/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "../support/ngap-r18.0.0/38413-i10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NGAP_PDUsetQoSInformation_H_
#define	_NGAP_PDUsetQoSInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NGAP_ExtendedPacketDelayBudget.h"
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NGAP_PDUsetQoSInformation__pduSetIntegratedHandlingInformation {
	NGAP_PDUsetQoSInformation__pduSetIntegratedHandlingInformation_true	= 0,
	NGAP_PDUsetQoSInformation__pduSetIntegratedHandlingInformation_false	= 1
	/*
	 * Enumeration is extensible
	 */
} e_NGAP_PDUsetQoSInformation__pduSetIntegratedHandlingInformation;

/* Forward declarations */
struct NGAP_PacketErrorRate;
struct NGAP_ProtocolExtensionContainer;

/* NGAP_PDUsetQoSInformation */
typedef struct NGAP_PDUsetQoSInformation {
	NGAP_ExtendedPacketDelayBudget_t	*pduSetDelayBudget;	/* OPTIONAL */
	struct NGAP_PacketErrorRate	*pduSetErrorRate;	/* OPTIONAL */
	long	*pduSetIntegratedHandlingInformation;	/* OPTIONAL */
	struct NGAP_ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_PDUsetQoSInformation_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_NGAP_pduSetIntegratedHandlingInformation_4;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_NGAP_PDUsetQoSInformation;
extern asn_SEQUENCE_specifics_t asn_SPC_NGAP_PDUsetQoSInformation_specs_1;
extern asn_TYPE_member_t asn_MBR_NGAP_PDUsetQoSInformation_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _NGAP_PDUsetQoSInformation_H_ */
#include <asn_internal.h>
