/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "../support/ngap-r18.0.0/38413-i10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#include "NGAP_NR-A2X-ServicesAuthorized.h"

#include "NGAP_ProtocolExtensionContainer.h"
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_type_NGAP_aerialUE_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  1,  1,  0,  1 }	/* (0..1,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_type_NGAP_aerialControllerUE_constr_6 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  1,  1,  0,  1 }	/* (0..1,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
static const asn_INTEGER_enum_map_t asn_MAP_NGAP_aerialUE_value2enum_2[] = {
	{ 0,	10,	"authorized" },
	{ 1,	14,	"not-authorized" }
	/* This list is extensible */
};
static const unsigned int asn_MAP_NGAP_aerialUE_enum2value_2[] = {
	0,	/* authorized(0) */
	1	/* not-authorized(1) */
	/* This list is extensible */
};
static const asn_INTEGER_specifics_t asn_SPC_NGAP_aerialUE_specs_2 = {
	asn_MAP_NGAP_aerialUE_value2enum_2,	/* "tag" => N; sorted by tag */
	asn_MAP_NGAP_aerialUE_enum2value_2,	/* N => "tag"; sorted by N */
	2,	/* Number of elements in the maps */
	3,	/* Extensions before this member */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_NGAP_aerialUE_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_NGAP_aerialUE_2 = {
	"aerialUE",
	"aerialUE",
	&asn_OP_NativeEnumerated,
	asn_DEF_NGAP_aerialUE_tags_2,
	sizeof(asn_DEF_NGAP_aerialUE_tags_2)
		/sizeof(asn_DEF_NGAP_aerialUE_tags_2[0]) - 1, /* 1 */
	asn_DEF_NGAP_aerialUE_tags_2,	/* Same as above */
	sizeof(asn_DEF_NGAP_aerialUE_tags_2)
		/sizeof(asn_DEF_NGAP_aerialUE_tags_2[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_NGAP_aerialUE_constr_2,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_NGAP_aerialUE_specs_2	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_NGAP_aerialControllerUE_value2enum_6[] = {
	{ 0,	10,	"authorized" },
	{ 1,	14,	"not-authorized" }
	/* This list is extensible */
};
static const unsigned int asn_MAP_NGAP_aerialControllerUE_enum2value_6[] = {
	0,	/* authorized(0) */
	1	/* not-authorized(1) */
	/* This list is extensible */
};
static const asn_INTEGER_specifics_t asn_SPC_NGAP_aerialControllerUE_specs_6 = {
	asn_MAP_NGAP_aerialControllerUE_value2enum_6,	/* "tag" => N; sorted by tag */
	asn_MAP_NGAP_aerialControllerUE_enum2value_6,	/* N => "tag"; sorted by N */
	2,	/* Number of elements in the maps */
	3,	/* Extensions before this member */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_NGAP_aerialControllerUE_tags_6[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_NGAP_aerialControllerUE_6 = {
	"aerialControllerUE",
	"aerialControllerUE",
	&asn_OP_NativeEnumerated,
	asn_DEF_NGAP_aerialControllerUE_tags_6,
	sizeof(asn_DEF_NGAP_aerialControllerUE_tags_6)
		/sizeof(asn_DEF_NGAP_aerialControllerUE_tags_6[0]) - 1, /* 1 */
	asn_DEF_NGAP_aerialControllerUE_tags_6,	/* Same as above */
	sizeof(asn_DEF_NGAP_aerialControllerUE_tags_6)
		/sizeof(asn_DEF_NGAP_aerialControllerUE_tags_6[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_NGAP_aerialControllerUE_constr_6,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_NGAP_aerialControllerUE_specs_6	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_NGAP_NR_A2X_ServicesAuthorized_1[] = {
	{ ATF_POINTER, 3, offsetof(struct NGAP_NR_A2X_ServicesAuthorized, aerialUE),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NGAP_aerialUE_2,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"aerialUE"
		},
	{ ATF_POINTER, 2, offsetof(struct NGAP_NR_A2X_ServicesAuthorized, aerialControllerUE),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NGAP_aerialControllerUE_6,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"aerialControllerUE"
		},
	{ ATF_POINTER, 1, offsetof(struct NGAP_NR_A2X_ServicesAuthorized, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NGAP_ProtocolExtensionContainer_11180P227,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"iE-Extensions"
		},
};
static const int asn_MAP_NGAP_NR_A2X_ServicesAuthorized_oms_1[] = { 0, 1, 2 };
static const ber_tlv_tag_t asn_DEF_NGAP_NR_A2X_ServicesAuthorized_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_NGAP_NR_A2X_ServicesAuthorized_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* aerialUE */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* aerialControllerUE */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* iE-Extensions */
};
asn_SEQUENCE_specifics_t asn_SPC_NGAP_NR_A2X_ServicesAuthorized_specs_1 = {
	sizeof(struct NGAP_NR_A2X_ServicesAuthorized),
	offsetof(struct NGAP_NR_A2X_ServicesAuthorized, _asn_ctx),
	asn_MAP_NGAP_NR_A2X_ServicesAuthorized_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_NGAP_NR_A2X_ServicesAuthorized_oms_1,	/* Optional members */
	3, 0,	/* Root/Additions */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_NGAP_NR_A2X_ServicesAuthorized = {
	"NR-A2X-ServicesAuthorized",
	"NR-A2X-ServicesAuthorized",
	&asn_OP_SEQUENCE,
	asn_DEF_NGAP_NR_A2X_ServicesAuthorized_tags_1,
	sizeof(asn_DEF_NGAP_NR_A2X_ServicesAuthorized_tags_1)
		/sizeof(asn_DEF_NGAP_NR_A2X_ServicesAuthorized_tags_1[0]), /* 1 */
	asn_DEF_NGAP_NR_A2X_ServicesAuthorized_tags_1,	/* Same as above */
	sizeof(asn_DEF_NGAP_NR_A2X_ServicesAuthorized_tags_1)
		/sizeof(asn_DEF_NGAP_NR_A2X_ServicesAuthorized_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_NGAP_NR_A2X_ServicesAuthorized_1,
	3,	/* Elements count */
	&asn_SPC_NGAP_NR_A2X_ServicesAuthorized_specs_1	/* Additional specs */
};

