/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "../support/ngap-r18.0.0/38413-i10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NGAP_FiveGCAction_H_
#define	_NGAP_FiveGCAction_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NGAP_FiveGCAction_PR {
	NGAP_FiveGCAction_PR_NOTHING,	/* No components present */
	NGAP_FiveGCAction_PR_hLComActivate,
	NGAP_FiveGCAction_PR_hLComDeactivate,
	NGAP_FiveGCAction_PR_choice_Extensions
} NGAP_FiveGCAction_PR;

/* Forward declarations */
struct NGAP_HLComActivate;
struct NGAP_HLComDeactivate;
struct NGAP_ProtocolIE_SingleContainer;

/* NGAP_FiveGCAction */
typedef struct NGAP_FiveGCAction {
	NGAP_FiveGCAction_PR present;
	union NGAP_FiveGCAction_u {
		struct NGAP_HLComActivate	*hLComActivate;
		struct NGAP_HLComDeactivate	*hLComDeactivate;
		struct NGAP_ProtocolIE_SingleContainer	*choice_Extensions;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_FiveGCAction_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NGAP_FiveGCAction;
extern asn_CHOICE_specifics_t asn_SPC_NGAP_FiveGCAction_specs_1;
extern asn_TYPE_member_t asn_MBR_NGAP_FiveGCAction_1[3];
extern asn_per_constraints_t asn_PER_type_NGAP_FiveGCAction_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _NGAP_FiveGCAction_H_ */
#include <asn_internal.h>
