/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "../support/ngap-r18.0.0/38413-i10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NGAP_RANTimingSynchronisationStatusInfo_H_
#define	_NGAP_RANTimingSynchronisationStatusInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <BIT_STRING.h>
#include "NGAP_ParentTImeSource.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NGAP_RANTimingSynchronisationStatusInfo__synchronisationState {
	NGAP_RANTimingSynchronisationStatusInfo__synchronisationState_locked	= 0,
	NGAP_RANTimingSynchronisationStatusInfo__synchronisationState_holdover	= 1,
	NGAP_RANTimingSynchronisationStatusInfo__synchronisationState_freerun	= 2
	/*
	 * Enumeration is extensible
	 */
} e_NGAP_RANTimingSynchronisationStatusInfo__synchronisationState;
typedef enum NGAP_RANTimingSynchronisationStatusInfo__traceabletoUTC {
	NGAP_RANTimingSynchronisationStatusInfo__traceabletoUTC_true	= 0,
	NGAP_RANTimingSynchronisationStatusInfo__traceabletoUTC_false	= 1
	/*
	 * Enumeration is extensible
	 */
} e_NGAP_RANTimingSynchronisationStatusInfo__traceabletoUTC;
typedef enum NGAP_RANTimingSynchronisationStatusInfo__traceabletoGNSS {
	NGAP_RANTimingSynchronisationStatusInfo__traceabletoGNSS_true	= 0,
	NGAP_RANTimingSynchronisationStatusInfo__traceabletoGNSS_false	= 1
	/*
	 * Enumeration is extensible
	 */
} e_NGAP_RANTimingSynchronisationStatusInfo__traceabletoGNSS;

/* Forward declarations */
struct NGAP_ClockAccuracy;
struct NGAP_ProtocolExtensionContainer;

/* NGAP_RANTimingSynchronisationStatusInfo */
typedef struct NGAP_RANTimingSynchronisationStatusInfo {
	long	*synchronisationState;	/* OPTIONAL */
	long	*traceabletoUTC;	/* OPTIONAL */
	long	*traceabletoGNSS;	/* OPTIONAL */
	BIT_STRING_t	*clockFrequencyStability;	/* OPTIONAL */
	struct NGAP_ClockAccuracy	*clockAccuracy;	/* OPTIONAL */
	NGAP_ParentTImeSource_t	*parentTImeSource;	/* OPTIONAL */
	struct NGAP_ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_RANTimingSynchronisationStatusInfo_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_NGAP_synchronisationState_2;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_NGAP_traceabletoUTC_7;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_NGAP_traceabletoGNSS_11;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_NGAP_RANTimingSynchronisationStatusInfo;
extern asn_SEQUENCE_specifics_t asn_SPC_NGAP_RANTimingSynchronisationStatusInfo_specs_1;
extern asn_TYPE_member_t asn_MBR_NGAP_RANTimingSynchronisationStatusInfo_1[7];

#ifdef __cplusplus
}
#endif

#endif	/* _NGAP_RANTimingSynchronisationStatusInfo_H_ */
#include <asn_internal.h>
