/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "../support/ngap-r18.0.0/38413-i10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NGAP_CongestionInformationRequest_H_
#define	_NGAP_CongestionInformationRequest_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NGAP_CongestionInformationRequest {
	NGAP_CongestionInformationRequest_ul	= 0,
	NGAP_CongestionInformationRequest_dl	= 1,
	NGAP_CongestionInformationRequest_both	= 2,
	NGAP_CongestionInformationRequest_stop	= 3
	/*
	 * Enumeration is extensible
	 */
} e_NGAP_CongestionInformationRequest;

/* NGAP_CongestionInformationRequest */
typedef long	 NGAP_CongestionInformationRequest_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_NGAP_CongestionInformationRequest_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_CongestionInformationRequest;
extern const asn_INTEGER_specifics_t asn_SPC_NGAP_CongestionInformationRequest_specs_1;
asn_struct_free_f NGAP_CongestionInformationRequest_free;
asn_struct_print_f NGAP_CongestionInformationRequest_print;
asn_constr_check_f NGAP_CongestionInformationRequest_constraint;
per_type_decoder_f NGAP_CongestionInformationRequest_decode_aper;
per_type_encoder_f NGAP_CongestionInformationRequest_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _NGAP_CongestionInformationRequest_H_ */
#include <asn_internal.h>
