/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "../support/ngap-r18.0.0/38413-i10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#include "NGAP_NR-Paging-Long-eDRX-Cycle-for-RRC-INACTIVE.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_NGAP_NR_Paging_Long_eDRX_Cycle_for_RRC_INACTIVE_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  4,  4,  0,  9 }	/* (0..9,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
static const asn_INTEGER_enum_map_t asn_MAP_NGAP_NR_Paging_Long_eDRX_Cycle_for_RRC_INACTIVE_value2enum_1[] = {
	{ 0,	3,	"hf2" },
	{ 1,	3,	"hf4" },
	{ 2,	3,	"hf8" },
	{ 3,	4,	"hf16" },
	{ 4,	4,	"hf32" },
	{ 5,	4,	"hf64" },
	{ 6,	5,	"hf128" },
	{ 7,	5,	"hf256" },
	{ 8,	5,	"hf512" },
	{ 9,	6,	"hf1024" }
	/* This list is extensible */
};
static const unsigned int asn_MAP_NGAP_NR_Paging_Long_eDRX_Cycle_for_RRC_INACTIVE_enum2value_1[] = {
	9,	/* hf1024(9) */
	6,	/* hf128(6) */
	3,	/* hf16(3) */
	0,	/* hf2(0) */
	7,	/* hf256(7) */
	4,	/* hf32(4) */
	1,	/* hf4(1) */
	8,	/* hf512(8) */
	5,	/* hf64(5) */
	2	/* hf8(2) */
	/* This list is extensible */
};
const asn_INTEGER_specifics_t asn_SPC_NGAP_NR_Paging_Long_eDRX_Cycle_for_RRC_INACTIVE_specs_1 = {
	asn_MAP_NGAP_NR_Paging_Long_eDRX_Cycle_for_RRC_INACTIVE_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_NGAP_NR_Paging_Long_eDRX_Cycle_for_RRC_INACTIVE_enum2value_1,	/* N => "tag"; sorted by N */
	10,	/* Number of elements in the maps */
	11,	/* Extensions before this member */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_NGAP_NR_Paging_Long_eDRX_Cycle_for_RRC_INACTIVE_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_NGAP_NR_Paging_Long_eDRX_Cycle_for_RRC_INACTIVE = {
	"NR-Paging-Long-eDRX-Cycle-for-RRC-INACTIVE",
	"NR-Paging-Long-eDRX-Cycle-for-RRC-INACTIVE",
	&asn_OP_NativeEnumerated,
	asn_DEF_NGAP_NR_Paging_Long_eDRX_Cycle_for_RRC_INACTIVE_tags_1,
	sizeof(asn_DEF_NGAP_NR_Paging_Long_eDRX_Cycle_for_RRC_INACTIVE_tags_1)
		/sizeof(asn_DEF_NGAP_NR_Paging_Long_eDRX_Cycle_for_RRC_INACTIVE_tags_1[0]), /* 1 */
	asn_DEF_NGAP_NR_Paging_Long_eDRX_Cycle_for_RRC_INACTIVE_tags_1,	/* Same as above */
	sizeof(asn_DEF_NGAP_NR_Paging_Long_eDRX_Cycle_for_RRC_INACTIVE_tags_1)
		/sizeof(asn_DEF_NGAP_NR_Paging_Long_eDRX_Cycle_for_RRC_INACTIVE_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_NGAP_NR_Paging_Long_eDRX_Cycle_for_RRC_INACTIVE_constr_1,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_NGAP_NR_Paging_Long_eDRX_Cycle_for_RRC_INACTIVE_specs_1	/* Additional specs */
};

