/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "../support/ngap-r18.0.0/38413-i10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NGAP_A2X_PC5_QoS_Flow_Item_H_
#define	_NGAP_A2X_PC5_QoS_Flow_Item_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NGAP_A2X_PC5_QoS_Flow_Item__a2X_Range {
	NGAP_A2X_PC5_QoS_Flow_Item__a2X_Range_m50	= 0,
	NGAP_A2X_PC5_QoS_Flow_Item__a2X_Range_m80	= 1,
	NGAP_A2X_PC5_QoS_Flow_Item__a2X_Range_m180	= 2,
	NGAP_A2X_PC5_QoS_Flow_Item__a2X_Range_m200	= 3,
	NGAP_A2X_PC5_QoS_Flow_Item__a2X_Range_m350	= 4,
	NGAP_A2X_PC5_QoS_Flow_Item__a2X_Range_m400	= 5,
	NGAP_A2X_PC5_QoS_Flow_Item__a2X_Range_m500	= 6,
	NGAP_A2X_PC5_QoS_Flow_Item__a2X_Range_m700	= 7,
	NGAP_A2X_PC5_QoS_Flow_Item__a2X_Range_m1000	= 8
	/*
	 * Enumeration is extensible
	 */
} e_NGAP_A2X_PC5_QoS_Flow_Item__a2X_Range;

/* Forward declarations */
struct NGAP_A2X_PC5_FlowBitRates;
struct NGAP_ProtocolExtensionContainer;

/* NGAP_A2X-PC5-QoS-Flow-Item */
typedef struct NGAP_A2X_PC5_QoS_Flow_Item {
	long	 a2X_PQI;
	struct NGAP_A2X_PC5_FlowBitRates	*a2X_PC5_FlowBitRates;	/* OPTIONAL */
	long	*a2X_Range;	/* OPTIONAL */
	struct NGAP_ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_A2X_PC5_QoS_Flow_Item_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_NGAP_a2X_Range_4;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_NGAP_A2X_PC5_QoS_Flow_Item;
extern asn_SEQUENCE_specifics_t asn_SPC_NGAP_A2X_PC5_QoS_Flow_Item_specs_1;
extern asn_TYPE_member_t asn_MBR_NGAP_A2X_PC5_QoS_Flow_Item_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _NGAP_A2X_PC5_QoS_Flow_Item_H_ */
#include <asn_internal.h>
