/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-Containers"
 * 	found in "../support/ngap-r18.0.0/38413-i10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NGAP_ProtocolIE_Container_H_
#define	_NGAP_ProtocolIE_Container_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct NGAP_PDUSessionResourceSetupRequestIEs;
struct NGAP_PDUSessionResourceSetupResponseIEs;
struct NGAP_PDUSessionResourceReleaseCommandIEs;
struct NGAP_PDUSessionResourceReleaseResponseIEs;
struct NGAP_PDUSessionResourceModifyRequestIEs;
struct NGAP_PDUSessionResourceModifyResponseIEs;
struct NGAP_PDUSessionResourceNotifyIEs;
struct NGAP_PDUSessionResourceModifyIndicationIEs;
struct NGAP_PDUSessionResourceModifyConfirmIEs;
struct NGAP_InitialContextSetupRequestIEs;
struct NGAP_InitialContextSetupResponseIEs;
struct NGAP_InitialContextSetupFailureIEs;
struct NGAP_UEContextReleaseRequest_IEs;
struct NGAP_UEContextReleaseCommand_IEs;
struct NGAP_UEContextReleaseComplete_IEs;
struct NGAP_UEContextResumeRequestIEs;
struct NGAP_UEContextResumeResponseIEs;
struct NGAP_UEContextResumeFailureIEs;
struct NGAP_UEContextSuspendRequestIEs;
struct NGAP_UEContextSuspendResponseIEs;
struct NGAP_UEContextSuspendFailureIEs;
struct NGAP_UEContextModificationRequestIEs;
struct NGAP_UEContextModificationResponseIEs;
struct NGAP_UEContextModificationFailureIEs;
struct NGAP_RRCInactiveTransitionReportIEs;
struct NGAP_RetrieveUEInformationIEs;
struct NGAP_UEInformationTransferIEs;
struct NGAP_RANCPRelocationIndicationIEs;
struct NGAP_HandoverRequiredIEs;
struct NGAP_HandoverCommandIEs;
struct NGAP_HandoverPreparationFailureIEs;
struct NGAP_HandoverRequestIEs;
struct NGAP_HandoverRequestAcknowledgeIEs;
struct NGAP_HandoverFailureIEs;
struct NGAP_HandoverNotifyIEs;
struct NGAP_PathSwitchRequestIEs;
struct NGAP_PathSwitchRequestAcknowledgeIEs;
struct NGAP_PathSwitchRequestFailureIEs;
struct NGAP_HandoverCancelIEs;
struct NGAP_HandoverCancelAcknowledgeIEs;
struct NGAP_HandoverSuccessIEs;
struct NGAP_UplinkRANEarlyStatusTransferIEs;
struct NGAP_DownlinkRANEarlyStatusTransferIEs;
struct NGAP_UplinkRANStatusTransferIEs;
struct NGAP_DownlinkRANStatusTransferIEs;
struct NGAP_PagingIEs;
struct NGAP_InitialUEMessage_IEs;
struct NGAP_DownlinkNASTransport_IEs;
struct NGAP_UplinkNASTransport_IEs;
struct NGAP_NASNonDeliveryIndication_IEs;
struct NGAP_RerouteNASRequest_IEs;
struct NGAP_NGSetupRequestIEs;
struct NGAP_NGSetupResponseIEs;
struct NGAP_NGSetupFailureIEs;
struct NGAP_RANConfigurationUpdateIEs;
struct NGAP_RANConfigurationUpdateAcknowledgeIEs;
struct NGAP_RANConfigurationUpdateFailureIEs;
struct NGAP_AMFConfigurationUpdateIEs;
struct NGAP_AMFConfigurationUpdateAcknowledgeIEs;
struct NGAP_AMFConfigurationUpdateFailureIEs;
struct NGAP_AMFStatusIndicationIEs;
struct NGAP_NGResetIEs;
struct NGAP_NGResetAcknowledgeIEs;
struct NGAP_ErrorIndicationIEs;
struct NGAP_OverloadStartIEs;
struct NGAP_OverloadStopIEs;
struct NGAP_UplinkRANConfigurationTransferIEs;
struct NGAP_DownlinkRANConfigurationTransferIEs;
struct NGAP_WriteReplaceWarningRequestIEs;
struct NGAP_WriteReplaceWarningResponseIEs;
struct NGAP_PWSCancelRequestIEs;
struct NGAP_PWSCancelResponseIEs;
struct NGAP_PWSRestartIndicationIEs;
struct NGAP_PWSFailureIndicationIEs;
struct NGAP_DownlinkUEAssociatedNRPPaTransportIEs;
struct NGAP_UplinkUEAssociatedNRPPaTransportIEs;
struct NGAP_DownlinkNonUEAssociatedNRPPaTransportIEs;
struct NGAP_UplinkNonUEAssociatedNRPPaTransportIEs;
struct NGAP_TraceStartIEs;
struct NGAP_TraceFailureIndicationIEs;
struct NGAP_DeactivateTraceIEs;
struct NGAP_CellTrafficTraceIEs;
struct NGAP_LocationReportingControlIEs;
struct NGAP_LocationReportingFailureIndicationIEs;
struct NGAP_LocationReportIEs;
struct NGAP_UETNLABindingReleaseRequestIEs;
struct NGAP_UERadioCapabilityInfoIndicationIEs;
struct NGAP_UERadioCapabilityCheckRequestIEs;
struct NGAP_UERadioCapabilityCheckResponseIEs;
struct NGAP_SecondaryRATDataUsageReportIEs;
struct NGAP_UplinkRIMInformationTransferIEs;
struct NGAP_DownlinkRIMInformationTransferIEs;
struct NGAP_ConnectionEstablishmentIndicationIEs;
struct NGAP_UERadioCapabilityIDMappingRequestIEs;
struct NGAP_UERadioCapabilityIDMappingResponseIEs;
struct NGAP_AMFCPRelocationIndicationIEs;
struct NGAP_BroadcastSessionSetupRequestIEs;
struct NGAP_BroadcastSessionSetupResponseIEs;
struct NGAP_BroadcastSessionSetupFailureIEs;
struct NGAP_BroadcastSessionModificationRequestIEs;
struct NGAP_BroadcastSessionModificationResponseIEs;
struct NGAP_BroadcastSessionModificationFailureIEs;
struct NGAP_BroadcastSessionReleaseRequestIEs;
struct NGAP_BroadcastSessionReleaseRequiredIEs;
struct NGAP_BroadcastSessionReleaseResponseIEs;
struct NGAP_BroadcastSessionTransportRequestIEs;
struct NGAP_BroadcastSessionTransportResponseIEs;
struct NGAP_BroadcastSessionTransportFailureIEs;
struct NGAP_DistributionSetupRequestIEs;
struct NGAP_DistributionSetupResponseIEs;
struct NGAP_DistributionSetupFailureIEs;
struct NGAP_DistributionReleaseRequestIEs;
struct NGAP_DistributionReleaseResponseIEs;
struct NGAP_MulticastSessionActivationRequestIEs;
struct NGAP_MulticastSessionActivationResponseIEs;
struct NGAP_MulticastSessionActivationFailureIEs;
struct NGAP_MulticastSessionDeactivationRequestIEs;
struct NGAP_MulticastSessionDeactivationResponseIEs;
struct NGAP_MulticastSessionUpdateRequestIEs;
struct NGAP_MulticastSessionUpdateResponseIEs;
struct NGAP_MulticastSessionUpdateFailureIEs;
struct NGAP_MulticastGroupPagingIEs;
struct NGAP_TimingSynchronisationStatusRequestIEs;
struct NGAP_TimingSynchronisationStatusResponseIEs;
struct NGAP_TimingSynchronisationStatusFailureIEs;
struct NGAP_TimingSynchronisationStatusReportIEs;
struct NGAP_MTCommunicationHandlingRequestIEs;
struct NGAP_MTCommunicationHandlingResponseIEs;
struct NGAP_MTCommunicationHandlingFailureIEs;
struct NGAP_RANPagingRequestIEs;
struct NGAP_MBSSessionSetupOrModRequestTransferIEs;
struct NGAP_MulticastSessionUpdateRequestTransferIEs;
struct NGAP_PDUSessionResourceModifyRequestTransferIEs;
struct NGAP_PDUSessionResourceSetupRequestTransferIEs;

/* NGAP_ProtocolIE-Container */
typedef struct NGAP_ProtocolIE_Container_11139P0 {
	A_SEQUENCE_OF(struct NGAP_PDUSessionResourceSetupRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P0_t;
typedef struct NGAP_ProtocolIE_Container_11139P1 {
	A_SEQUENCE_OF(struct NGAP_PDUSessionResourceSetupResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P1_t;
typedef struct NGAP_ProtocolIE_Container_11139P2 {
	A_SEQUENCE_OF(struct NGAP_PDUSessionResourceReleaseCommandIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P2_t;
typedef struct NGAP_ProtocolIE_Container_11139P3 {
	A_SEQUENCE_OF(struct NGAP_PDUSessionResourceReleaseResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P3_t;
typedef struct NGAP_ProtocolIE_Container_11139P4 {
	A_SEQUENCE_OF(struct NGAP_PDUSessionResourceModifyRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P4_t;
typedef struct NGAP_ProtocolIE_Container_11139P5 {
	A_SEQUENCE_OF(struct NGAP_PDUSessionResourceModifyResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P5_t;
typedef struct NGAP_ProtocolIE_Container_11139P6 {
	A_SEQUENCE_OF(struct NGAP_PDUSessionResourceNotifyIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P6_t;
typedef struct NGAP_ProtocolIE_Container_11139P7 {
	A_SEQUENCE_OF(struct NGAP_PDUSessionResourceModifyIndicationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P7_t;
typedef struct NGAP_ProtocolIE_Container_11139P8 {
	A_SEQUENCE_OF(struct NGAP_PDUSessionResourceModifyConfirmIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P8_t;
typedef struct NGAP_ProtocolIE_Container_11139P9 {
	A_SEQUENCE_OF(struct NGAP_InitialContextSetupRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P9_t;
typedef struct NGAP_ProtocolIE_Container_11139P10 {
	A_SEQUENCE_OF(struct NGAP_InitialContextSetupResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P10_t;
typedef struct NGAP_ProtocolIE_Container_11139P11 {
	A_SEQUENCE_OF(struct NGAP_InitialContextSetupFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P11_t;
typedef struct NGAP_ProtocolIE_Container_11139P12 {
	A_SEQUENCE_OF(struct NGAP_UEContextReleaseRequest_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P12_t;
typedef struct NGAP_ProtocolIE_Container_11139P13 {
	A_SEQUENCE_OF(struct NGAP_UEContextReleaseCommand_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P13_t;
typedef struct NGAP_ProtocolIE_Container_11139P14 {
	A_SEQUENCE_OF(struct NGAP_UEContextReleaseComplete_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P14_t;
typedef struct NGAP_ProtocolIE_Container_11139P15 {
	A_SEQUENCE_OF(struct NGAP_UEContextResumeRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P15_t;
typedef struct NGAP_ProtocolIE_Container_11139P16 {
	A_SEQUENCE_OF(struct NGAP_UEContextResumeResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P16_t;
typedef struct NGAP_ProtocolIE_Container_11139P17 {
	A_SEQUENCE_OF(struct NGAP_UEContextResumeFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P17_t;
typedef struct NGAP_ProtocolIE_Container_11139P18 {
	A_SEQUENCE_OF(struct NGAP_UEContextSuspendRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P18_t;
typedef struct NGAP_ProtocolIE_Container_11139P19 {
	A_SEQUENCE_OF(struct NGAP_UEContextSuspendResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P19_t;
typedef struct NGAP_ProtocolIE_Container_11139P20 {
	A_SEQUENCE_OF(struct NGAP_UEContextSuspendFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P20_t;
typedef struct NGAP_ProtocolIE_Container_11139P21 {
	A_SEQUENCE_OF(struct NGAP_UEContextModificationRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P21_t;
typedef struct NGAP_ProtocolIE_Container_11139P22 {
	A_SEQUENCE_OF(struct NGAP_UEContextModificationResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P22_t;
typedef struct NGAP_ProtocolIE_Container_11139P23 {
	A_SEQUENCE_OF(struct NGAP_UEContextModificationFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P23_t;
typedef struct NGAP_ProtocolIE_Container_11139P24 {
	A_SEQUENCE_OF(struct NGAP_RRCInactiveTransitionReportIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P24_t;
typedef struct NGAP_ProtocolIE_Container_11139P25 {
	A_SEQUENCE_OF(struct NGAP_RetrieveUEInformationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P25_t;
typedef struct NGAP_ProtocolIE_Container_11139P26 {
	A_SEQUENCE_OF(struct NGAP_UEInformationTransferIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P26_t;
typedef struct NGAP_ProtocolIE_Container_11139P27 {
	A_SEQUENCE_OF(struct NGAP_RANCPRelocationIndicationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P27_t;
typedef struct NGAP_ProtocolIE_Container_11139P28 {
	A_SEQUENCE_OF(struct NGAP_HandoverRequiredIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P28_t;
typedef struct NGAP_ProtocolIE_Container_11139P29 {
	A_SEQUENCE_OF(struct NGAP_HandoverCommandIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P29_t;
typedef struct NGAP_ProtocolIE_Container_11139P30 {
	A_SEQUENCE_OF(struct NGAP_HandoverPreparationFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P30_t;
typedef struct NGAP_ProtocolIE_Container_11139P31 {
	A_SEQUENCE_OF(struct NGAP_HandoverRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P31_t;
typedef struct NGAP_ProtocolIE_Container_11139P32 {
	A_SEQUENCE_OF(struct NGAP_HandoverRequestAcknowledgeIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P32_t;
typedef struct NGAP_ProtocolIE_Container_11139P33 {
	A_SEQUENCE_OF(struct NGAP_HandoverFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P33_t;
typedef struct NGAP_ProtocolIE_Container_11139P34 {
	A_SEQUENCE_OF(struct NGAP_HandoverNotifyIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P34_t;
typedef struct NGAP_ProtocolIE_Container_11139P35 {
	A_SEQUENCE_OF(struct NGAP_PathSwitchRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P35_t;
typedef struct NGAP_ProtocolIE_Container_11139P36 {
	A_SEQUENCE_OF(struct NGAP_PathSwitchRequestAcknowledgeIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P36_t;
typedef struct NGAP_ProtocolIE_Container_11139P37 {
	A_SEQUENCE_OF(struct NGAP_PathSwitchRequestFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P37_t;
typedef struct NGAP_ProtocolIE_Container_11139P38 {
	A_SEQUENCE_OF(struct NGAP_HandoverCancelIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P38_t;
typedef struct NGAP_ProtocolIE_Container_11139P39 {
	A_SEQUENCE_OF(struct NGAP_HandoverCancelAcknowledgeIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P39_t;
typedef struct NGAP_ProtocolIE_Container_11139P40 {
	A_SEQUENCE_OF(struct NGAP_HandoverSuccessIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P40_t;
typedef struct NGAP_ProtocolIE_Container_11139P41 {
	A_SEQUENCE_OF(struct NGAP_UplinkRANEarlyStatusTransferIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P41_t;
typedef struct NGAP_ProtocolIE_Container_11139P42 {
	A_SEQUENCE_OF(struct NGAP_DownlinkRANEarlyStatusTransferIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P42_t;
typedef struct NGAP_ProtocolIE_Container_11139P43 {
	A_SEQUENCE_OF(struct NGAP_UplinkRANStatusTransferIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P43_t;
typedef struct NGAP_ProtocolIE_Container_11139P44 {
	A_SEQUENCE_OF(struct NGAP_DownlinkRANStatusTransferIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P44_t;
typedef struct NGAP_ProtocolIE_Container_11139P45 {
	A_SEQUENCE_OF(struct NGAP_PagingIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P45_t;
typedef struct NGAP_ProtocolIE_Container_11139P46 {
	A_SEQUENCE_OF(struct NGAP_InitialUEMessage_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P46_t;
typedef struct NGAP_ProtocolIE_Container_11139P47 {
	A_SEQUENCE_OF(struct NGAP_DownlinkNASTransport_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P47_t;
typedef struct NGAP_ProtocolIE_Container_11139P48 {
	A_SEQUENCE_OF(struct NGAP_UplinkNASTransport_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P48_t;
typedef struct NGAP_ProtocolIE_Container_11139P49 {
	A_SEQUENCE_OF(struct NGAP_NASNonDeliveryIndication_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P49_t;
typedef struct NGAP_ProtocolIE_Container_11139P50 {
	A_SEQUENCE_OF(struct NGAP_RerouteNASRequest_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P50_t;
typedef struct NGAP_ProtocolIE_Container_11139P51 {
	A_SEQUENCE_OF(struct NGAP_NGSetupRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P51_t;
typedef struct NGAP_ProtocolIE_Container_11139P52 {
	A_SEQUENCE_OF(struct NGAP_NGSetupResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P52_t;
typedef struct NGAP_ProtocolIE_Container_11139P53 {
	A_SEQUENCE_OF(struct NGAP_NGSetupFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P53_t;
typedef struct NGAP_ProtocolIE_Container_11139P54 {
	A_SEQUENCE_OF(struct NGAP_RANConfigurationUpdateIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P54_t;
typedef struct NGAP_ProtocolIE_Container_11139P55 {
	A_SEQUENCE_OF(struct NGAP_RANConfigurationUpdateAcknowledgeIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P55_t;
typedef struct NGAP_ProtocolIE_Container_11139P56 {
	A_SEQUENCE_OF(struct NGAP_RANConfigurationUpdateFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P56_t;
typedef struct NGAP_ProtocolIE_Container_11139P57 {
	A_SEQUENCE_OF(struct NGAP_AMFConfigurationUpdateIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P57_t;
typedef struct NGAP_ProtocolIE_Container_11139P58 {
	A_SEQUENCE_OF(struct NGAP_AMFConfigurationUpdateAcknowledgeIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P58_t;
typedef struct NGAP_ProtocolIE_Container_11139P59 {
	A_SEQUENCE_OF(struct NGAP_AMFConfigurationUpdateFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P59_t;
typedef struct NGAP_ProtocolIE_Container_11139P60 {
	A_SEQUENCE_OF(struct NGAP_AMFStatusIndicationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P60_t;
typedef struct NGAP_ProtocolIE_Container_11139P61 {
	A_SEQUENCE_OF(struct NGAP_NGResetIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P61_t;
typedef struct NGAP_ProtocolIE_Container_11139P62 {
	A_SEQUENCE_OF(struct NGAP_NGResetAcknowledgeIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P62_t;
typedef struct NGAP_ProtocolIE_Container_11139P63 {
	A_SEQUENCE_OF(struct NGAP_ErrorIndicationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P63_t;
typedef struct NGAP_ProtocolIE_Container_11139P64 {
	A_SEQUENCE_OF(struct NGAP_OverloadStartIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P64_t;
typedef struct NGAP_ProtocolIE_Container_11139P65 {
	A_SEQUENCE_OF(struct NGAP_OverloadStopIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P65_t;
typedef struct NGAP_ProtocolIE_Container_11139P66 {
	A_SEQUENCE_OF(struct NGAP_UplinkRANConfigurationTransferIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P66_t;
typedef struct NGAP_ProtocolIE_Container_11139P67 {
	A_SEQUENCE_OF(struct NGAP_DownlinkRANConfigurationTransferIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P67_t;
typedef struct NGAP_ProtocolIE_Container_11139P68 {
	A_SEQUENCE_OF(struct NGAP_WriteReplaceWarningRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P68_t;
typedef struct NGAP_ProtocolIE_Container_11139P69 {
	A_SEQUENCE_OF(struct NGAP_WriteReplaceWarningResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P69_t;
typedef struct NGAP_ProtocolIE_Container_11139P70 {
	A_SEQUENCE_OF(struct NGAP_PWSCancelRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P70_t;
typedef struct NGAP_ProtocolIE_Container_11139P71 {
	A_SEQUENCE_OF(struct NGAP_PWSCancelResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P71_t;
typedef struct NGAP_ProtocolIE_Container_11139P72 {
	A_SEQUENCE_OF(struct NGAP_PWSRestartIndicationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P72_t;
typedef struct NGAP_ProtocolIE_Container_11139P73 {
	A_SEQUENCE_OF(struct NGAP_PWSFailureIndicationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P73_t;
typedef struct NGAP_ProtocolIE_Container_11139P74 {
	A_SEQUENCE_OF(struct NGAP_DownlinkUEAssociatedNRPPaTransportIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P74_t;
typedef struct NGAP_ProtocolIE_Container_11139P75 {
	A_SEQUENCE_OF(struct NGAP_UplinkUEAssociatedNRPPaTransportIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P75_t;
typedef struct NGAP_ProtocolIE_Container_11139P76 {
	A_SEQUENCE_OF(struct NGAP_DownlinkNonUEAssociatedNRPPaTransportIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P76_t;
typedef struct NGAP_ProtocolIE_Container_11139P77 {
	A_SEQUENCE_OF(struct NGAP_UplinkNonUEAssociatedNRPPaTransportIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P77_t;
typedef struct NGAP_ProtocolIE_Container_11139P78 {
	A_SEQUENCE_OF(struct NGAP_TraceStartIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P78_t;
typedef struct NGAP_ProtocolIE_Container_11139P79 {
	A_SEQUENCE_OF(struct NGAP_TraceFailureIndicationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P79_t;
typedef struct NGAP_ProtocolIE_Container_11139P80 {
	A_SEQUENCE_OF(struct NGAP_DeactivateTraceIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P80_t;
typedef struct NGAP_ProtocolIE_Container_11139P81 {
	A_SEQUENCE_OF(struct NGAP_CellTrafficTraceIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P81_t;
typedef struct NGAP_ProtocolIE_Container_11139P82 {
	A_SEQUENCE_OF(struct NGAP_LocationReportingControlIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P82_t;
typedef struct NGAP_ProtocolIE_Container_11139P83 {
	A_SEQUENCE_OF(struct NGAP_LocationReportingFailureIndicationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P83_t;
typedef struct NGAP_ProtocolIE_Container_11139P84 {
	A_SEQUENCE_OF(struct NGAP_LocationReportIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P84_t;
typedef struct NGAP_ProtocolIE_Container_11139P85 {
	A_SEQUENCE_OF(struct NGAP_UETNLABindingReleaseRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P85_t;
typedef struct NGAP_ProtocolIE_Container_11139P86 {
	A_SEQUENCE_OF(struct NGAP_UERadioCapabilityInfoIndicationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P86_t;
typedef struct NGAP_ProtocolIE_Container_11139P87 {
	A_SEQUENCE_OF(struct NGAP_UERadioCapabilityCheckRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P87_t;
typedef struct NGAP_ProtocolIE_Container_11139P88 {
	A_SEQUENCE_OF(struct NGAP_UERadioCapabilityCheckResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P88_t;
typedef struct NGAP_ProtocolIE_Container_11139P89 {
	A_SEQUENCE_OF(struct NGAP_SecondaryRATDataUsageReportIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P89_t;
typedef struct NGAP_ProtocolIE_Container_11139P90 {
	A_SEQUENCE_OF(struct NGAP_UplinkRIMInformationTransferIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P90_t;
typedef struct NGAP_ProtocolIE_Container_11139P91 {
	A_SEQUENCE_OF(struct NGAP_DownlinkRIMInformationTransferIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P91_t;
typedef struct NGAP_ProtocolIE_Container_11139P92 {
	A_SEQUENCE_OF(struct NGAP_ConnectionEstablishmentIndicationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P92_t;
typedef struct NGAP_ProtocolIE_Container_11139P93 {
	A_SEQUENCE_OF(struct NGAP_UERadioCapabilityIDMappingRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P93_t;
typedef struct NGAP_ProtocolIE_Container_11139P94 {
	A_SEQUENCE_OF(struct NGAP_UERadioCapabilityIDMappingResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P94_t;
typedef struct NGAP_ProtocolIE_Container_11139P95 {
	A_SEQUENCE_OF(struct NGAP_AMFCPRelocationIndicationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P95_t;
typedef struct NGAP_ProtocolIE_Container_11139P96 {
	A_SEQUENCE_OF(struct NGAP_BroadcastSessionSetupRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P96_t;
typedef struct NGAP_ProtocolIE_Container_11139P97 {
	A_SEQUENCE_OF(struct NGAP_BroadcastSessionSetupResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P97_t;
typedef struct NGAP_ProtocolIE_Container_11139P98 {
	A_SEQUENCE_OF(struct NGAP_BroadcastSessionSetupFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P98_t;
typedef struct NGAP_ProtocolIE_Container_11139P99 {
	A_SEQUENCE_OF(struct NGAP_BroadcastSessionModificationRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P99_t;
typedef struct NGAP_ProtocolIE_Container_11139P100 {
	A_SEQUENCE_OF(struct NGAP_BroadcastSessionModificationResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P100_t;
typedef struct NGAP_ProtocolIE_Container_11139P101 {
	A_SEQUENCE_OF(struct NGAP_BroadcastSessionModificationFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P101_t;
typedef struct NGAP_ProtocolIE_Container_11139P102 {
	A_SEQUENCE_OF(struct NGAP_BroadcastSessionReleaseRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P102_t;
typedef struct NGAP_ProtocolIE_Container_11139P103 {
	A_SEQUENCE_OF(struct NGAP_BroadcastSessionReleaseRequiredIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P103_t;
typedef struct NGAP_ProtocolIE_Container_11139P104 {
	A_SEQUENCE_OF(struct NGAP_BroadcastSessionReleaseResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P104_t;
typedef struct NGAP_ProtocolIE_Container_11139P105 {
	A_SEQUENCE_OF(struct NGAP_BroadcastSessionTransportRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P105_t;
typedef struct NGAP_ProtocolIE_Container_11139P106 {
	A_SEQUENCE_OF(struct NGAP_BroadcastSessionTransportResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P106_t;
typedef struct NGAP_ProtocolIE_Container_11139P107 {
	A_SEQUENCE_OF(struct NGAP_BroadcastSessionTransportFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P107_t;
typedef struct NGAP_ProtocolIE_Container_11139P108 {
	A_SEQUENCE_OF(struct NGAP_DistributionSetupRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P108_t;
typedef struct NGAP_ProtocolIE_Container_11139P109 {
	A_SEQUENCE_OF(struct NGAP_DistributionSetupResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P109_t;
typedef struct NGAP_ProtocolIE_Container_11139P110 {
	A_SEQUENCE_OF(struct NGAP_DistributionSetupFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P110_t;
typedef struct NGAP_ProtocolIE_Container_11139P111 {
	A_SEQUENCE_OF(struct NGAP_DistributionReleaseRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P111_t;
typedef struct NGAP_ProtocolIE_Container_11139P112 {
	A_SEQUENCE_OF(struct NGAP_DistributionReleaseResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P112_t;
typedef struct NGAP_ProtocolIE_Container_11139P113 {
	A_SEQUENCE_OF(struct NGAP_MulticastSessionActivationRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P113_t;
typedef struct NGAP_ProtocolIE_Container_11139P114 {
	A_SEQUENCE_OF(struct NGAP_MulticastSessionActivationResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P114_t;
typedef struct NGAP_ProtocolIE_Container_11139P115 {
	A_SEQUENCE_OF(struct NGAP_MulticastSessionActivationFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P115_t;
typedef struct NGAP_ProtocolIE_Container_11139P116 {
	A_SEQUENCE_OF(struct NGAP_MulticastSessionDeactivationRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P116_t;
typedef struct NGAP_ProtocolIE_Container_11139P117 {
	A_SEQUENCE_OF(struct NGAP_MulticastSessionDeactivationResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P117_t;
typedef struct NGAP_ProtocolIE_Container_11139P118 {
	A_SEQUENCE_OF(struct NGAP_MulticastSessionUpdateRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P118_t;
typedef struct NGAP_ProtocolIE_Container_11139P119 {
	A_SEQUENCE_OF(struct NGAP_MulticastSessionUpdateResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P119_t;
typedef struct NGAP_ProtocolIE_Container_11139P120 {
	A_SEQUENCE_OF(struct NGAP_MulticastSessionUpdateFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P120_t;
typedef struct NGAP_ProtocolIE_Container_11139P121 {
	A_SEQUENCE_OF(struct NGAP_MulticastGroupPagingIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P121_t;
typedef struct NGAP_ProtocolIE_Container_11139P122 {
	A_SEQUENCE_OF(struct NGAP_TimingSynchronisationStatusRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P122_t;
typedef struct NGAP_ProtocolIE_Container_11139P123 {
	A_SEQUENCE_OF(struct NGAP_TimingSynchronisationStatusResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P123_t;
typedef struct NGAP_ProtocolIE_Container_11139P124 {
	A_SEQUENCE_OF(struct NGAP_TimingSynchronisationStatusFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P124_t;
typedef struct NGAP_ProtocolIE_Container_11139P125 {
	A_SEQUENCE_OF(struct NGAP_TimingSynchronisationStatusReportIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P125_t;
typedef struct NGAP_ProtocolIE_Container_11139P126 {
	A_SEQUENCE_OF(struct NGAP_MTCommunicationHandlingRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P126_t;
typedef struct NGAP_ProtocolIE_Container_11139P127 {
	A_SEQUENCE_OF(struct NGAP_MTCommunicationHandlingResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P127_t;
typedef struct NGAP_ProtocolIE_Container_11139P128 {
	A_SEQUENCE_OF(struct NGAP_MTCommunicationHandlingFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P128_t;
typedef struct NGAP_ProtocolIE_Container_11139P129 {
	A_SEQUENCE_OF(struct NGAP_RANPagingRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P129_t;
typedef struct NGAP_ProtocolIE_Container_11139P130 {
	A_SEQUENCE_OF(struct NGAP_MBSSessionSetupOrModRequestTransferIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P130_t;
typedef struct NGAP_ProtocolIE_Container_11139P131 {
	A_SEQUENCE_OF(struct NGAP_MulticastSessionUpdateRequestTransferIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P131_t;
typedef struct NGAP_ProtocolIE_Container_11139P132 {
	A_SEQUENCE_OF(struct NGAP_PDUSessionResourceModifyRequestTransferIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P132_t;
typedef struct NGAP_ProtocolIE_Container_11139P133 {
	A_SEQUENCE_OF(struct NGAP_PDUSessionResourceSetupRequestTransferIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_11139P133_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P0;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P0_specs_1;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P0_1[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P0_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P1;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P1_specs_3;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P1_3[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P1_constr_3;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P2;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P2_specs_5;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P2_5[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P2_constr_5;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P3;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P3_specs_7;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P3_7[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P3_constr_7;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P4;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P4_specs_9;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P4_9[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P4_constr_9;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P5;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P5_specs_11;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P5_11[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P5_constr_11;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P6;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P6_specs_13;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P6_13[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P6_constr_13;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P7;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P7_specs_15;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P7_15[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P7_constr_15;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P8;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P8_specs_17;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P8_17[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P8_constr_17;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P9;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P9_specs_19;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P9_19[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P9_constr_19;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P10;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P10_specs_21;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P10_21[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P10_constr_21;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P11;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P11_specs_23;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P11_23[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P11_constr_23;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P12;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P12_specs_25;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P12_25[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P12_constr_25;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P13;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P13_specs_27;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P13_27[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P13_constr_27;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P14;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P14_specs_29;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P14_29[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P14_constr_29;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P15;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P15_specs_31;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P15_31[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P15_constr_31;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P16;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P16_specs_33;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P16_33[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P16_constr_33;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P17;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P17_specs_35;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P17_35[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P17_constr_35;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P18;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P18_specs_37;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P18_37[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P18_constr_37;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P19;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P19_specs_39;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P19_39[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P19_constr_39;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P20;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P20_specs_41;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P20_41[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P20_constr_41;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P21;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P21_specs_43;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P21_43[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P21_constr_43;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P22;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P22_specs_45;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P22_45[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P22_constr_45;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P23;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P23_specs_47;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P23_47[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P23_constr_47;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P24;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P24_specs_49;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P24_49[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P24_constr_49;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P25;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P25_specs_51;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P25_51[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P25_constr_51;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P26;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P26_specs_53;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P26_53[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P26_constr_53;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P27;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P27_specs_55;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P27_55[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P27_constr_55;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P28;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P28_specs_57;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P28_57[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P28_constr_57;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P29;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P29_specs_59;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P29_59[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P29_constr_59;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P30;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P30_specs_61;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P30_61[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P30_constr_61;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P31;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P31_specs_63;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P31_63[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P31_constr_63;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P32;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P32_specs_65;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P32_65[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P32_constr_65;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P33;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P33_specs_67;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P33_67[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P33_constr_67;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P34;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P34_specs_69;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P34_69[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P34_constr_69;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P35;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P35_specs_71;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P35_71[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P35_constr_71;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P36;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P36_specs_73;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P36_73[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P36_constr_73;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P37;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P37_specs_75;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P37_75[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P37_constr_75;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P38;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P38_specs_77;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P38_77[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P38_constr_77;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P39;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P39_specs_79;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P39_79[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P39_constr_79;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P40;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P40_specs_81;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P40_81[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P40_constr_81;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P41;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P41_specs_83;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P41_83[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P41_constr_83;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P42;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P42_specs_85;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P42_85[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P42_constr_85;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P43;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P43_specs_87;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P43_87[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P43_constr_87;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P44;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P44_specs_89;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P44_89[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P44_constr_89;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P45;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P45_specs_91;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P45_91[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P45_constr_91;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P46;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P46_specs_93;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P46_93[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P46_constr_93;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P47;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P47_specs_95;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P47_95[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P47_constr_95;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P48;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P48_specs_97;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P48_97[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P48_constr_97;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P49;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P49_specs_99;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P49_99[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P49_constr_99;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P50;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P50_specs_101;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P50_101[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P50_constr_101;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P51;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P51_specs_103;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P51_103[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P51_constr_103;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P52;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P52_specs_105;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P52_105[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P52_constr_105;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P53;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P53_specs_107;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P53_107[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P53_constr_107;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P54;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P54_specs_109;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P54_109[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P54_constr_109;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P55;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P55_specs_111;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P55_111[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P55_constr_111;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P56;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P56_specs_113;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P56_113[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P56_constr_113;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P57;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P57_specs_115;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P57_115[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P57_constr_115;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P58;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P58_specs_117;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P58_117[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P58_constr_117;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P59;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P59_specs_119;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P59_119[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P59_constr_119;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P60;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P60_specs_121;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P60_121[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P60_constr_121;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P61;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P61_specs_123;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P61_123[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P61_constr_123;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P62;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P62_specs_125;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P62_125[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P62_constr_125;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P63;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P63_specs_127;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P63_127[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P63_constr_127;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P64;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P64_specs_129;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P64_129[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P64_constr_129;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P65;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P65_specs_131;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P65_131[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P65_constr_131;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P66;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P66_specs_133;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P66_133[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P66_constr_133;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P67;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P67_specs_135;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P67_135[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P67_constr_135;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P68;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P68_specs_137;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P68_137[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P68_constr_137;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P69;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P69_specs_139;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P69_139[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P69_constr_139;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P70;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P70_specs_141;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P70_141[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P70_constr_141;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P71;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P71_specs_143;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P71_143[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P71_constr_143;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P72;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P72_specs_145;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P72_145[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P72_constr_145;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P73;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P73_specs_147;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P73_147[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P73_constr_147;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P74;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P74_specs_149;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P74_149[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P74_constr_149;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P75;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P75_specs_151;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P75_151[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P75_constr_151;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P76;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P76_specs_153;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P76_153[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P76_constr_153;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P77;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P77_specs_155;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P77_155[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P77_constr_155;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P78;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P78_specs_157;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P78_157[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P78_constr_157;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P79;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P79_specs_159;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P79_159[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P79_constr_159;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P80;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P80_specs_161;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P80_161[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P80_constr_161;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P81;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P81_specs_163;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P81_163[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P81_constr_163;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P82;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P82_specs_165;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P82_165[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P82_constr_165;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P83;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P83_specs_167;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P83_167[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P83_constr_167;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P84;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P84_specs_169;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P84_169[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P84_constr_169;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P85;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P85_specs_171;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P85_171[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P85_constr_171;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P86;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P86_specs_173;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P86_173[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P86_constr_173;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P87;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P87_specs_175;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P87_175[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P87_constr_175;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P88;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P88_specs_177;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P88_177[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P88_constr_177;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P89;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P89_specs_179;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P89_179[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P89_constr_179;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P90;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P90_specs_181;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P90_181[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P90_constr_181;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P91;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P91_specs_183;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P91_183[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P91_constr_183;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P92;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P92_specs_185;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P92_185[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P92_constr_185;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P93;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P93_specs_187;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P93_187[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P93_constr_187;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P94;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P94_specs_189;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P94_189[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P94_constr_189;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P95;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P95_specs_191;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P95_191[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P95_constr_191;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P96;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P96_specs_193;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P96_193[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P96_constr_193;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P97;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P97_specs_195;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P97_195[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P97_constr_195;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P98;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P98_specs_197;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P98_197[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P98_constr_197;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P99;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P99_specs_199;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P99_199[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P99_constr_199;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P100;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P100_specs_201;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P100_201[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P100_constr_201;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P101;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P101_specs_203;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P101_203[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P101_constr_203;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P102;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P102_specs_205;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P102_205[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P102_constr_205;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P103;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P103_specs_207;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P103_207[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P103_constr_207;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P104;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P104_specs_209;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P104_209[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P104_constr_209;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P105;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P105_specs_211;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P105_211[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P105_constr_211;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P106;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P106_specs_213;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P106_213[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P106_constr_213;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P107;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P107_specs_215;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P107_215[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P107_constr_215;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P108;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P108_specs_217;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P108_217[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P108_constr_217;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P109;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P109_specs_219;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P109_219[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P109_constr_219;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P110;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P110_specs_221;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P110_221[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P110_constr_221;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P111;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P111_specs_223;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P111_223[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P111_constr_223;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P112;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P112_specs_225;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P112_225[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P112_constr_225;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P113;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P113_specs_227;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P113_227[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P113_constr_227;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P114;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P114_specs_229;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P114_229[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P114_constr_229;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P115;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P115_specs_231;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P115_231[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P115_constr_231;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P116;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P116_specs_233;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P116_233[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P116_constr_233;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P117;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P117_specs_235;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P117_235[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P117_constr_235;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P118;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P118_specs_237;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P118_237[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P118_constr_237;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P119;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P119_specs_239;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P119_239[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P119_constr_239;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P120;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P120_specs_241;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P120_241[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P120_constr_241;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P121;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P121_specs_243;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P121_243[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P121_constr_243;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P122;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P122_specs_245;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P122_245[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P122_constr_245;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P123;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P123_specs_247;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P123_247[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P123_constr_247;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P124;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P124_specs_249;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P124_249[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P124_constr_249;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P125;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P125_specs_251;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P125_251[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P125_constr_251;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P126;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P126_specs_253;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P126_253[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P126_constr_253;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P127;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P127_specs_255;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P127_255[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P127_constr_255;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P128;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P128_specs_257;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P128_257[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P128_constr_257;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P129;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P129_specs_259;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P129_259[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P129_constr_259;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P130;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P130_specs_261;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P130_261[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P130_constr_261;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P131;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P131_specs_263;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P131_263[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P131_constr_263;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P132;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P132_specs_265;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P132_265[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P132_constr_265;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_11139P133;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_11139P133_specs_267;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_11139P133_267[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_11139P133_constr_267;

#ifdef __cplusplus
}
#endif

#endif	/* _NGAP_ProtocolIE_Container_H_ */
#include <asn_internal.h>
