/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r18.1.0/38455-i10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPa_AngleMeasurementType_H_
#define	_NRPPa_AngleMeasurementType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPa_AngleMeasurementType_PR {
	NRPPa_AngleMeasurementType_PR_NOTHING,	/* No components present */
	NRPPa_AngleMeasurementType_PR_expected_ULAoA,
	NRPPa_AngleMeasurementType_PR_expected_ZoA,
	NRPPa_AngleMeasurementType_PR_choice_extension
} NRPPa_AngleMeasurementType_PR;

/* Forward declarations */
struct NRPPa_Expected_UL_AoA;
struct NRPPa_Expected_ZoA_only;
struct NRPPa_ProtocolIE_Single_Container;

/* NRPPa_AngleMeasurementType */
typedef struct NRPPa_AngleMeasurementType {
	NRPPa_AngleMeasurementType_PR present;
	union NRPPa_AngleMeasurementType_u {
		struct NRPPa_Expected_UL_AoA	*expected_ULAoA;
		struct NRPPa_Expected_ZoA_only	*expected_ZoA;
		struct NRPPa_ProtocolIE_Single_Container	*choice_extension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPa_AngleMeasurementType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NRPPa_AngleMeasurementType;
extern asn_CHOICE_specifics_t asn_SPC_NRPPa_AngleMeasurementType_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPa_AngleMeasurementType_1[3];
extern asn_per_constraints_t asn_PER_type_NRPPa_AngleMeasurementType_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPa_AngleMeasurementType_H_ */
#include <asn_internal.h>
