/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r18.1.0/38455-i10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPa_PRSResourceSet_Item_H_
#define	_NRPPa_PRSResourceSet_Item_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NRPPa_PRS-Resource-Set-ID.h"
#include <NativeEnumerated.h>
#include <NativeInteger.h>
#include "NRPPa_PRSResource-List.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPa_PRSResourceSet_Item__subcarrierSpacing {
	NRPPa_PRSResourceSet_Item__subcarrierSpacing_kHz15	= 0,
	NRPPa_PRSResourceSet_Item__subcarrierSpacing_kHz30	= 1,
	NRPPa_PRSResourceSet_Item__subcarrierSpacing_kHz60	= 2,
	NRPPa_PRSResourceSet_Item__subcarrierSpacing_kHz120	= 3
	/*
	 * Enumeration is extensible
	 */
} e_NRPPa_PRSResourceSet_Item__subcarrierSpacing;
typedef enum NRPPa_PRSResourceSet_Item__combSize {
	NRPPa_PRSResourceSet_Item__combSize_n2	= 0,
	NRPPa_PRSResourceSet_Item__combSize_n4	= 1,
	NRPPa_PRSResourceSet_Item__combSize_n6	= 2,
	NRPPa_PRSResourceSet_Item__combSize_n12	= 3
	/*
	 * Enumeration is extensible
	 */
} e_NRPPa_PRSResourceSet_Item__combSize;
typedef enum NRPPa_PRSResourceSet_Item__cPType {
	NRPPa_PRSResourceSet_Item__cPType_normal	= 0,
	NRPPa_PRSResourceSet_Item__cPType_extended	= 1
	/*
	 * Enumeration is extensible
	 */
} e_NRPPa_PRSResourceSet_Item__cPType;
typedef enum NRPPa_PRSResourceSet_Item__resourceSetPeriodicity {
	NRPPa_PRSResourceSet_Item__resourceSetPeriodicity_n4	= 0,
	NRPPa_PRSResourceSet_Item__resourceSetPeriodicity_n5	= 1,
	NRPPa_PRSResourceSet_Item__resourceSetPeriodicity_n8	= 2,
	NRPPa_PRSResourceSet_Item__resourceSetPeriodicity_n10	= 3,
	NRPPa_PRSResourceSet_Item__resourceSetPeriodicity_n16	= 4,
	NRPPa_PRSResourceSet_Item__resourceSetPeriodicity_n20	= 5,
	NRPPa_PRSResourceSet_Item__resourceSetPeriodicity_n32	= 6,
	NRPPa_PRSResourceSet_Item__resourceSetPeriodicity_n40	= 7,
	NRPPa_PRSResourceSet_Item__resourceSetPeriodicity_n64	= 8,
	NRPPa_PRSResourceSet_Item__resourceSetPeriodicity_n80	= 9,
	NRPPa_PRSResourceSet_Item__resourceSetPeriodicity_n160	= 10,
	NRPPa_PRSResourceSet_Item__resourceSetPeriodicity_n320	= 11,
	NRPPa_PRSResourceSet_Item__resourceSetPeriodicity_n640	= 12,
	NRPPa_PRSResourceSet_Item__resourceSetPeriodicity_n1280	= 13,
	NRPPa_PRSResourceSet_Item__resourceSetPeriodicity_n2560	= 14,
	NRPPa_PRSResourceSet_Item__resourceSetPeriodicity_n5120	= 15,
	NRPPa_PRSResourceSet_Item__resourceSetPeriodicity_n10240	= 16,
	NRPPa_PRSResourceSet_Item__resourceSetPeriodicity_n20480	= 17,
	NRPPa_PRSResourceSet_Item__resourceSetPeriodicity_n40960	= 18,
	NRPPa_PRSResourceSet_Item__resourceSetPeriodicity_n81920	= 19,
	/*
	 * Enumeration is extensible
	 */
	NRPPa_PRSResourceSet_Item__resourceSetPeriodicity_n128	= 20,
	NRPPa_PRSResourceSet_Item__resourceSetPeriodicity_n256	= 21,
	NRPPa_PRSResourceSet_Item__resourceSetPeriodicity_n512	= 22
} e_NRPPa_PRSResourceSet_Item__resourceSetPeriodicity;
typedef enum NRPPa_PRSResourceSet_Item__resourceRepetitionFactor {
	NRPPa_PRSResourceSet_Item__resourceRepetitionFactor_rf1	= 0,
	NRPPa_PRSResourceSet_Item__resourceRepetitionFactor_rf2	= 1,
	NRPPa_PRSResourceSet_Item__resourceRepetitionFactor_rf4	= 2,
	NRPPa_PRSResourceSet_Item__resourceRepetitionFactor_rf6	= 3,
	NRPPa_PRSResourceSet_Item__resourceRepetitionFactor_rf8	= 4,
	NRPPa_PRSResourceSet_Item__resourceRepetitionFactor_rf16	= 5,
	NRPPa_PRSResourceSet_Item__resourceRepetitionFactor_rf32	= 6
	/*
	 * Enumeration is extensible
	 */
} e_NRPPa_PRSResourceSet_Item__resourceRepetitionFactor;
typedef enum NRPPa_PRSResourceSet_Item__resourceTimeGap {
	NRPPa_PRSResourceSet_Item__resourceTimeGap_tg1	= 0,
	NRPPa_PRSResourceSet_Item__resourceTimeGap_tg2	= 1,
	NRPPa_PRSResourceSet_Item__resourceTimeGap_tg4	= 2,
	NRPPa_PRSResourceSet_Item__resourceTimeGap_tg8	= 3,
	NRPPa_PRSResourceSet_Item__resourceTimeGap_tg16	= 4,
	NRPPa_PRSResourceSet_Item__resourceTimeGap_tg32	= 5
	/*
	 * Enumeration is extensible
	 */
} e_NRPPa_PRSResourceSet_Item__resourceTimeGap;
typedef enum NRPPa_PRSResourceSet_Item__resourceNumberofSymbols {
	NRPPa_PRSResourceSet_Item__resourceNumberofSymbols_n2	= 0,
	NRPPa_PRSResourceSet_Item__resourceNumberofSymbols_n4	= 1,
	NRPPa_PRSResourceSet_Item__resourceNumberofSymbols_n6	= 2,
	NRPPa_PRSResourceSet_Item__resourceNumberofSymbols_n12	= 3,
	/*
	 * Enumeration is extensible
	 */
	NRPPa_PRSResourceSet_Item__resourceNumberofSymbols_n1	= 4
} e_NRPPa_PRSResourceSet_Item__resourceNumberofSymbols;

/* Forward declarations */
struct NRPPa_PRSMuting;
struct NRPPa_ProtocolExtensionContainer;

/* NRPPa_PRSResourceSet-Item */
typedef struct NRPPa_PRSResourceSet_Item {
	NRPPa_PRS_Resource_Set_ID_t	 pRSResourceSetID;
	long	 subcarrierSpacing;
	long	 pRSbandwidth;
	long	 startPRB;
	long	 pointA;
	long	 combSize;
	long	 cPType;
	long	 resourceSetPeriodicity;
	long	 resourceSetSlotOffset;
	long	 resourceRepetitionFactor;
	long	 resourceTimeGap;
	long	 resourceNumberofSymbols;
	struct NRPPa_PRSMuting	*pRSMuting;	/* OPTIONAL */
	long	 pRSResourceTransmitPower;
	NRPPa_PRSResource_List_t	 pRSResource_List;
	struct NRPPa_ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPa_PRSResourceSet_Item_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_NRPPa_subcarrierSpacing_3;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_NRPPa_combSize_12;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_NRPPa_cPType_18;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_NRPPa_resourceSetPeriodicity_22;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_NRPPa_resourceRepetitionFactor_48;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_NRPPa_resourceTimeGap_57;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_NRPPa_resourceNumberofSymbols_65;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_NRPPa_PRSResourceSet_Item;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPa_PRSResourceSet_Item_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPa_PRSResourceSet_Item_1[16];

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPa_PRSResourceSet_Item_H_ */
#include <asn_internal.h>
