/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r18.1.0/38455-i10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPa_PosSIB_Type_H_
#define	_NRPPa_PosSIB_Type_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPa_PosSIB_Type {
	NRPPa_PosSIB_Type_posSibType1_1	= 0,
	NRPPa_PosSIB_Type_posSibType1_2	= 1,
	NRPPa_PosSIB_Type_posSibType1_3	= 2,
	NRPPa_PosSIB_Type_posSibType1_4	= 3,
	NRPPa_PosSIB_Type_posSibType1_5	= 4,
	NRPPa_PosSIB_Type_posSibType1_6	= 5,
	NRPPa_PosSIB_Type_posSibType1_7	= 6,
	NRPPa_PosSIB_Type_posSibType1_8	= 7,
	NRPPa_PosSIB_Type_posSibType2_1	= 8,
	NRPPa_PosSIB_Type_posSibType2_2	= 9,
	NRPPa_PosSIB_Type_posSibType2_3	= 10,
	NRPPa_PosSIB_Type_posSibType2_4	= 11,
	NRPPa_PosSIB_Type_posSibType2_5	= 12,
	NRPPa_PosSIB_Type_posSibType2_6	= 13,
	NRPPa_PosSIB_Type_posSibType2_7	= 14,
	NRPPa_PosSIB_Type_posSibType2_8	= 15,
	NRPPa_PosSIB_Type_posSibType2_9	= 16,
	NRPPa_PosSIB_Type_posSibType2_10	= 17,
	NRPPa_PosSIB_Type_posSibType2_11	= 18,
	NRPPa_PosSIB_Type_posSibType2_12	= 19,
	NRPPa_PosSIB_Type_posSibType2_13	= 20,
	NRPPa_PosSIB_Type_posSibType2_14	= 21,
	NRPPa_PosSIB_Type_posSibType2_15	= 22,
	NRPPa_PosSIB_Type_posSibType2_16	= 23,
	NRPPa_PosSIB_Type_posSibType2_17	= 24,
	NRPPa_PosSIB_Type_posSibType2_18	= 25,
	NRPPa_PosSIB_Type_posSibType2_19	= 26,
	NRPPa_PosSIB_Type_posSibType2_20	= 27,
	NRPPa_PosSIB_Type_posSibType2_21	= 28,
	NRPPa_PosSIB_Type_posSibType2_22	= 29,
	NRPPa_PosSIB_Type_posSibType2_23	= 30,
	NRPPa_PosSIB_Type_posSibType2_24	= 31,
	NRPPa_PosSIB_Type_posSibType2_25	= 32,
	NRPPa_PosSIB_Type_posSibType3_1	= 33,
	NRPPa_PosSIB_Type_posSibType4_1	= 34,
	NRPPa_PosSIB_Type_posSibType5_1	= 35,
	NRPPa_PosSIB_Type_posSibType6_1	= 36,
	NRPPa_PosSIB_Type_posSibType6_2	= 37,
	NRPPa_PosSIB_Type_posSibType6_3	= 38,
	/*
	 * Enumeration is extensible
	 */
	NRPPa_PosSIB_Type_posSibType1_9	= 39,
	NRPPa_PosSIB_Type_posSibType1_10	= 40,
	NRPPa_PosSIB_Type_posSibType6_4	= 41,
	NRPPa_PosSIB_Type_posSibType6_5	= 42,
	NRPPa_PosSIB_Type_posSibType6_6	= 43
} e_NRPPa_PosSIB_Type;

/* NRPPa_PosSIB-Type */
typedef long	 NRPPa_PosSIB_Type_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_NRPPa_PosSIB_Type_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_NRPPa_PosSIB_Type;
extern const asn_INTEGER_specifics_t asn_SPC_NRPPa_PosSIB_Type_specs_1;
asn_struct_free_f NRPPa_PosSIB_Type_free;
asn_struct_print_f NRPPa_PosSIB_Type_print;
asn_constr_check_f NRPPa_PosSIB_Type_constraint;
per_type_decoder_f NRPPa_PosSIB_Type_decode_aper;
per_type_encoder_f NRPPa_PosSIB_Type_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPa_PosSIB_Type_H_ */
#include <asn_internal.h>
