/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-Containers"
 * 	found in "../support/nrppa-r18.1.0/38455-i10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPa_PrivateIE_Field_H_
#define	_NRPPa_PrivateIE_Field_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NRPPa_PrivateIE-ID.h"
#include "NRPPa_Criticality.h"
#include <ANY.h>
#include <asn_ioc.h>
#include <OPEN_TYPE.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPa_PrivateMessage_IEs__value_PR {
	NRPPa_PrivateMessage_IEs__value_PR_NOTHING	/* No components present */
	
} NRPPa_PrivateMessage_IEs__value_PR;

/* NRPPa_PrivateIE-Field */
typedef struct NRPPa_PrivateMessage_IEs {
	NRPPa_PrivateIE_ID_t	 id;
	NRPPa_Criticality_t	 criticality;
	struct NRPPa_PrivateMessage_IEs__value {
		NRPPa_PrivateMessage_IEs__value_PR present;
		union NRPPa_PrivateMessage_IEs__NRPPa_value_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPa_PrivateMessage_IEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NRPPa_PrivateMessage_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPa_PrivateMessage_IEs_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPa_PrivateMessage_IEs_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPa_PrivateIE_Field_H_ */
#include <asn_internal.h>
