/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-CommonDataTypes"
 * 	found in "../support/nrppa-r18.1.0/38455-i10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPa_ProcedureCode_H_
#define	_NRPPa_ProcedureCode_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* NRPPa_ProcedureCode */
typedef long	 NRPPa_ProcedureCode_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_NRPPa_ProcedureCode_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_NRPPa_ProcedureCode;
asn_struct_free_f NRPPa_ProcedureCode_free;
asn_struct_print_f NRPPa_ProcedureCode_print;
asn_constr_check_f NRPPa_ProcedureCode_constraint;
per_type_decoder_f NRPPa_ProcedureCode_decode_aper;
per_type_encoder_f NRPPa_ProcedureCode_encode_aper;
#define NRPPa_ProcedureCode_id_errorIndication	((NRPPa_ProcedureCode_t)0)
#define NRPPa_ProcedureCode_id_privateMessage	((NRPPa_ProcedureCode_t)1)
#define NRPPa_ProcedureCode_id_e_CIDMeasurementInitiation	((NRPPa_ProcedureCode_t)2)
#define NRPPa_ProcedureCode_id_e_CIDMeasurementFailureIndication	((NRPPa_ProcedureCode_t)3)
#define NRPPa_ProcedureCode_id_e_CIDMeasurementReport	((NRPPa_ProcedureCode_t)4)
#define NRPPa_ProcedureCode_id_e_CIDMeasurementTermination	((NRPPa_ProcedureCode_t)5)
#define NRPPa_ProcedureCode_id_oTDOAInformationExchange	((NRPPa_ProcedureCode_t)6)
#define NRPPa_ProcedureCode_id_assistanceInformationControl	((NRPPa_ProcedureCode_t)7)
#define NRPPa_ProcedureCode_id_assistanceInformationFeedback	((NRPPa_ProcedureCode_t)8)
#define NRPPa_ProcedureCode_id_positioningInformationExchange	((NRPPa_ProcedureCode_t)9)
#define NRPPa_ProcedureCode_id_positioningInformationUpdate	((NRPPa_ProcedureCode_t)10)
#define NRPPa_ProcedureCode_id_Measurement	((NRPPa_ProcedureCode_t)11)
#define NRPPa_ProcedureCode_id_MeasurementReport	((NRPPa_ProcedureCode_t)12)
#define NRPPa_ProcedureCode_id_MeasurementUpdate	((NRPPa_ProcedureCode_t)13)
#define NRPPa_ProcedureCode_id_MeasurementAbort	((NRPPa_ProcedureCode_t)14)
#define NRPPa_ProcedureCode_id_MeasurementFailureIndication	((NRPPa_ProcedureCode_t)15)
#define NRPPa_ProcedureCode_id_tRPInformationExchange	((NRPPa_ProcedureCode_t)16)
#define NRPPa_ProcedureCode_id_positioningActivation	((NRPPa_ProcedureCode_t)17)
#define NRPPa_ProcedureCode_id_positioningDeactivation	((NRPPa_ProcedureCode_t)18)
#define NRPPa_ProcedureCode_id_pRSConfigurationExchange	((NRPPa_ProcedureCode_t)19)
#define NRPPa_ProcedureCode_id_measurementPreconfiguration	((NRPPa_ProcedureCode_t)20)
#define NRPPa_ProcedureCode_id_measurementActivation	((NRPPa_ProcedureCode_t)21)
#define NRPPa_ProcedureCode_id_sRSInformationReservationNotification	((NRPPa_ProcedureCode_t)22)

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPa_ProcedureCode_H_ */
#include <asn_internal.h>
