/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-CommonDataTypes"
 * 	found in "../support/nrppa-r18.1.0/38455-i10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPa_ProtocolIE_ID_H_
#define	_NRPPa_ProtocolIE_ID_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* NRPPa_ProtocolIE-ID */
typedef long	 NRPPa_ProtocolIE_ID_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_NRPPa_ProtocolIE_ID_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_NRPPa_ProtocolIE_ID;
asn_struct_free_f NRPPa_ProtocolIE_ID_free;
asn_struct_print_f NRPPa_ProtocolIE_ID_print;
asn_constr_check_f NRPPa_ProtocolIE_ID_constraint;
per_type_decoder_f NRPPa_ProtocolIE_ID_decode_aper;
per_type_encoder_f NRPPa_ProtocolIE_ID_encode_aper;
#define NRPPa_ProtocolIE_ID_id_Cause	((NRPPa_ProtocolIE_ID_t)0)
#define NRPPa_ProtocolIE_ID_id_CriticalityDiagnostics	((NRPPa_ProtocolIE_ID_t)1)
#define NRPPa_ProtocolIE_ID_id_LMF_UE_Measurement_ID	((NRPPa_ProtocolIE_ID_t)2)
#define NRPPa_ProtocolIE_ID_id_ReportCharacteristics	((NRPPa_ProtocolIE_ID_t)3)
#define NRPPa_ProtocolIE_ID_id_MeasurementPeriodicity	((NRPPa_ProtocolIE_ID_t)4)
#define NRPPa_ProtocolIE_ID_id_MeasurementQuantities	((NRPPa_ProtocolIE_ID_t)5)
#define NRPPa_ProtocolIE_ID_id_RAN_UE_Measurement_ID	((NRPPa_ProtocolIE_ID_t)6)
#define NRPPa_ProtocolIE_ID_id_E_CID_MeasurementResult	((NRPPa_ProtocolIE_ID_t)7)
#define NRPPa_ProtocolIE_ID_id_OTDOACells	((NRPPa_ProtocolIE_ID_t)8)
#define NRPPa_ProtocolIE_ID_id_OTDOA_Information_Type_Group	((NRPPa_ProtocolIE_ID_t)9)
#define NRPPa_ProtocolIE_ID_id_OTDOA_Information_Type_Item	((NRPPa_ProtocolIE_ID_t)10)
#define NRPPa_ProtocolIE_ID_id_MeasurementQuantities_Item	((NRPPa_ProtocolIE_ID_t)11)
#define NRPPa_ProtocolIE_ID_id_RequestedSRSTransmissionCharacteristics	((NRPPa_ProtocolIE_ID_t)12)
#define NRPPa_ProtocolIE_ID_id_Cell_Portion_ID	((NRPPa_ProtocolIE_ID_t)14)
#define NRPPa_ProtocolIE_ID_id_OtherRATMeasurementQuantities	((NRPPa_ProtocolIE_ID_t)15)
#define NRPPa_ProtocolIE_ID_id_OtherRATMeasurementQuantities_Item	((NRPPa_ProtocolIE_ID_t)16)
#define NRPPa_ProtocolIE_ID_id_OtherRATMeasurementResult	((NRPPa_ProtocolIE_ID_t)17)
#define NRPPa_ProtocolIE_ID_id_WLANMeasurementQuantities	((NRPPa_ProtocolIE_ID_t)19)
#define NRPPa_ProtocolIE_ID_id_WLANMeasurementQuantities_Item	((NRPPa_ProtocolIE_ID_t)20)
#define NRPPa_ProtocolIE_ID_id_WLANMeasurementResult	((NRPPa_ProtocolIE_ID_t)21)
#define NRPPa_ProtocolIE_ID_id_TDD_Config_EUTRA_Item	((NRPPa_ProtocolIE_ID_t)22)
#define NRPPa_ProtocolIE_ID_id_Assistance_Information	((NRPPa_ProtocolIE_ID_t)23)
#define NRPPa_ProtocolIE_ID_id_Broadcast	((NRPPa_ProtocolIE_ID_t)24)
#define NRPPa_ProtocolIE_ID_id_AssistanceInformationFailureList	((NRPPa_ProtocolIE_ID_t)25)
#define NRPPa_ProtocolIE_ID_id_SRSConfiguration	((NRPPa_ProtocolIE_ID_t)26)
#define NRPPa_ProtocolIE_ID_id_MeasurementResult	((NRPPa_ProtocolIE_ID_t)27)
#define NRPPa_ProtocolIE_ID_id_TRP_ID	((NRPPa_ProtocolIE_ID_t)28)
#define NRPPa_ProtocolIE_ID_id_TRPInformationTypeListTRPReq	((NRPPa_ProtocolIE_ID_t)29)
#define NRPPa_ProtocolIE_ID_id_TRPInformationListTRPResp	((NRPPa_ProtocolIE_ID_t)30)
#define NRPPa_ProtocolIE_ID_id_MeasurementBeamInfoRequest	((NRPPa_ProtocolIE_ID_t)31)
#define NRPPa_ProtocolIE_ID_id_ResultSS_RSRP	((NRPPa_ProtocolIE_ID_t)32)
#define NRPPa_ProtocolIE_ID_id_ResultSS_RSRQ	((NRPPa_ProtocolIE_ID_t)33)
#define NRPPa_ProtocolIE_ID_id_ResultCSI_RSRP	((NRPPa_ProtocolIE_ID_t)34)
#define NRPPa_ProtocolIE_ID_id_ResultCSI_RSRQ	((NRPPa_ProtocolIE_ID_t)35)
#define NRPPa_ProtocolIE_ID_id_AngleOfArrivalNR	((NRPPa_ProtocolIE_ID_t)36)
#define NRPPa_ProtocolIE_ID_id_GeographicalCoordinates	((NRPPa_ProtocolIE_ID_t)37)
#define NRPPa_ProtocolIE_ID_id_PositioningBroadcastCells	((NRPPa_ProtocolIE_ID_t)38)
#define NRPPa_ProtocolIE_ID_id_LMF_Measurement_ID	((NRPPa_ProtocolIE_ID_t)39)
#define NRPPa_ProtocolIE_ID_id_RAN_Measurement_ID	((NRPPa_ProtocolIE_ID_t)40)
#define NRPPa_ProtocolIE_ID_id_TRP_MeasurementRequestList	((NRPPa_ProtocolIE_ID_t)41)
#define NRPPa_ProtocolIE_ID_id_TRP_MeasurementResponseList	((NRPPa_ProtocolIE_ID_t)42)
#define NRPPa_ProtocolIE_ID_id_TRP_MeasurementReportList	((NRPPa_ProtocolIE_ID_t)43)
#define NRPPa_ProtocolIE_ID_id_SRSType	((NRPPa_ProtocolIE_ID_t)44)
#define NRPPa_ProtocolIE_ID_id_ActivationTime	((NRPPa_ProtocolIE_ID_t)45)
#define NRPPa_ProtocolIE_ID_id_SRSResourceSetID	((NRPPa_ProtocolIE_ID_t)46)
#define NRPPa_ProtocolIE_ID_id_TRPList	((NRPPa_ProtocolIE_ID_t)47)
#define NRPPa_ProtocolIE_ID_id_SRSSpatialRelation	((NRPPa_ProtocolIE_ID_t)48)
#define NRPPa_ProtocolIE_ID_id_SystemFrameNumber	((NRPPa_ProtocolIE_ID_t)49)
#define NRPPa_ProtocolIE_ID_id_SlotNumber	((NRPPa_ProtocolIE_ID_t)50)
#define NRPPa_ProtocolIE_ID_id_SRSResourceTrigger	((NRPPa_ProtocolIE_ID_t)51)
#define NRPPa_ProtocolIE_ID_id_TRPMeasurementQuantities	((NRPPa_ProtocolIE_ID_t)52)
#define NRPPa_ProtocolIE_ID_id_AbortTransmission	((NRPPa_ProtocolIE_ID_t)53)
#define NRPPa_ProtocolIE_ID_id_SFNInitialisationTime	((NRPPa_ProtocolIE_ID_t)54)
#define NRPPa_ProtocolIE_ID_id_ResultNR	((NRPPa_ProtocolIE_ID_t)55)
#define NRPPa_ProtocolIE_ID_id_ResultEUTRA	((NRPPa_ProtocolIE_ID_t)56)
#define NRPPa_ProtocolIE_ID_id_TRPInformationTypeItem	((NRPPa_ProtocolIE_ID_t)57)
#define NRPPa_ProtocolIE_ID_id_CGI_NR	((NRPPa_ProtocolIE_ID_t)58)
#define NRPPa_ProtocolIE_ID_id_SFNInitialisationTime_NR	((NRPPa_ProtocolIE_ID_t)59)
#define NRPPa_ProtocolIE_ID_id_Cell_ID	((NRPPa_ProtocolIE_ID_t)60)
#define NRPPa_ProtocolIE_ID_id_SrsFrequency	((NRPPa_ProtocolIE_ID_t)61)
#define NRPPa_ProtocolIE_ID_id_TRPType	((NRPPa_ProtocolIE_ID_t)62)
#define NRPPa_ProtocolIE_ID_id_SRSSpatialRelationPerSRSResource	((NRPPa_ProtocolIE_ID_t)63)
#define NRPPa_ProtocolIE_ID_id_MeasurementPeriodicityExtended	((NRPPa_ProtocolIE_ID_t)64)
#define NRPPa_ProtocolIE_ID_id_PRS_Resource_ID	((NRPPa_ProtocolIE_ID_t)65)
#define NRPPa_ProtocolIE_ID_id_PRSTRPList	((NRPPa_ProtocolIE_ID_t)66)
#define NRPPa_ProtocolIE_ID_id_PRSTransmissionTRPList	((NRPPa_ProtocolIE_ID_t)67)
#define NRPPa_ProtocolIE_ID_id_OnDemandPRS	((NRPPa_ProtocolIE_ID_t)68)
#define NRPPa_ProtocolIE_ID_id_AoA_SearchWindow	((NRPPa_ProtocolIE_ID_t)69)
#define NRPPa_ProtocolIE_ID_id_TRP_MeasurementUpdateList	((NRPPa_ProtocolIE_ID_t)70)
#define NRPPa_ProtocolIE_ID_id_ZoA	((NRPPa_ProtocolIE_ID_t)71)
#define NRPPa_ProtocolIE_ID_id_ResponseTime	((NRPPa_ProtocolIE_ID_t)72)
#define NRPPa_ProtocolIE_ID_id_UEReportingInformation	((NRPPa_ProtocolIE_ID_t)73)
#define NRPPa_ProtocolIE_ID_id_MultipleULAoA	((NRPPa_ProtocolIE_ID_t)74)
#define NRPPa_ProtocolIE_ID_id_UL_SRS_RSRPP	((NRPPa_ProtocolIE_ID_t)75)
#define NRPPa_ProtocolIE_ID_id_SRSResourcetype	((NRPPa_ProtocolIE_ID_t)76)
#define NRPPa_ProtocolIE_ID_id_ExtendedAdditionalPathList	((NRPPa_ProtocolIE_ID_t)77)
#define NRPPa_ProtocolIE_ID_id_ARPLocationInfo	((NRPPa_ProtocolIE_ID_t)78)
#define NRPPa_ProtocolIE_ID_id_ARP_ID	((NRPPa_ProtocolIE_ID_t)79)
#define NRPPa_ProtocolIE_ID_id_LoS_NLoSInformation	((NRPPa_ProtocolIE_ID_t)80)
#define NRPPa_ProtocolIE_ID_id_UETxTEGAssociationList	((NRPPa_ProtocolIE_ID_t)81)
#define NRPPa_ProtocolIE_ID_id_NumberOfTRPRxTEG	((NRPPa_ProtocolIE_ID_t)82)
#define NRPPa_ProtocolIE_ID_id_NumberOfTRPRxTxTEG	((NRPPa_ProtocolIE_ID_t)83)
#define NRPPa_ProtocolIE_ID_id_TRPTxTEGAssociation	((NRPPa_ProtocolIE_ID_t)84)
#define NRPPa_ProtocolIE_ID_id_TRPTEGInformation	((NRPPa_ProtocolIE_ID_t)85)
#define NRPPa_ProtocolIE_ID_id_TRP_Rx_TEGInformation	((NRPPa_ProtocolIE_ID_t)86)
#define NRPPa_ProtocolIE_ID_id_TRP_PRS_Information_List	((NRPPa_ProtocolIE_ID_t)87)
#define NRPPa_ProtocolIE_ID_id_PRS_Measurements_Info_List	((NRPPa_ProtocolIE_ID_t)88)
#define NRPPa_ProtocolIE_ID_id_PRSConfigRequestType	((NRPPa_ProtocolIE_ID_t)89)
#define NRPPa_ProtocolIE_ID_id_UE_TEG_Info_Request	((NRPPa_ProtocolIE_ID_t)90)
#define NRPPa_ProtocolIE_ID_id_MeasurementTimeOccasion	((NRPPa_ProtocolIE_ID_t)91)
#define NRPPa_ProtocolIE_ID_id_MeasurementCharacteristicsRequestIndicator	((NRPPa_ProtocolIE_ID_t)92)
#define NRPPa_ProtocolIE_ID_id_TRPBeamAntennaInformation	((NRPPa_ProtocolIE_ID_t)93)
#define NRPPa_ProtocolIE_ID_id_NR_TADV	((NRPPa_ProtocolIE_ID_t)94)
#define NRPPa_ProtocolIE_ID_id_MeasurementAmount	((NRPPa_ProtocolIE_ID_t)95)
#define NRPPa_ProtocolIE_ID_id_pathPower	((NRPPa_ProtocolIE_ID_t)96)
#define NRPPa_ProtocolIE_ID_id_PreconfigurationResult	((NRPPa_ProtocolIE_ID_t)97)
#define NRPPa_ProtocolIE_ID_id_RequestType	((NRPPa_ProtocolIE_ID_t)98)
#define NRPPa_ProtocolIE_ID_id_UE_TEG_ReportingPeriodicity	((NRPPa_ProtocolIE_ID_t)99)
#define NRPPa_ProtocolIE_ID_id_SRSPortIndex	((NRPPa_ProtocolIE_ID_t)100)
#define NRPPa_ProtocolIE_ID_id_procedure_code_101_not_to_be_used	((NRPPa_ProtocolIE_ID_t)101)
#define NRPPa_ProtocolIE_ID_id_procedure_code_102_not_to_be_used	((NRPPa_ProtocolIE_ID_t)102)
#define NRPPa_ProtocolIE_ID_id_procedure_code_103_not_to_be_used	((NRPPa_ProtocolIE_ID_t)103)
#define NRPPa_ProtocolIE_ID_id_UETxTimingErrorMargin	((NRPPa_ProtocolIE_ID_t)104)
#define NRPPa_ProtocolIE_ID_id_MeasurementPeriodicityNR_AoA	((NRPPa_ProtocolIE_ID_t)105)
#define NRPPa_ProtocolIE_ID_id_SRSTransmissionStatus	((NRPPa_ProtocolIE_ID_t)106)
#define NRPPa_ProtocolIE_ID_id_nrofSymbolsExtended	((NRPPa_ProtocolIE_ID_t)107)
#define NRPPa_ProtocolIE_ID_id_repetitionFactorExtended	((NRPPa_ProtocolIE_ID_t)108)
#define NRPPa_ProtocolIE_ID_id_StartRBHopping	((NRPPa_ProtocolIE_ID_t)109)
#define NRPPa_ProtocolIE_ID_id_StartRBIndex	((NRPPa_ProtocolIE_ID_t)110)
#define NRPPa_ProtocolIE_ID_id_transmissionCombn8	((NRPPa_ProtocolIE_ID_t)111)
#define NRPPa_ProtocolIE_ID_id_ExtendedResourceSymbolOffset	((NRPPa_ProtocolIE_ID_t)112)
#define NRPPa_ProtocolIE_ID_id_NewNRCGI	((NRPPa_ProtocolIE_ID_t)113)
#define NRPPa_ProtocolIE_ID_id_Mobile_TRP_LocationInformation	((NRPPa_ProtocolIE_ID_t)114)
#define NRPPa_ProtocolIE_ID_id_Mobile_IAB_MT_UE_ID	((NRPPa_ProtocolIE_ID_t)115)
#define NRPPa_ProtocolIE_ID_id_MobileAccessPointLocation	((NRPPa_ProtocolIE_ID_t)116)
#define NRPPa_ProtocolIE_ID_id_CommonTAParameters	((NRPPa_ProtocolIE_ID_t)117)
#define NRPPa_ProtocolIE_ID_id_UE_Rx_Tx_Time_Diff	((NRPPa_ProtocolIE_ID_t)118)
#define NRPPa_ProtocolIE_ID_id_SCS_480	((NRPPa_ProtocolIE_ID_t)119)
#define NRPPa_ProtocolIE_ID_id_SCS_960	((NRPPa_ProtocolIE_ID_t)120)
#define NRPPa_ProtocolIE_ID_id_Bandwidth_Aggregation_Request_Indication	((NRPPa_ProtocolIE_ID_t)121)
#define NRPPa_ProtocolIE_ID_id_PosSRSResourceSet_Aggregation_List	((NRPPa_ProtocolIE_ID_t)122)
#define NRPPa_ProtocolIE_ID_id_TimingReportingGranularityFactorExtended	((NRPPa_ProtocolIE_ID_t)123)
#define NRPPa_ProtocolIE_ID_id_TimeWindowInformation_SRS_List	((NRPPa_ProtocolIE_ID_t)124)
#define NRPPa_ProtocolIE_ID_id_TimeWindowInformation_Measurement_List	((NRPPa_ProtocolIE_ID_t)125)
#define NRPPa_ProtocolIE_ID_id_UL_RSCPMeas	((NRPPa_ProtocolIE_ID_t)126)
#define NRPPa_ProtocolIE_ID_id_SymbolIndex	((NRPPa_ProtocolIE_ID_t)127)
#define NRPPa_ProtocolIE_ID_id_PosValidityAreaCellList	((NRPPa_ProtocolIE_ID_t)128)
#define NRPPa_ProtocolIE_ID_id_SRSReservationType	((NRPPa_ProtocolIE_ID_t)129)
#define NRPPa_ProtocolIE_ID_id_PRSBWAggregationRequestIndication	((NRPPa_ProtocolIE_ID_t)130)
#define NRPPa_ProtocolIE_ID_id_AggregatedPosSRSResourceID_List	((NRPPa_ProtocolIE_ID_t)131)
#define NRPPa_ProtocolIE_ID_id_AggregatedPRSResourceSetList	((NRPPa_ProtocolIE_ID_t)132)
#define NRPPa_ProtocolIE_ID_id_TRPPhaseQuality	((NRPPa_ProtocolIE_ID_t)133)
#define NRPPa_ProtocolIE_ID_id_NewCellIdentity	((NRPPa_ProtocolIE_ID_t)134)
#define NRPPa_ProtocolIE_ID_id_ValidityAreaSpecificSRSInformation	((NRPPa_ProtocolIE_ID_t)135)
#define NRPPa_ProtocolIE_ID_id_RequestedSRSPreconfigurationCharacteristics_List	((NRPPa_ProtocolIE_ID_t)136)
#define NRPPa_ProtocolIE_ID_id_SRSPreconfiguration_List	((NRPPa_ProtocolIE_ID_t)137)
#define NRPPa_ProtocolIE_ID_id_SRSInformation	((NRPPa_ProtocolIE_ID_t)138)
#define NRPPa_ProtocolIE_ID_id_TxHoppingConfiguration	((NRPPa_ProtocolIE_ID_t)139)
#define NRPPa_ProtocolIE_ID_id_MeasuredFrequencyHops	((NRPPa_ProtocolIE_ID_t)140)
#define NRPPa_ProtocolIE_ID_id_ReportingGranularitykminus1	((NRPPa_ProtocolIE_ID_t)141)
#define NRPPa_ProtocolIE_ID_id_ReportingGranularitykminus2	((NRPPa_ProtocolIE_ID_t)142)
#define NRPPa_ProtocolIE_ID_id_ReportingGranularitykminus3	((NRPPa_ProtocolIE_ID_t)143)
#define NRPPa_ProtocolIE_ID_id_ReportingGranularitykminus4	((NRPPa_ProtocolIE_ID_t)144)
#define NRPPa_ProtocolIE_ID_id_ReportingGranularitykminus5	((NRPPa_ProtocolIE_ID_t)145)
#define NRPPa_ProtocolIE_ID_id_ReportingGranularitykminus6	((NRPPa_ProtocolIE_ID_t)146)
#define NRPPa_ProtocolIE_ID_id_ReportingGranularitykminus1AdditionalPath	((NRPPa_ProtocolIE_ID_t)147)
#define NRPPa_ProtocolIE_ID_id_ReportingGranularitykminus2AdditionalPath	((NRPPa_ProtocolIE_ID_t)148)
#define NRPPa_ProtocolIE_ID_id_ReportingGranularitykminus3AdditionalPath	((NRPPa_ProtocolIE_ID_t)149)
#define NRPPa_ProtocolIE_ID_id_ReportingGranularitykminus4AdditionalPath	((NRPPa_ProtocolIE_ID_t)150)
#define NRPPa_ProtocolIE_ID_id_ReportingGranularitykminus5AdditionalPath	((NRPPa_ProtocolIE_ID_t)151)
#define NRPPa_ProtocolIE_ID_id_ReportingGranularitykminus6AdditionalPath	((NRPPa_ProtocolIE_ID_t)152)

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPa_ProtocolIE_ID_H_ */
#include <asn_internal.h>
