/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r18.1.0/38455-i10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#include "NRPPa_SpatialRelationPerSRSResource.h"

#include "NRPPa_ProtocolExtensionContainer.h"
asn_TYPE_member_t asn_MBR_NRPPa_SpatialRelationPerSRSResource_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct NRPPa_SpatialRelationPerSRSResource, spatialRelationPerSRSResource_List),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NRPPa_SpatialRelationPerSRSResource_List,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"spatialRelationPerSRSResource-List"
		},
	{ ATF_POINTER, 1, offsetof(struct NRPPa_SpatialRelationPerSRSResource, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NRPPa_ProtocolExtensionContainer_4443P115,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"iE-Extensions"
		},
};
static const int asn_MAP_NRPPa_SpatialRelationPerSRSResource_oms_1[] = { 1 };
static const ber_tlv_tag_t asn_DEF_NRPPa_SpatialRelationPerSRSResource_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_NRPPa_SpatialRelationPerSRSResource_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* spatialRelationPerSRSResource-List */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* iE-Extensions */
};
asn_SEQUENCE_specifics_t asn_SPC_NRPPa_SpatialRelationPerSRSResource_specs_1 = {
	sizeof(struct NRPPa_SpatialRelationPerSRSResource),
	offsetof(struct NRPPa_SpatialRelationPerSRSResource, _asn_ctx),
	asn_MAP_NRPPa_SpatialRelationPerSRSResource_tag2el_1,
	2,	/* Count of tags in the map */
	asn_MAP_NRPPa_SpatialRelationPerSRSResource_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	2,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_NRPPa_SpatialRelationPerSRSResource = {
	"SpatialRelationPerSRSResource",
	"SpatialRelationPerSRSResource",
	&asn_OP_SEQUENCE,
	asn_DEF_NRPPa_SpatialRelationPerSRSResource_tags_1,
	sizeof(asn_DEF_NRPPa_SpatialRelationPerSRSResource_tags_1)
		/sizeof(asn_DEF_NRPPa_SpatialRelationPerSRSResource_tags_1[0]), /* 1 */
	asn_DEF_NRPPa_SpatialRelationPerSRSResource_tags_1,	/* Same as above */
	sizeof(asn_DEF_NRPPa_SpatialRelationPerSRSResource_tags_1)
		/sizeof(asn_DEF_NRPPa_SpatialRelationPerSRSResource_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_NRPPa_SpatialRelationPerSRSResource_1,
	2,	/* Elements count */
	&asn_SPC_NRPPa_SpatialRelationPerSRSResource_specs_1	/* Additional specs */
};

