/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r18.1.0/38455-i10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPa_TxHoppingConfiguration_H_
#define	_NRPPa_TxHoppingConfiguration_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <NativeInteger.h>
#include "NRPPa_SlotOffsetForRemainingHopsList.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPa_TxHoppingConfiguration__overlapValue {
	NRPPa_TxHoppingConfiguration__overlapValue_rb0	= 0,
	NRPPa_TxHoppingConfiguration__overlapValue_rb1	= 1,
	NRPPa_TxHoppingConfiguration__overlapValue_rb2	= 2,
	NRPPa_TxHoppingConfiguration__overlapValue_rb4	= 3
} e_NRPPa_TxHoppingConfiguration__overlapValue;

/* Forward declarations */
struct NRPPa_ProtocolExtensionContainer;

/* NRPPa_TxHoppingConfiguration */
typedef struct NRPPa_TxHoppingConfiguration {
	long	 overlapValue;
	long	 numberOfHops;
	NRPPa_SlotOffsetForRemainingHopsList_t	 slotOffsetForRemainingHopsList;
	struct NRPPa_ProtocolExtensionContainer	*iE_extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPa_TxHoppingConfiguration_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_NRPPa_overlapValue_2;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_NRPPa_TxHoppingConfiguration;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPa_TxHoppingConfiguration_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPa_TxHoppingConfiguration_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPa_TxHoppingConfiguration_H_ */
#include <asn_internal.h>
