/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r18.1.0/38455-i10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPa_SRSResourceTypeChoice_H_
#define	_NRPPa_SRSResourceTypeChoice_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPa_SRSResourceTypeChoice_PR {
	NRPPa_SRSResourceTypeChoice_PR_NOTHING,	/* No components present */
	NRPPa_SRSResourceTypeChoice_PR_sRSResourceInfo,
	NRPPa_SRSResourceTypeChoice_PR_posSRSResourceInfo
	/* Extensions may appear below */
	
} NRPPa_SRSResourceTypeChoice_PR;

/* Forward declarations */
struct NRPPa_SRSInfo;
struct NRPPa_PosSRSInfo;

/* NRPPa_SRSResourceTypeChoice */
typedef struct NRPPa_SRSResourceTypeChoice {
	NRPPa_SRSResourceTypeChoice_PR present;
	union NRPPa_SRSResourceTypeChoice_u {
		struct NRPPa_SRSInfo	*sRSResourceInfo;
		struct NRPPa_PosSRSInfo	*posSRSResourceInfo;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPa_SRSResourceTypeChoice_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NRPPa_SRSResourceTypeChoice;
extern asn_CHOICE_specifics_t asn_SPC_NRPPa_SRSResourceTypeChoice_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPa_SRSResourceTypeChoice_1[2];
extern asn_per_constraints_t asn_PER_type_NRPPa_SRSResourceTypeChoice_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPa_SRSResourceTypeChoice_H_ */
#include <asn_internal.h>
