/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r18.1.0/38455-i10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPa_ResultGERAN_Item_H_
#define	_NRPPa_ResultGERAN_Item_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NRPPa_BCCH.h"
#include "NRPPa_PhysCellIDGERAN.h"
#include "NRPPa_RSSI.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct NRPPa_ProtocolExtensionContainer;

/* NRPPa_ResultGERAN-Item */
typedef struct NRPPa_ResultGERAN_Item {
	NRPPa_BCCH_t	 bCCH;
	NRPPa_PhysCellIDGERAN_t	 physCellIDGERAN;
	NRPPa_RSSI_t	 rSSI;
	struct NRPPa_ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPa_ResultGERAN_Item_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NRPPa_ResultGERAN_Item;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPa_ResultGERAN_Item_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPa_ResultGERAN_Item_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPa_ResultGERAN_Item_H_ */
#include <asn_internal.h>
