/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r18.1.0/38455-i10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPa_OTDOACell_Information_Item_H_
#define	_NRPPa_OTDOACell_Information_Item_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NRPPa_PCI-EUTRA.h"
#include "NRPPa_TAC.h"
#include "NRPPa_EARFCN.h"
#include "NRPPa_PRS-Bandwidth-EUTRA.h"
#include "NRPPa_PRS-ConfigurationIndex-EUTRA.h"
#include "NRPPa_CPLength-EUTRA.h"
#include "NRPPa_NumberOfDlFrames-EUTRA.h"
#include "NRPPa_NumberOfAntennaPorts-EUTRA.h"
#include "NRPPa_SFNInitialisationTime-EUTRA.h"
#include "NRPPa_PRS-ID-EUTRA.h"
#include "NRPPa_TP-ID-EUTRA.h"
#include "NRPPa_TP-Type-EUTRA.h"
#include "NRPPa_NumberOfDlFrames-Extended-EUTRA.h"
#include "NRPPa_DL-Bandwidth-EUTRA.h"
#include "NRPPa_PRSOccasionGroup-EUTRA.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPa_OTDOACell_Information_Item_PR {
	NRPPa_OTDOACell_Information_Item_PR_NOTHING,	/* No components present */
	NRPPa_OTDOACell_Information_Item_PR_pCI_EUTRA,
	NRPPa_OTDOACell_Information_Item_PR_cGI_EUTRA,
	NRPPa_OTDOACell_Information_Item_PR_tAC,
	NRPPa_OTDOACell_Information_Item_PR_eARFCN,
	NRPPa_OTDOACell_Information_Item_PR_pRS_Bandwidth_EUTRA,
	NRPPa_OTDOACell_Information_Item_PR_pRS_ConfigurationIndex_EUTRA,
	NRPPa_OTDOACell_Information_Item_PR_cPLength_EUTRA,
	NRPPa_OTDOACell_Information_Item_PR_numberOfDlFrames_EUTRA,
	NRPPa_OTDOACell_Information_Item_PR_numberOfAntennaPorts_EUTRA,
	NRPPa_OTDOACell_Information_Item_PR_sFNInitialisationTime_EUTRA,
	NRPPa_OTDOACell_Information_Item_PR_nG_RANAccessPointPosition,
	NRPPa_OTDOACell_Information_Item_PR_pRSMutingConfiguration_EUTRA,
	NRPPa_OTDOACell_Information_Item_PR_prsid_EUTRA,
	NRPPa_OTDOACell_Information_Item_PR_tpid_EUTRA,
	NRPPa_OTDOACell_Information_Item_PR_tpType_EUTRA,
	NRPPa_OTDOACell_Information_Item_PR_numberOfDlFrames_Extended_EUTRA,
	NRPPa_OTDOACell_Information_Item_PR_crsCPlength_EUTRA,
	NRPPa_OTDOACell_Information_Item_PR_dL_Bandwidth_EUTRA,
	NRPPa_OTDOACell_Information_Item_PR_pRSOccasionGroup_EUTRA,
	NRPPa_OTDOACell_Information_Item_PR_pRSFrequencyHoppingConfiguration_EUTRA,
	NRPPa_OTDOACell_Information_Item_PR_choice_Extension
} NRPPa_OTDOACell_Information_Item_PR;

/* Forward declarations */
struct NRPPa_CGI_EUTRA;
struct NRPPa_NG_RANAccessPointPosition;
struct NRPPa_PRSMutingConfiguration_EUTRA;
struct NRPPa_PRSFrequencyHoppingConfiguration_EUTRA;
struct NRPPa_ProtocolIE_Single_Container;

/* NRPPa_OTDOACell-Information-Item */
typedef struct NRPPa_OTDOACell_Information_Item {
	NRPPa_OTDOACell_Information_Item_PR present;
	union NRPPa_OTDOACell_Information_Item_u {
		NRPPa_PCI_EUTRA_t	 pCI_EUTRA;
		struct NRPPa_CGI_EUTRA	*cGI_EUTRA;
		NRPPa_TAC_t	 tAC;
		NRPPa_EARFCN_t	 eARFCN;
		NRPPa_PRS_Bandwidth_EUTRA_t	 pRS_Bandwidth_EUTRA;
		NRPPa_PRS_ConfigurationIndex_EUTRA_t	 pRS_ConfigurationIndex_EUTRA;
		NRPPa_CPLength_EUTRA_t	 cPLength_EUTRA;
		NRPPa_NumberOfDlFrames_EUTRA_t	 numberOfDlFrames_EUTRA;
		NRPPa_NumberOfAntennaPorts_EUTRA_t	 numberOfAntennaPorts_EUTRA;
		NRPPa_SFNInitialisationTime_EUTRA_t	 sFNInitialisationTime_EUTRA;
		struct NRPPa_NG_RANAccessPointPosition	*nG_RANAccessPointPosition;
		struct NRPPa_PRSMutingConfiguration_EUTRA	*pRSMutingConfiguration_EUTRA;
		NRPPa_PRS_ID_EUTRA_t	 prsid_EUTRA;
		NRPPa_TP_ID_EUTRA_t	 tpid_EUTRA;
		NRPPa_TP_Type_EUTRA_t	 tpType_EUTRA;
		NRPPa_NumberOfDlFrames_Extended_EUTRA_t	 numberOfDlFrames_Extended_EUTRA;
		NRPPa_CPLength_EUTRA_t	 crsCPlength_EUTRA;
		NRPPa_DL_Bandwidth_EUTRA_t	 dL_Bandwidth_EUTRA;
		NRPPa_PRSOccasionGroup_EUTRA_t	 pRSOccasionGroup_EUTRA;
		struct NRPPa_PRSFrequencyHoppingConfiguration_EUTRA	*pRSFrequencyHoppingConfiguration_EUTRA;
		struct NRPPa_ProtocolIE_Single_Container	*choice_Extension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPa_OTDOACell_Information_Item_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NRPPa_OTDOACell_Information_Item;
extern asn_CHOICE_specifics_t asn_SPC_NRPPa_OTDOACell_Information_Item_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPa_OTDOACell_Information_Item_1[21];
extern asn_per_constraints_t asn_PER_type_NRPPa_OTDOACell_Information_Item_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPa_OTDOACell_Information_Item_H_ */
#include <asn_internal.h>
