/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r18.1.0/38455-i10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPa_ExtendedAdditionalPathList_Item_H_
#define	_NRPPa_ExtendedAdditionalPathList_Item_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NRPPa_RelativePathDelay.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct NRPPa_TrpMeasurementQuality;
struct NRPPa_MultipleULAoA;
struct NRPPa_UL_SRS_RSRPP;
struct NRPPa_ProtocolExtensionContainer;

/* NRPPa_ExtendedAdditionalPathList-Item */
typedef struct NRPPa_ExtendedAdditionalPathList_Item {
	NRPPa_RelativePathDelay_t	 relativeTimeOfPath;
	struct NRPPa_TrpMeasurementQuality	*pathQuality;	/* OPTIONAL */
	struct NRPPa_MultipleULAoA	*multipleULAoA;	/* OPTIONAL */
	struct NRPPa_UL_SRS_RSRPP	*pathPower;	/* OPTIONAL */
	struct NRPPa_ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPa_ExtendedAdditionalPathList_Item_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NRPPa_ExtendedAdditionalPathList_Item;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPa_ExtendedAdditionalPathList_Item_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPa_ExtendedAdditionalPathList_Item_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPa_ExtendedAdditionalPathList_Item_H_ */
#include <asn_internal.h>
