/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r18.1.0/38455-i10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPa_NG_RANCell_H_
#define	_NRPPa_NG_RANCell_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NRPPa_EUTRACellIdentifier.h"
#include "NRPPa_NRCellIdentifier.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPa_NG_RANCell_PR {
	NRPPa_NG_RANCell_PR_NOTHING,	/* No components present */
	NRPPa_NG_RANCell_PR_eUTRA_CellID,
	NRPPa_NG_RANCell_PR_nR_CellID,
	NRPPa_NG_RANCell_PR_choice_Extension
} NRPPa_NG_RANCell_PR;

/* Forward declarations */
struct NRPPa_ProtocolIE_Single_Container;

/* NRPPa_NG-RANCell */
typedef struct NRPPa_NG_RANCell {
	NRPPa_NG_RANCell_PR present;
	union NRPPa_NG_RANCell_u {
		NRPPa_EUTRACellIdentifier_t	 eUTRA_CellID;
		NRPPa_NRCellIdentifier_t	 nR_CellID;
		struct NRPPa_ProtocolIE_Single_Container	*choice_Extension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPa_NG_RANCell_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NRPPa_NG_RANCell;
extern asn_CHOICE_specifics_t asn_SPC_NRPPa_NG_RANCell_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPa_NG_RANCell_1[3];
extern asn_per_constraints_t asn_PER_type_NRPPa_NG_RANCell_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPa_NG_RANCell_H_ */
#include <asn_internal.h>
