/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r18.1.0/38455-i10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPa_TrpMeasurementTimingQuality_H_
#define	_NRPPa_TrpMeasurementTimingQuality_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPa_TrpMeasurementTimingQuality__resolution {
	NRPPa_TrpMeasurementTimingQuality__resolution_m0dot1	= 0,
	NRPPa_TrpMeasurementTimingQuality__resolution_m1	= 1,
	NRPPa_TrpMeasurementTimingQuality__resolution_m10	= 2,
	NRPPa_TrpMeasurementTimingQuality__resolution_m30	= 3
	/*
	 * Enumeration is extensible
	 */
} e_NRPPa_TrpMeasurementTimingQuality__resolution;

/* Forward declarations */
struct NRPPa_ProtocolExtensionContainer;

/* NRPPa_TrpMeasurementTimingQuality */
typedef struct NRPPa_TrpMeasurementTimingQuality {
	long	 measurementQuality;
	long	 resolution;
	struct NRPPa_ProtocolExtensionContainer	*iE_extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPa_TrpMeasurementTimingQuality_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_NRPPa_resolution_3;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_NRPPa_TrpMeasurementTimingQuality;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPa_TrpMeasurementTimingQuality_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPa_TrpMeasurementTimingQuality_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPa_TrpMeasurementTimingQuality_H_ */
#include <asn_internal.h>
