/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r18.1.0/38455-i10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPa_TransmissionCombPos_H_
#define	_NRPPa_TransmissionCombPos_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPa_TransmissionCombPos_PR {
	NRPPa_TransmissionCombPos_PR_NOTHING,	/* No components present */
	NRPPa_TransmissionCombPos_PR_n2,
	NRPPa_TransmissionCombPos_PR_n4,
	NRPPa_TransmissionCombPos_PR_n8,
	NRPPa_TransmissionCombPos_PR_choice_extension
} NRPPa_TransmissionCombPos_PR;

/* Forward declarations */
struct NRPPa_ProtocolIE_Single_Container;

/* NRPPa_TransmissionCombPos */
typedef struct NRPPa_TransmissionCombPos {
	NRPPa_TransmissionCombPos_PR present;
	union NRPPa_TransmissionCombPos_u {
		struct NRPPa_TransmissionCombPos__n2 {
			long	 combOffset_n2;
			long	 cyclicShift_n2;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} *n2;
		struct NRPPa_TransmissionCombPos__n4 {
			long	 combOffset_n4;
			long	 cyclicShift_n4;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} *n4;
		struct NRPPa_TransmissionCombPos__n8 {
			long	 combOffset_n8;
			long	 cyclicShift_n8;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} *n8;
		struct NRPPa_ProtocolIE_Single_Container	*choice_extension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPa_TransmissionCombPos_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NRPPa_TransmissionCombPos;
extern asn_CHOICE_specifics_t asn_SPC_NRPPa_TransmissionCombPos_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPa_TransmissionCombPos_1[4];
extern asn_per_constraints_t asn_PER_type_NRPPa_TransmissionCombPos_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPa_TransmissionCombPos_H_ */
#include <asn_internal.h>
