/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r18.1.0/38455-i10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPa_TRPMeasurementType_H_
#define	_NRPPa_TRPMeasurementType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPa_TRPMeasurementType {
	NRPPa_TRPMeasurementType_gNB_RxTxTimeDiff	= 0,
	NRPPa_TRPMeasurementType_uL_SRS_RSRP	= 1,
	NRPPa_TRPMeasurementType_uL_AoA	= 2,
	NRPPa_TRPMeasurementType_uL_RTOA	= 3,
	/*
	 * Enumeration is extensible
	 */
	NRPPa_TRPMeasurementType_multiple_UL_AoA	= 4,
	NRPPa_TRPMeasurementType_uL_SRS_RSRPP	= 5,
	NRPPa_TRPMeasurementType_ul_RSCP	= 6
} e_NRPPa_TRPMeasurementType;

/* NRPPa_TRPMeasurementType */
typedef long	 NRPPa_TRPMeasurementType_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_NRPPa_TRPMeasurementType_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_NRPPa_TRPMeasurementType;
extern const asn_INTEGER_specifics_t asn_SPC_NRPPa_TRPMeasurementType_specs_1;
asn_struct_free_f NRPPa_TRPMeasurementType_free;
asn_struct_print_f NRPPa_TRPMeasurementType_print;
asn_constr_check_f NRPPa_TRPMeasurementType_constraint;
per_type_decoder_f NRPPa_TRPMeasurementType_decode_aper;
per_type_encoder_f NRPPa_TRPMeasurementType_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPa_TRPMeasurementType_H_ */
#include <asn_internal.h>
