/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r18.1.0/38455-i10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPa_OTDOA_Information_Item_H_
#define	_NRPPa_OTDOA_Information_Item_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPa_OTDOA_Information_Item {
	NRPPa_OTDOA_Information_Item_pci	= 0,
	NRPPa_OTDOA_Information_Item_cGI	= 1,
	NRPPa_OTDOA_Information_Item_tac	= 2,
	NRPPa_OTDOA_Information_Item_earfcn	= 3,
	NRPPa_OTDOA_Information_Item_prsBandwidth	= 4,
	NRPPa_OTDOA_Information_Item_prsConfigIndex	= 5,
	NRPPa_OTDOA_Information_Item_cpLength	= 6,
	NRPPa_OTDOA_Information_Item_noDlFrames	= 7,
	NRPPa_OTDOA_Information_Item_noAntennaPorts	= 8,
	NRPPa_OTDOA_Information_Item_sFNInitTime	= 9,
	NRPPa_OTDOA_Information_Item_nG_RANAccessPointPosition	= 10,
	NRPPa_OTDOA_Information_Item_prsmutingconfiguration	= 11,
	NRPPa_OTDOA_Information_Item_prsid	= 12,
	NRPPa_OTDOA_Information_Item_tpid	= 13,
	NRPPa_OTDOA_Information_Item_tpType	= 14,
	NRPPa_OTDOA_Information_Item_crsCPlength	= 15,
	NRPPa_OTDOA_Information_Item_dlBandwidth	= 16,
	NRPPa_OTDOA_Information_Item_multipleprsConfigurationsperCell	= 17,
	NRPPa_OTDOA_Information_Item_prsOccasionGroup	= 18,
	NRPPa_OTDOA_Information_Item_prsFrequencyHoppingConfiguration	= 19,
	/*
	 * Enumeration is extensible
	 */
	NRPPa_OTDOA_Information_Item_tddConfig	= 20
} e_NRPPa_OTDOA_Information_Item;

/* NRPPa_OTDOA-Information-Item */
typedef long	 NRPPa_OTDOA_Information_Item_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_NRPPa_OTDOA_Information_Item_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_NRPPa_OTDOA_Information_Item;
extern const asn_INTEGER_specifics_t asn_SPC_NRPPa_OTDOA_Information_Item_specs_1;
asn_struct_free_f NRPPa_OTDOA_Information_Item_free;
asn_struct_print_f NRPPa_OTDOA_Information_Item_print;
asn_constr_check_f NRPPa_OTDOA_Information_Item_constraint;
per_type_decoder_f NRPPa_OTDOA_Information_Item_decode_aper;
per_type_encoder_f NRPPa_OTDOA_Information_Item_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPa_OTDOA_Information_Item_H_ */
#include <asn_internal.h>
