/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r18.1.0/38455-i10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPa_TRPInformationTypeResponseList_H_
#define	_NRPPa_TRPInformationTypeResponseList_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct NRPPa_TRPInformationTypeResponseItem;

/* NRPPa_TRPInformationTypeResponseList */
typedef struct NRPPa_TRPInformationTypeResponseList {
	A_SEQUENCE_OF(struct NRPPa_TRPInformationTypeResponseItem) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPa_TRPInformationTypeResponseList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NRPPa_TRPInformationTypeResponseList;
extern asn_SET_OF_specifics_t asn_SPC_NRPPa_TRPInformationTypeResponseList_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPa_TRPInformationTypeResponseList_1[1];
extern asn_per_constraints_t asn_PER_type_NRPPa_TRPInformationTypeResponseList_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPa_TRPInformationTypeResponseList_H_ */
#include <asn_internal.h>
