/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-PDU-Contents"
 * 	found in "../support/nrppa-r18.1.0/38455-i10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPa_SRSType_H_
#define	_NRPPa_SRSType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPa_SRSType_PR {
	NRPPa_SRSType_PR_NOTHING,	/* No components present */
	NRPPa_SRSType_PR_semipersistentSRS,
	NRPPa_SRSType_PR_aperiodicSRS,
	NRPPa_SRSType_PR_choice_Extension
} NRPPa_SRSType_PR;

/* Forward declarations */
struct NRPPa_SemipersistentSRS;
struct NRPPa_AperiodicSRS;
struct NRPPa_ProtocolIE_Single_Container;

/* NRPPa_SRSType */
typedef struct NRPPa_SRSType {
	NRPPa_SRSType_PR present;
	union NRPPa_SRSType_u {
		struct NRPPa_SemipersistentSRS	*semipersistentSRS;
		struct NRPPa_AperiodicSRS	*aperiodicSRS;
		struct NRPPa_ProtocolIE_Single_Container	*choice_Extension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPa_SRSType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NRPPa_SRSType;
extern asn_CHOICE_specifics_t asn_SPC_NRPPa_SRSType_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPa_SRSType_1[3];
extern asn_per_constraints_t asn_PER_type_NRPPa_SRSType_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPa_SRSType_H_ */
#include <asn_internal.h>
