/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r18.1.0/38455-i10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPa_ResourceTypePos_H_
#define	_NRPPa_ResourceTypePos_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPa_ResourceTypePos_PR {
	NRPPa_ResourceTypePos_PR_NOTHING,	/* No components present */
	NRPPa_ResourceTypePos_PR_periodic,
	NRPPa_ResourceTypePos_PR_semi_persistent,
	NRPPa_ResourceTypePos_PR_aperiodic,
	NRPPa_ResourceTypePos_PR_choice_extension
} NRPPa_ResourceTypePos_PR;

/* Forward declarations */
struct NRPPa_ResourceTypePeriodicPos;
struct NRPPa_ResourceTypeSemi_persistentPos;
struct NRPPa_ResourceTypeAperiodicPos;
struct NRPPa_ProtocolIE_Single_Container;

/* NRPPa_ResourceTypePos */
typedef struct NRPPa_ResourceTypePos {
	NRPPa_ResourceTypePos_PR present;
	union NRPPa_ResourceTypePos_u {
		struct NRPPa_ResourceTypePeriodicPos	*periodic;
		struct NRPPa_ResourceTypeSemi_persistentPos	*semi_persistent;
		struct NRPPa_ResourceTypeAperiodicPos	*aperiodic;
		struct NRPPa_ProtocolIE_Single_Container	*choice_extension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPa_ResourceTypePos_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NRPPa_ResourceTypePos;
extern asn_CHOICE_specifics_t asn_SPC_NRPPa_ResourceTypePos_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPa_ResourceTypePos_1[4];
extern asn_per_constraints_t asn_PER_type_NRPPa_ResourceTypePos_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPa_ResourceTypePos_H_ */
#include <asn_internal.h>
