/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r18.1.0/38455-i10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPa_AssistanceInformationMetaData_H_
#define	_NRPPa_AssistanceInformationMetaData_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPa_AssistanceInformationMetaData__encrypted {
	NRPPa_AssistanceInformationMetaData__encrypted_true	= 0
	/*
	 * Enumeration is extensible
	 */
} e_NRPPa_AssistanceInformationMetaData__encrypted;
typedef enum NRPPa_AssistanceInformationMetaData__gNSSID {
	NRPPa_AssistanceInformationMetaData__gNSSID_gps	= 0,
	NRPPa_AssistanceInformationMetaData__gNSSID_sbas	= 1,
	NRPPa_AssistanceInformationMetaData__gNSSID_qzss	= 2,
	NRPPa_AssistanceInformationMetaData__gNSSID_galileo	= 3,
	NRPPa_AssistanceInformationMetaData__gNSSID_glonass	= 4,
	NRPPa_AssistanceInformationMetaData__gNSSID_bds	= 5,
	NRPPa_AssistanceInformationMetaData__gNSSID_navic	= 6
	/*
	 * Enumeration is extensible
	 */
} e_NRPPa_AssistanceInformationMetaData__gNSSID;
typedef enum NRPPa_AssistanceInformationMetaData__sBASID {
	NRPPa_AssistanceInformationMetaData__sBASID_waas	= 0,
	NRPPa_AssistanceInformationMetaData__sBASID_egnos	= 1,
	NRPPa_AssistanceInformationMetaData__sBASID_msas	= 2,
	NRPPa_AssistanceInformationMetaData__sBASID_gagan	= 3
	/*
	 * Enumeration is extensible
	 */
} e_NRPPa_AssistanceInformationMetaData__sBASID;

/* Forward declarations */
struct NRPPa_ProtocolExtensionContainer;

/* NRPPa_AssistanceInformationMetaData */
typedef struct NRPPa_AssistanceInformationMetaData {
	long	*encrypted;	/* OPTIONAL */
	long	*gNSSID;	/* OPTIONAL */
	long	*sBASID;	/* OPTIONAL */
	struct NRPPa_ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPa_AssistanceInformationMetaData_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_NRPPa_encrypted_2;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_NRPPa_gNSSID_5;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_NRPPa_sBASID_14;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_NRPPa_AssistanceInformationMetaData;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPa_AssistanceInformationMetaData_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPa_AssistanceInformationMetaData_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPa_AssistanceInformationMetaData_H_ */
#include <asn_internal.h>
