/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r18.1.0/38455-i10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPa_ResourceSetType_H_
#define	_NRPPa_ResourceSetType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPa_ResourceSetType_PR {
	NRPPa_ResourceSetType_PR_NOTHING,	/* No components present */
	NRPPa_ResourceSetType_PR_periodic,
	NRPPa_ResourceSetType_PR_semi_persistent,
	NRPPa_ResourceSetType_PR_aperiodic,
	NRPPa_ResourceSetType_PR_choice_extension
} NRPPa_ResourceSetType_PR;

/* Forward declarations */
struct NRPPa_ResourceSetTypePeriodic;
struct NRPPa_ResourceSetTypeSemi_persistent;
struct NRPPa_ResourceSetTypeAperiodic;
struct NRPPa_ProtocolIE_Single_Container;

/* NRPPa_ResourceSetType */
typedef struct NRPPa_ResourceSetType {
	NRPPa_ResourceSetType_PR present;
	union NRPPa_ResourceSetType_u {
		struct NRPPa_ResourceSetTypePeriodic	*periodic;
		struct NRPPa_ResourceSetTypeSemi_persistent	*semi_persistent;
		struct NRPPa_ResourceSetTypeAperiodic	*aperiodic;
		struct NRPPa_ProtocolIE_Single_Container	*choice_extension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPa_ResourceSetType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NRPPa_ResourceSetType;
extern asn_CHOICE_specifics_t asn_SPC_NRPPa_ResourceSetType_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPa_ResourceSetType_1[4];
extern asn_per_constraints_t asn_PER_type_NRPPa_ResourceSetType_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPa_ResourceSetType_H_ */
#include <asn_internal.h>
