/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r18.1.0/38455-i10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPa_AggregatedPRSResourceSetList_H_
#define	_NRPPa_AggregatedPRSResourceSetList_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct NRPPa_AggregatedPRSResourceSet_Item;

/* NRPPa_AggregatedPRSResourceSetList */
typedef struct NRPPa_AggregatedPRSResourceSetList {
	A_SEQUENCE_OF(struct NRPPa_AggregatedPRSResourceSet_Item) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPa_AggregatedPRSResourceSetList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NRPPa_AggregatedPRSResourceSetList;

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPa_AggregatedPRSResourceSetList_H_ */
#include <asn_internal.h>
