/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r18.1.0/38455-i10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPa_TRPPositionDefinitionType_H_
#define	_NRPPa_TRPPositionDefinitionType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPa_TRPPositionDefinitionType_PR {
	NRPPa_TRPPositionDefinitionType_PR_NOTHING,	/* No components present */
	NRPPa_TRPPositionDefinitionType_PR_direct,
	NRPPa_TRPPositionDefinitionType_PR_referenced,
	NRPPa_TRPPositionDefinitionType_PR_choice_extension
} NRPPa_TRPPositionDefinitionType_PR;

/* Forward declarations */
struct NRPPa_TRPPositionDirect;
struct NRPPa_TRPPositionReferenced;
struct NRPPa_ProtocolIE_Single_Container;

/* NRPPa_TRPPositionDefinitionType */
typedef struct NRPPa_TRPPositionDefinitionType {
	NRPPa_TRPPositionDefinitionType_PR present;
	union NRPPa_TRPPositionDefinitionType_u {
		struct NRPPa_TRPPositionDirect	*direct;
		struct NRPPa_TRPPositionReferenced	*referenced;
		struct NRPPa_ProtocolIE_Single_Container	*choice_extension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPa_TRPPositionDefinitionType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NRPPa_TRPPositionDefinitionType;
extern asn_CHOICE_specifics_t asn_SPC_NRPPa_TRPPositionDefinitionType_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPa_TRPPositionDefinitionType_1[3];
extern asn_per_constraints_t asn_PER_type_NRPPa_TRPPositionDefinitionType_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPa_TRPPositionDefinitionType_H_ */
#include <asn_internal.h>
