/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r18.1.0/38455-i10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPa_CauseProtocol_H_
#define	_NRPPa_CauseProtocol_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPa_CauseProtocol {
	NRPPa_CauseProtocol_transfer_syntax_error	= 0,
	NRPPa_CauseProtocol_abstract_syntax_error_reject	= 1,
	NRPPa_CauseProtocol_abstract_syntax_error_ignore_and_notify	= 2,
	NRPPa_CauseProtocol_message_not_compatible_with_receiver_state	= 3,
	NRPPa_CauseProtocol_semantic_error	= 4,
	NRPPa_CauseProtocol_unspecified	= 5,
	NRPPa_CauseProtocol_abstract_syntax_error_falsely_constructed_message	= 6
	/*
	 * Enumeration is extensible
	 */
} e_NRPPa_CauseProtocol;

/* NRPPa_CauseProtocol */
typedef long	 NRPPa_CauseProtocol_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_NRPPa_CauseProtocol_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_NRPPa_CauseProtocol;
extern const asn_INTEGER_specifics_t asn_SPC_NRPPa_CauseProtocol_specs_1;
asn_struct_free_f NRPPa_CauseProtocol_free;
asn_struct_print_f NRPPa_CauseProtocol_print;
asn_constr_check_f NRPPa_CauseProtocol_constraint;
per_type_decoder_f NRPPa_CauseProtocol_decode_aper;
per_type_encoder_f NRPPa_CauseProtocol_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPa_CauseProtocol_H_ */
#include <asn_internal.h>
