/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r18.1.0/38455-i10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPa_CriticalityDiagnostics_H_
#define	_NRPPa_CriticalityDiagnostics_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NRPPa_ProcedureCode.h"
#include "NRPPa_TriggeringMessage.h"
#include "NRPPa_Criticality.h"
#include "NRPPa_NRPPATransactionID.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct NRPPa_CriticalityDiagnostics_IE_List;
struct NRPPa_ProtocolExtensionContainer;

/* NRPPa_CriticalityDiagnostics */
typedef struct NRPPa_CriticalityDiagnostics {
	NRPPa_ProcedureCode_t	*procedureCode;	/* OPTIONAL */
	NRPPa_TriggeringMessage_t	*triggeringMessage;	/* OPTIONAL */
	NRPPa_Criticality_t	*procedureCriticality;	/* OPTIONAL */
	NRPPa_NRPPATransactionID_t	*nrppatransactionID;	/* OPTIONAL */
	struct NRPPa_CriticalityDiagnostics_IE_List	*iEsCriticalityDiagnostics;	/* OPTIONAL */
	struct NRPPa_ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPa_CriticalityDiagnostics_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NRPPa_CriticalityDiagnostics;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPa_CriticalityDiagnostics_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPa_CriticalityDiagnostics_1[6];

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPa_CriticalityDiagnostics_H_ */
#include <asn_internal.h>
