/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r18.1.0/38455-i10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPa_TimeStamp_H_
#define	_NRPPa_TimeStamp_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NRPPa_SystemFrameNumber.h"
#include "NRPPa_TimeStampSlotIndex.h"
#include "NRPPa_RelativeTime1900.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct NRPPa_ProtocolExtensionContainer;

/* NRPPa_TimeStamp */
typedef struct NRPPa_TimeStamp {
	NRPPa_SystemFrameNumber_t	 systemFrameNumber;
	NRPPa_TimeStampSlotIndex_t	 slotIndex;
	NRPPa_RelativeTime1900_t	*measurementTime;	/* OPTIONAL */
	struct NRPPa_ProtocolExtensionContainer	*iE_Extension;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPa_TimeStamp_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NRPPa_TimeStamp;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPa_TimeStamp_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPa_TimeStamp_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPa_TimeStamp_H_ */
#include <asn_internal.h>
