/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r18.1.0/38455-i10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPa_DL_PRSResourceARPLocation_H_
#define	_NRPPa_DL_PRSResourceARPLocation_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPa_DL_PRSResourceARPLocation_PR {
	NRPPa_DL_PRSResourceARPLocation_PR_NOTHING,	/* No components present */
	NRPPa_DL_PRSResourceARPLocation_PR_relativeGeodeticLocation,
	NRPPa_DL_PRSResourceARPLocation_PR_relativeCartesianLocation,
	NRPPa_DL_PRSResourceARPLocation_PR_choice_Extension
} NRPPa_DL_PRSResourceARPLocation_PR;

/* Forward declarations */
struct NRPPa_RelativeGeodeticLocation;
struct NRPPa_RelativeCartesianLocation;
struct NRPPa_ProtocolIE_Single_Container;

/* NRPPa_DL-PRSResourceARPLocation */
typedef struct NRPPa_DL_PRSResourceARPLocation {
	NRPPa_DL_PRSResourceARPLocation_PR present;
	union NRPPa_DL_PRSResourceARPLocation_u {
		struct NRPPa_RelativeGeodeticLocation	*relativeGeodeticLocation;
		struct NRPPa_RelativeCartesianLocation	*relativeCartesianLocation;
		struct NRPPa_ProtocolIE_Single_Container	*choice_Extension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPa_DL_PRSResourceARPLocation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NRPPa_DL_PRSResourceARPLocation;
extern asn_CHOICE_specifics_t asn_SPC_NRPPa_DL_PRSResourceARPLocation_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPa_DL_PRSResourceARPLocation_1[3];
extern asn_per_constraints_t asn_PER_type_NRPPa_DL_PRSResourceARPLocation_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPa_DL_PRSResourceARPLocation_H_ */
#include <asn_internal.h>
