/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r18.1.0/38455-i10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPa_GNBRxTxTimeDiffMeas_H_
#define	_NRPPa_GNBRxTxTimeDiffMeas_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPa_GNBRxTxTimeDiffMeas_PR {
	NRPPa_GNBRxTxTimeDiffMeas_PR_NOTHING,	/* No components present */
	NRPPa_GNBRxTxTimeDiffMeas_PR_k0,
	NRPPa_GNBRxTxTimeDiffMeas_PR_k1,
	NRPPa_GNBRxTxTimeDiffMeas_PR_k2,
	NRPPa_GNBRxTxTimeDiffMeas_PR_k3,
	NRPPa_GNBRxTxTimeDiffMeas_PR_k4,
	NRPPa_GNBRxTxTimeDiffMeas_PR_k5,
	NRPPa_GNBRxTxTimeDiffMeas_PR_choice_extension
} NRPPa_GNBRxTxTimeDiffMeas_PR;

/* Forward declarations */
struct NRPPa_ProtocolIE_Single_Container;

/* NRPPa_GNBRxTxTimeDiffMeas */
typedef struct NRPPa_GNBRxTxTimeDiffMeas {
	NRPPa_GNBRxTxTimeDiffMeas_PR present;
	union NRPPa_GNBRxTxTimeDiffMeas_u {
		long	 k0;
		long	 k1;
		long	 k2;
		long	 k3;
		long	 k4;
		long	 k5;
		struct NRPPa_ProtocolIE_Single_Container	*choice_extension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPa_GNBRxTxTimeDiffMeas_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NRPPa_GNBRxTxTimeDiffMeas;
extern asn_CHOICE_specifics_t asn_SPC_NRPPa_GNBRxTxTimeDiffMeas_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPa_GNBRxTxTimeDiffMeas_1[7];
extern asn_per_constraints_t asn_PER_type_NRPPa_GNBRxTxTimeDiffMeas_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPa_GNBRxTxTimeDiffMeas_H_ */
#include <asn_internal.h>
