/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r18.1.0/38455-i10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#include "NRPPa_TxHoppingConfiguration.h"

#include "NRPPa_ProtocolExtensionContainer.h"
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static int
memb_NRPPa_numberOfHops_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 1L && value <= 6L)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_type_NRPPa_overlapValue_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  3 }	/* (0..3) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_memb_NRPPa_numberOfHops_constr_7 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  1,  6 }	/* (1..6) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
static const asn_INTEGER_enum_map_t asn_MAP_NRPPa_overlapValue_value2enum_2[] = {
	{ 0,	3,	"rb0" },
	{ 1,	3,	"rb1" },
	{ 2,	3,	"rb2" },
	{ 3,	3,	"rb4" }
};
static const unsigned int asn_MAP_NRPPa_overlapValue_enum2value_2[] = {
	0,	/* rb0(0) */
	1,	/* rb1(1) */
	2,	/* rb2(2) */
	3	/* rb4(3) */
};
static const asn_INTEGER_specifics_t asn_SPC_NRPPa_overlapValue_specs_2 = {
	asn_MAP_NRPPa_overlapValue_value2enum_2,	/* "tag" => N; sorted by tag */
	asn_MAP_NRPPa_overlapValue_enum2value_2,	/* N => "tag"; sorted by N */
	4,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_NRPPa_overlapValue_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_NRPPa_overlapValue_2 = {
	"overlapValue",
	"overlapValue",
	&asn_OP_NativeEnumerated,
	asn_DEF_NRPPa_overlapValue_tags_2,
	sizeof(asn_DEF_NRPPa_overlapValue_tags_2)
		/sizeof(asn_DEF_NRPPa_overlapValue_tags_2[0]) - 1, /* 1 */
	asn_DEF_NRPPa_overlapValue_tags_2,	/* Same as above */
	sizeof(asn_DEF_NRPPa_overlapValue_tags_2)
		/sizeof(asn_DEF_NRPPa_overlapValue_tags_2[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_NRPPa_overlapValue_constr_2,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_NRPPa_overlapValue_specs_2	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_NRPPa_TxHoppingConfiguration_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct NRPPa_TxHoppingConfiguration, overlapValue),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NRPPa_overlapValue_2,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"overlapValue"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct NRPPa_TxHoppingConfiguration, numberOfHops),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			&asn_PER_memb_NRPPa_numberOfHops_constr_7,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			memb_NRPPa_numberOfHops_constraint_1
		},
		0, 0, /* No default value */
		"numberOfHops"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct NRPPa_TxHoppingConfiguration, slotOffsetForRemainingHopsList),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NRPPa_SlotOffsetForRemainingHopsList,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"slotOffsetForRemainingHopsList"
		},
	{ ATF_POINTER, 1, offsetof(struct NRPPa_TxHoppingConfiguration, iE_extensions),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NRPPa_ProtocolExtensionContainer_4443P163,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"iE-extensions"
		},
};
static const int asn_MAP_NRPPa_TxHoppingConfiguration_oms_1[] = { 3 };
static const ber_tlv_tag_t asn_DEF_NRPPa_TxHoppingConfiguration_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_NRPPa_TxHoppingConfiguration_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* overlapValue */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* numberOfHops */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* slotOffsetForRemainingHopsList */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* iE-extensions */
};
asn_SEQUENCE_specifics_t asn_SPC_NRPPa_TxHoppingConfiguration_specs_1 = {
	sizeof(struct NRPPa_TxHoppingConfiguration),
	offsetof(struct NRPPa_TxHoppingConfiguration, _asn_ctx),
	asn_MAP_NRPPa_TxHoppingConfiguration_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_NRPPa_TxHoppingConfiguration_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	4,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_NRPPa_TxHoppingConfiguration = {
	"TxHoppingConfiguration",
	"TxHoppingConfiguration",
	&asn_OP_SEQUENCE,
	asn_DEF_NRPPa_TxHoppingConfiguration_tags_1,
	sizeof(asn_DEF_NRPPa_TxHoppingConfiguration_tags_1)
		/sizeof(asn_DEF_NRPPa_TxHoppingConfiguration_tags_1[0]), /* 1 */
	asn_DEF_NRPPa_TxHoppingConfiguration_tags_1,	/* Same as above */
	sizeof(asn_DEF_NRPPa_TxHoppingConfiguration_tags_1)
		/sizeof(asn_DEF_NRPPa_TxHoppingConfiguration_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_NRPPa_TxHoppingConfiguration_1,
	4,	/* Elements count */
	&asn_SPC_NRPPa_TxHoppingConfiguration_specs_1	/* Additional specs */
};

