/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r18.1.0/38455-i10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPa_MeasuredResultsValue_H_
#define	_NRPPa_MeasuredResultsValue_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPa_MeasuredResultsValue_PR {
	NRPPa_MeasuredResultsValue_PR_NOTHING,	/* No components present */
	NRPPa_MeasuredResultsValue_PR_valueAngleOfArrival_EUTRA,
	NRPPa_MeasuredResultsValue_PR_valueTimingAdvanceType1_EUTRA,
	NRPPa_MeasuredResultsValue_PR_valueTimingAdvanceType2_EUTRA,
	NRPPa_MeasuredResultsValue_PR_resultRSRP_EUTRA,
	NRPPa_MeasuredResultsValue_PR_resultRSRQ_EUTRA,
	NRPPa_MeasuredResultsValue_PR_choice_Extension
} NRPPa_MeasuredResultsValue_PR;

/* Forward declarations */
struct NRPPa_ResultRSRP_EUTRA;
struct NRPPa_ResultRSRQ_EUTRA;
struct NRPPa_ProtocolIE_Single_Container;

/* NRPPa_MeasuredResultsValue */
typedef struct NRPPa_MeasuredResultsValue {
	NRPPa_MeasuredResultsValue_PR present;
	union NRPPa_MeasuredResultsValue_u {
		long	 valueAngleOfArrival_EUTRA;
		long	 valueTimingAdvanceType1_EUTRA;
		long	 valueTimingAdvanceType2_EUTRA;
		struct NRPPa_ResultRSRP_EUTRA	*resultRSRP_EUTRA;
		struct NRPPa_ResultRSRQ_EUTRA	*resultRSRQ_EUTRA;
		struct NRPPa_MeasuredResultsValue_ExtensionIE	*choice_Extension; //This line was modified by NK!
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPa_MeasuredResultsValue_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NRPPa_MeasuredResultsValue;
extern asn_CHOICE_specifics_t asn_SPC_NRPPa_MeasuredResultsValue_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPa_MeasuredResultsValue_1[6];
extern asn_per_constraints_t asn_PER_type_NRPPa_MeasuredResultsValue_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPa_MeasuredResultsValue_H_ */
#include <asn_internal.h>
