/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r18.1.0/38455-i10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPa_RxTEG_H_
#define	_NRPPa_RxTEG_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NRPPa_TRP-Rx-TEGInformation.h"
#include "NRPPa_TRP-Tx-TEGInformation.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct NRPPa_ProtocolExtensionContainer;

/* NRPPa_RxTEG */
typedef struct NRPPa_RxTEG {
	NRPPa_TRP_Rx_TEGInformation_t	 tRP_Rx_TEGInformation;
	NRPPa_TRP_Tx_TEGInformation_t	 tRP_Tx_TEGInformation;
	struct NRPPa_ProtocolExtensionContainer	*iE_extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPa_RxTEG_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NRPPa_RxTEG;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPa_RxTEG_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPa_RxTEG_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPa_RxTEG_H_ */
#include <asn_internal.h>
