/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r18.1.0/38455-i10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPa_UETxTEGAssociationItem_H_
#define	_NRPPa_UETxTEGAssociationItem_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include "NRPPa_PosSRSResourceID-List.h"
#include "NRPPa_TimeStamp.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct NRPPa_CarrierFreq;
struct NRPPa_ProtocolExtensionContainer;

/* NRPPa_UETxTEGAssociationItem */
typedef struct NRPPa_UETxTEGAssociationItem {
	long	 uE_Tx_TEG_ID;
	NRPPa_PosSRSResourceID_List_t	 posSRSResourceID_List;
	NRPPa_TimeStamp_t	 timeStamp;
	struct NRPPa_CarrierFreq	*carrierFreq;	/* OPTIONAL */
	struct NRPPa_ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPa_UETxTEGAssociationItem_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NRPPa_UETxTEGAssociationItem;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPa_UETxTEGAssociationItem_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPa_UETxTEGAssociationItem_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPa_UETxTEGAssociationItem_H_ */
#include <asn_internal.h>
