/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r18.1.0/38455-i10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#include "NRPPa_PosSIB-Type.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_NRPPa_PosSIB_Type_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  6,  6,  0,  38 }	/* (0..38,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
static const asn_INTEGER_enum_map_t asn_MAP_NRPPa_PosSIB_Type_value2enum_1[] = {
	{ 0,	13,	"posSibType1-1" },
	{ 1,	13,	"posSibType1-2" },
	{ 2,	13,	"posSibType1-3" },
	{ 3,	13,	"posSibType1-4" },
	{ 4,	13,	"posSibType1-5" },
	{ 5,	13,	"posSibType1-6" },
	{ 6,	13,	"posSibType1-7" },
	{ 7,	13,	"posSibType1-8" },
	{ 8,	13,	"posSibType2-1" },
	{ 9,	13,	"posSibType2-2" },
	{ 10,	13,	"posSibType2-3" },
	{ 11,	13,	"posSibType2-4" },
	{ 12,	13,	"posSibType2-5" },
	{ 13,	13,	"posSibType2-6" },
	{ 14,	13,	"posSibType2-7" },
	{ 15,	13,	"posSibType2-8" },
	{ 16,	13,	"posSibType2-9" },
	{ 17,	14,	"posSibType2-10" },
	{ 18,	14,	"posSibType2-11" },
	{ 19,	14,	"posSibType2-12" },
	{ 20,	14,	"posSibType2-13" },
	{ 21,	14,	"posSibType2-14" },
	{ 22,	14,	"posSibType2-15" },
	{ 23,	14,	"posSibType2-16" },
	{ 24,	14,	"posSibType2-17" },
	{ 25,	14,	"posSibType2-18" },
	{ 26,	14,	"posSibType2-19" },
	{ 27,	14,	"posSibType2-20" },
	{ 28,	14,	"posSibType2-21" },
	{ 29,	14,	"posSibType2-22" },
	{ 30,	14,	"posSibType2-23" },
	{ 31,	14,	"posSibType2-24" },
	{ 32,	14,	"posSibType2-25" },
	{ 33,	13,	"posSibType3-1" },
	{ 34,	13,	"posSibType4-1" },
	{ 35,	13,	"posSibType5-1" },
	{ 36,	13,	"posSibType6-1" },
	{ 37,	13,	"posSibType6-2" },
	{ 38,	13,	"posSibType6-3" },
	{ 39,	13,	"posSibType1-9" },
	{ 40,	14,	"posSibType1-10" },
	{ 41,	13,	"posSibType6-4" },
	{ 42,	13,	"posSibType6-5" },
	{ 43,	13,	"posSibType6-6" }
	/* This list is extensible */
};
static const unsigned int asn_MAP_NRPPa_PosSIB_Type_enum2value_1[] = {
	0,	/* posSibType1-1(0) */
	40,	/* posSibType1-10(40) */
	1,	/* posSibType1-2(1) */
	2,	/* posSibType1-3(2) */
	3,	/* posSibType1-4(3) */
	4,	/* posSibType1-5(4) */
	5,	/* posSibType1-6(5) */
	6,	/* posSibType1-7(6) */
	7,	/* posSibType1-8(7) */
	39,	/* posSibType1-9(39) */
	8,	/* posSibType2-1(8) */
	17,	/* posSibType2-10(17) */
	18,	/* posSibType2-11(18) */
	19,	/* posSibType2-12(19) */
	20,	/* posSibType2-13(20) */
	21,	/* posSibType2-14(21) */
	22,	/* posSibType2-15(22) */
	23,	/* posSibType2-16(23) */
	24,	/* posSibType2-17(24) */
	25,	/* posSibType2-18(25) */
	26,	/* posSibType2-19(26) */
	9,	/* posSibType2-2(9) */
	27,	/* posSibType2-20(27) */
	28,	/* posSibType2-21(28) */
	29,	/* posSibType2-22(29) */
	30,	/* posSibType2-23(30) */
	31,	/* posSibType2-24(31) */
	32,	/* posSibType2-25(32) */
	10,	/* posSibType2-3(10) */
	11,	/* posSibType2-4(11) */
	12,	/* posSibType2-5(12) */
	13,	/* posSibType2-6(13) */
	14,	/* posSibType2-7(14) */
	15,	/* posSibType2-8(15) */
	16,	/* posSibType2-9(16) */
	33,	/* posSibType3-1(33) */
	34,	/* posSibType4-1(34) */
	35,	/* posSibType5-1(35) */
	36,	/* posSibType6-1(36) */
	37,	/* posSibType6-2(37) */
	38,	/* posSibType6-3(38) */
	41,	/* posSibType6-4(41) */
	42,	/* posSibType6-5(42) */
	43	/* posSibType6-6(43) */
	/* This list is extensible */
};
const asn_INTEGER_specifics_t asn_SPC_NRPPa_PosSIB_Type_specs_1 = {
	asn_MAP_NRPPa_PosSIB_Type_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_NRPPa_PosSIB_Type_enum2value_1,	/* N => "tag"; sorted by N */
	44,	/* Number of elements in the maps */
	40,	/* Extensions before this member */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_NRPPa_PosSIB_Type_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_NRPPa_PosSIB_Type = {
	"PosSIB-Type",
	"PosSIB-Type",
	&asn_OP_NativeEnumerated,
	asn_DEF_NRPPa_PosSIB_Type_tags_1,
	sizeof(asn_DEF_NRPPa_PosSIB_Type_tags_1)
		/sizeof(asn_DEF_NRPPa_PosSIB_Type_tags_1[0]), /* 1 */
	asn_DEF_NRPPa_PosSIB_Type_tags_1,	/* Same as above */
	sizeof(asn_DEF_NRPPa_PosSIB_Type_tags_1)
		/sizeof(asn_DEF_NRPPa_PosSIB_Type_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_NRPPa_PosSIB_Type_constr_1,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_NRPPa_PosSIB_Type_specs_1	/* Additional specs */
};

