/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r18.1.0/38455-i10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPa_TimingErrorMargin_H_
#define	_NRPPa_TimingErrorMargin_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPa_TimingErrorMargin {
	NRPPa_TimingErrorMargin_tc0	= 0,
	NRPPa_TimingErrorMargin_tc2	= 1,
	NRPPa_TimingErrorMargin_tc4	= 2,
	NRPPa_TimingErrorMargin_tc6	= 3,
	NRPPa_TimingErrorMargin_tc8	= 4,
	NRPPa_TimingErrorMargin_tc12	= 5,
	NRPPa_TimingErrorMargin_tc16	= 6,
	NRPPa_TimingErrorMargin_tc20	= 7,
	NRPPa_TimingErrorMargin_tc24	= 8,
	NRPPa_TimingErrorMargin_tc32	= 9,
	NRPPa_TimingErrorMargin_tc40	= 10,
	NRPPa_TimingErrorMargin_tc48	= 11,
	NRPPa_TimingErrorMargin_tc56	= 12,
	NRPPa_TimingErrorMargin_tc64	= 13,
	NRPPa_TimingErrorMargin_tc72	= 14,
	NRPPa_TimingErrorMargin_tc80	= 15
	/*
	 * Enumeration is extensible
	 */
} e_NRPPa_TimingErrorMargin;

/* NRPPa_TimingErrorMargin */
typedef long	 NRPPa_TimingErrorMargin_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_NRPPa_TimingErrorMargin_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_NRPPa_TimingErrorMargin;
extern const asn_INTEGER_specifics_t asn_SPC_NRPPa_TimingErrorMargin_specs_1;
asn_struct_free_f NRPPa_TimingErrorMargin_free;
asn_struct_print_f NRPPa_TimingErrorMargin_print;
asn_constr_check_f NRPPa_TimingErrorMargin_constraint;
per_type_decoder_f NRPPa_TimingErrorMargin_decode_aper;
per_type_encoder_f NRPPa_TimingErrorMargin_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPa_TimingErrorMargin_H_ */
#include <asn_internal.h>
