/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r18.1.0/38455-i10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPa_SRSResourceSet_Item_H_
#define	_NRPPa_SRSResourceSet_Item_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct NRPPa_PeriodicityList;
struct NRPPa_SpatialRelationInfo;
struct NRPPa_PathlossReferenceInformation;
struct NRPPa_ProtocolExtensionContainer;

/* NRPPa_SRSResourceSet-Item */
typedef struct NRPPa_SRSResourceSet_Item {
	long	*numberOfSRSResourcePerSet;	/* OPTIONAL */
	struct NRPPa_PeriodicityList	*periodicityList;	/* OPTIONAL */
	struct NRPPa_SpatialRelationInfo	*spatialRelationInformation;	/* OPTIONAL */
	struct NRPPa_PathlossReferenceInformation	*pathlossReferenceInformation;	/* OPTIONAL */
	struct NRPPa_ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPa_SRSResourceSet_Item_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NRPPa_SRSResourceSet_Item;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPa_SRSResourceSet_Item_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPa_SRSResourceSet_Item_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPa_SRSResourceSet_Item_H_ */
#include <asn_internal.h>
