/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r18.1.0/38455-i10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPa_ResultUTRAN_Item_H_
#define	_NRPPa_ResultUTRAN_Item_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NRPPa_UARFCN.h"
#include "NRPPa_UTRA-RSCP.h"
#include "NRPPa_UTRA-EcN0.h"
#include "NRPPa_PhysCellIDUTRA-FDD.h"
#include "NRPPa_PhysCellIDUTRA-TDD.h"
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPa_ResultUTRAN_Item__physCellIDUTRAN_PR {
	NRPPa_ResultUTRAN_Item__physCellIDUTRAN_PR_NOTHING,	/* No components present */
	NRPPa_ResultUTRAN_Item__physCellIDUTRAN_PR_physCellIDUTRA_FDD,
	NRPPa_ResultUTRAN_Item__physCellIDUTRAN_PR_physCellIDUTRA_TDD
} NRPPa_ResultUTRAN_Item__physCellIDUTRAN_PR;

/* Forward declarations */
struct NRPPa_ProtocolExtensionContainer;

/* NRPPa_ResultUTRAN-Item */
typedef struct NRPPa_ResultUTRAN_Item {
	NRPPa_UARFCN_t	 uARFCN;
	struct NRPPa_ResultUTRAN_Item__physCellIDUTRAN {
		NRPPa_ResultUTRAN_Item__physCellIDUTRAN_PR present;
		union NRPPa_ResultUTRAN_Item__NRPPa_physCellIDUTRAN_u {
			NRPPa_PhysCellIDUTRA_FDD_t	 physCellIDUTRA_FDD;
			NRPPa_PhysCellIDUTRA_TDD_t	 physCellIDUTRA_TDD;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} physCellIDUTRAN;
	NRPPa_UTRA_RSCP_t	*uTRA_RSCP;	/* OPTIONAL */
	NRPPa_UTRA_EcN0_t	*uTRA_EcN0;	/* OPTIONAL */
	struct NRPPa_ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPa_ResultUTRAN_Item_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NRPPa_ResultUTRAN_Item;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPa_ResultUTRAN_Item_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPa_ResultUTRAN_Item_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPa_ResultUTRAN_Item_H_ */
#include <asn_internal.h>
