/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r18.1.0/38455-i10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPa_BandwidthSRS_H_
#define	_NRPPa_BandwidthSRS_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPa_BandwidthSRS_PR {
	NRPPa_BandwidthSRS_PR_NOTHING,	/* No components present */
	NRPPa_BandwidthSRS_PR_fR1,
	NRPPa_BandwidthSRS_PR_fR2,
	NRPPa_BandwidthSRS_PR_choice_extension
} NRPPa_BandwidthSRS_PR;
typedef enum NRPPa_BandwidthSRS__fR1 {
	NRPPa_BandwidthSRS__fR1_mHz5	= 0,
	NRPPa_BandwidthSRS__fR1_mHz10	= 1,
	NRPPa_BandwidthSRS__fR1_mHz20	= 2,
	NRPPa_BandwidthSRS__fR1_mHz40	= 3,
	NRPPa_BandwidthSRS__fR1_mHz50	= 4,
	NRPPa_BandwidthSRS__fR1_mHz80	= 5,
	NRPPa_BandwidthSRS__fR1_mHz100	= 6,
	/*
	 * Enumeration is extensible
	 */
	NRPPa_BandwidthSRS__fR1_mHz160	= 7,
	NRPPa_BandwidthSRS__fR1_mHz200	= 8
} e_NRPPa_BandwidthSRS__fR1;
typedef enum NRPPa_BandwidthSRS__fR2 {
	NRPPa_BandwidthSRS__fR2_mHz50	= 0,
	NRPPa_BandwidthSRS__fR2_mHz100	= 1,
	NRPPa_BandwidthSRS__fR2_mHz200	= 2,
	NRPPa_BandwidthSRS__fR2_mHz400	= 3,
	/*
	 * Enumeration is extensible
	 */
	NRPPa_BandwidthSRS__fR2_mHz600	= 4,
	NRPPa_BandwidthSRS__fR2_mhz800	= 5,
	NRPPa_BandwidthSRS__fR2_mHz1600	= 6,
	NRPPa_BandwidthSRS__fR2_mHz2000	= 7
} e_NRPPa_BandwidthSRS__fR2;

/* Forward declarations */
struct NRPPa_ProtocolIE_Single_Container;

/* NRPPa_BandwidthSRS */
typedef struct NRPPa_BandwidthSRS {
	NRPPa_BandwidthSRS_PR present;
	union NRPPa_BandwidthSRS_u {
		long	 fR1;
		long	 fR2;
		struct NRPPa_ProtocolIE_Single_Container	*choice_extension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPa_BandwidthSRS_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_NRPPa_fR1_2;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_NRPPa_fR2_13;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_NRPPa_BandwidthSRS;
extern asn_CHOICE_specifics_t asn_SPC_NRPPa_BandwidthSRS_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPa_BandwidthSRS_1[3];
extern asn_per_constraints_t asn_PER_type_NRPPa_BandwidthSRS_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPa_BandwidthSRS_H_ */
#include <asn_internal.h>
