/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r18.1.0/38455-i10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPa_TRPTEGInformation_H_
#define	_NRPPa_TRPTEGInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPa_TRPTEGInformation_PR {
	NRPPa_TRPTEGInformation_PR_NOTHING,	/* No components present */
	NRPPa_TRPTEGInformation_PR_rxTx_TEG,
	NRPPa_TRPTEGInformation_PR_rx_TEG,
	NRPPa_TRPTEGInformation_PR_choice_extension
} NRPPa_TRPTEGInformation_PR;

/* Forward declarations */
struct NRPPa_RxTxTEG;
struct NRPPa_RxTEG;
struct NRPPa_ProtocolIE_Single_Container;

/* NRPPa_TRPTEGInformation */
typedef struct NRPPa_TRPTEGInformation {
	NRPPa_TRPTEGInformation_PR present;
	union NRPPa_TRPTEGInformation_u {
		struct NRPPa_RxTxTEG	*rxTx_TEG;
		struct NRPPa_RxTEG	*rx_TEG;
		struct NRPPa_ProtocolIE_Single_Container	*choice_extension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPa_TRPTEGInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NRPPa_TRPTEGInformation;
extern asn_CHOICE_specifics_t asn_SPC_NRPPa_TRPTEGInformation_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPa_TRPTEGInformation_1[3];
extern asn_per_constraints_t asn_PER_type_NRPPa_TRPTEGInformation_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPa_TRPTEGInformation_H_ */
#include <asn_internal.h>
