/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r18.1.0/38455-i10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPa_TRPPhaseQuality_H_
#define	_NRPPa_TRPPhaseQuality_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPa_TRPPhaseQuality__resolution {
	NRPPa_TRPPhaseQuality__resolution_deg0dot1	= 0,
	NRPPa_TRPPhaseQuality__resolution_deg1	= 1
	/*
	 * Enumeration is extensible
	 */
} e_NRPPa_TRPPhaseQuality__resolution;

/* Forward declarations */
struct NRPPa_ProtocolExtensionContainer;

/* NRPPa_TRPPhaseQuality */
typedef struct NRPPa_TRPPhaseQuality {
	long	 phaseQualityIndex;
	long	 resolution;
	struct NRPPa_ProtocolExtensionContainer	*iE_extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPa_TRPPhaseQuality_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_NRPPa_resolution_3;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_NRPPa_TRPPhaseQuality;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPa_TRPPhaseQuality_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPa_TRPPhaseQuality_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPa_TRPPhaseQuality_H_ */
#include <asn_internal.h>
