/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r18.1.0/38455-i10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPa_TimeWindowPeriodicitySRS_H_
#define	_NRPPa_TimeWindowPeriodicitySRS_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPa_TimeWindowPeriodicitySRS {
	NRPPa_TimeWindowPeriodicitySRS_ms0dot125	= 0,
	NRPPa_TimeWindowPeriodicitySRS_ms0dot25	= 1,
	NRPPa_TimeWindowPeriodicitySRS_ms0dot5	= 2,
	NRPPa_TimeWindowPeriodicitySRS_ms0dot625	= 3,
	NRPPa_TimeWindowPeriodicitySRS_ms1	= 4,
	NRPPa_TimeWindowPeriodicitySRS_ms1dot25	= 5,
	NRPPa_TimeWindowPeriodicitySRS_ms2	= 6,
	NRPPa_TimeWindowPeriodicitySRS_ms2dot5	= 7,
	NRPPa_TimeWindowPeriodicitySRS_ms4	= 8,
	NRPPa_TimeWindowPeriodicitySRS_ms5	= 9,
	NRPPa_TimeWindowPeriodicitySRS_ms8	= 10,
	NRPPa_TimeWindowPeriodicitySRS_ms10	= 11,
	NRPPa_TimeWindowPeriodicitySRS_ms16	= 12,
	NRPPa_TimeWindowPeriodicitySRS_ms20	= 13,
	NRPPa_TimeWindowPeriodicitySRS_ms32	= 14,
	NRPPa_TimeWindowPeriodicitySRS_ms40	= 15,
	NRPPa_TimeWindowPeriodicitySRS_ms64	= 16,
	NRPPa_TimeWindowPeriodicitySRS_ms80	= 17,
	NRPPa_TimeWindowPeriodicitySRS_ms160	= 18,
	NRPPa_TimeWindowPeriodicitySRS_ms320	= 19,
	NRPPa_TimeWindowPeriodicitySRS_ms640	= 20,
	NRPPa_TimeWindowPeriodicitySRS_ms1280	= 21,
	NRPPa_TimeWindowPeriodicitySRS_ms2560	= 22,
	NRPPa_TimeWindowPeriodicitySRS_ms5120	= 23,
	NRPPa_TimeWindowPeriodicitySRS_ms10240	= 24
	/*
	 * Enumeration is extensible
	 */
} e_NRPPa_TimeWindowPeriodicitySRS;

/* NRPPa_TimeWindowPeriodicitySRS */
typedef long	 NRPPa_TimeWindowPeriodicitySRS_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_NRPPa_TimeWindowPeriodicitySRS_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_NRPPa_TimeWindowPeriodicitySRS;
extern const asn_INTEGER_specifics_t asn_SPC_NRPPa_TimeWindowPeriodicitySRS_specs_1;
asn_struct_free_f NRPPa_TimeWindowPeriodicitySRS_free;
asn_struct_print_f NRPPa_TimeWindowPeriodicitySRS_print;
asn_constr_check_f NRPPa_TimeWindowPeriodicitySRS_constraint;
per_type_decoder_f NRPPa_TimeWindowPeriodicitySRS_decode_aper;
per_type_encoder_f NRPPa_TimeWindowPeriodicitySRS_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPa_TimeWindowPeriodicitySRS_H_ */
#include <asn_internal.h>
