/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r18.1.0/38455-i10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPa_HESSID_H_
#define	_NRPPa_HESSID_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* NRPPa_HESSID */
typedef OCTET_STRING_t	 NRPPa_HESSID_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_NRPPa_HESSID_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_NRPPa_HESSID;
asn_struct_free_f NRPPa_HESSID_free;
asn_struct_print_f NRPPa_HESSID_print;
asn_constr_check_f NRPPa_HESSID_constraint;
per_type_decoder_f NRPPa_HESSID_decode_aper;
per_type_encoder_f NRPPa_HESSID_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPa_HESSID_H_ */
#include <asn_internal.h>
