/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r18.1.0/38455-i10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPa_ResultNR_Item_H_
#define	_NRPPa_ResultNR_Item_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NRPPa_NR-PCI.h"
#include "NRPPa_NR-ARFCN.h"
#include "NRPPa_ValueRSRP-NR.h"
#include "NRPPa_ValueRSRQ-NR.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct NRPPa_ResultSS_RSRP_PerSSB;
struct NRPPa_ResultSS_RSRQ_PerSSB;
struct NRPPa_CGI_NR;
struct NRPPa_ProtocolExtensionContainer;

/* NRPPa_ResultNR-Item */
typedef struct NRPPa_ResultNR_Item {
	NRPPa_NR_PCI_t	 nR_PCI;
	NRPPa_NR_ARFCN_t	 nR_ARFCN;
	NRPPa_ValueRSRP_NR_t	*valueSS_RSRP_Cell;	/* OPTIONAL */
	NRPPa_ValueRSRQ_NR_t	*valueSS_RSRQ_Cell;	/* OPTIONAL */
	struct NRPPa_ResultSS_RSRP_PerSSB	*sS_RSRP_PerSSB;	/* OPTIONAL */
	struct NRPPa_ResultSS_RSRQ_PerSSB	*sS_RSRQ_PerSSB;	/* OPTIONAL */
	struct NRPPa_CGI_NR	*cGI_NR;	/* OPTIONAL */
	struct NRPPa_ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPa_ResultNR_Item_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NRPPa_ResultNR_Item;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPa_ResultNR_Item_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPa_ResultNR_Item_1[8];

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPa_ResultNR_Item_H_ */
#include <asn_internal.h>
