/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r18.1.0/38455-i10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPa_MeasuredFrequencyHops_H_
#define	_NRPPa_MeasuredFrequencyHops_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPa_MeasuredFrequencyHops {
	NRPPa_MeasuredFrequencyHops_singleHop	= 0,
	NRPPa_MeasuredFrequencyHops_multiHop	= 1
	/*
	 * Enumeration is extensible
	 */
} e_NRPPa_MeasuredFrequencyHops;

/* NRPPa_MeasuredFrequencyHops */
typedef long	 NRPPa_MeasuredFrequencyHops_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_NRPPa_MeasuredFrequencyHops_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_NRPPa_MeasuredFrequencyHops;
extern const asn_INTEGER_specifics_t asn_SPC_NRPPa_MeasuredFrequencyHops_specs_1;
asn_struct_free_f NRPPa_MeasuredFrequencyHops_free;
asn_struct_print_f NRPPa_MeasuredFrequencyHops_print;
asn_constr_check_f NRPPa_MeasuredFrequencyHops_constraint;
per_type_decoder_f NRPPa_MeasuredFrequencyHops_decode_aper;
per_type_encoder_f NRPPa_MeasuredFrequencyHops_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPa_MeasuredFrequencyHops_H_ */
#include <asn_internal.h>
