/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r18.1.0/38455-i10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPa_RequestedSRSTransmissionCharacteristics_H_
#define	_NRPPa_RequestedSRSTransmissionCharacteristics_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <NativeEnumerated.h>
#include "NRPPa_BandwidthSRS.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPa_RequestedSRSTransmissionCharacteristics__resourceType {
	NRPPa_RequestedSRSTransmissionCharacteristics__resourceType_periodic	= 0,
	NRPPa_RequestedSRSTransmissionCharacteristics__resourceType_semi_persistent	= 1,
	NRPPa_RequestedSRSTransmissionCharacteristics__resourceType_aperiodic	= 2
	/*
	 * Enumeration is extensible
	 */
} e_NRPPa_RequestedSRSTransmissionCharacteristics__resourceType;

/* Forward declarations */
struct NRPPa_SSBInfo;
struct NRPPa_ProtocolExtensionContainer;
struct NRPPa_SRSResourceSet_Item;

/* NRPPa_RequestedSRSTransmissionCharacteristics */
typedef struct NRPPa_RequestedSRSTransmissionCharacteristics {
	long	*numberOfTransmissions;	/* OPTIONAL */
	long	 resourceType;
	NRPPa_BandwidthSRS_t	 bandwidth;
	struct NRPPa_RequestedSRSTransmissionCharacteristics__listOfSRSResourceSet {
		A_SEQUENCE_OF(struct NRPPa_SRSResourceSet_Item) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *listOfSRSResourceSet;
	struct NRPPa_SSBInfo	*sSBInformation;	/* OPTIONAL */
	struct NRPPa_ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPa_RequestedSRSTransmissionCharacteristics_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_NRPPa_resourceType_3;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_NRPPa_RequestedSRSTransmissionCharacteristics;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPa_RequestedSRSTransmissionCharacteristics_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPa_RequestedSRSTransmissionCharacteristics_1[6];

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPa_RequestedSRSTransmissionCharacteristics_H_ */
#include <asn_internal.h>
