/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r18.1.0/38455-i10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPa_TRPInformationTypeItem_H_
#define	_NRPPa_TRPInformationTypeItem_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPa_TRPInformationTypeItem {
	NRPPa_TRPInformationTypeItem_nrPCI	= 0,
	NRPPa_TRPInformationTypeItem_nG_RAN_CGI	= 1,
	NRPPa_TRPInformationTypeItem_arfcn	= 2,
	NRPPa_TRPInformationTypeItem_pRSConfig	= 3,
	NRPPa_TRPInformationTypeItem_sSBInfo	= 4,
	NRPPa_TRPInformationTypeItem_sFNInitTime	= 5,
	NRPPa_TRPInformationTypeItem_spatialDirectInfo	= 6,
	NRPPa_TRPInformationTypeItem_geoCoord	= 7,
	/*
	 * Enumeration is extensible
	 */
	NRPPa_TRPInformationTypeItem_trp_type	= 8,
	NRPPa_TRPInformationTypeItem_ondemandPRSInfo	= 9,
	NRPPa_TRPInformationTypeItem_trpTxTeg	= 10,
	NRPPa_TRPInformationTypeItem_beam_antenna_info	= 11,
	NRPPa_TRPInformationTypeItem_mobile_trp_location_info	= 12,
	NRPPa_TRPInformationTypeItem_commonTA	= 13
} e_NRPPa_TRPInformationTypeItem;

/* NRPPa_TRPInformationTypeItem */
typedef long	 NRPPa_TRPInformationTypeItem_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_NRPPa_TRPInformationTypeItem_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_NRPPa_TRPInformationTypeItem;
extern const asn_INTEGER_specifics_t asn_SPC_NRPPa_TRPInformationTypeItem_specs_1;
asn_struct_free_f NRPPa_TRPInformationTypeItem_free;
asn_struct_print_f NRPPa_TRPInformationTypeItem_print;
asn_constr_check_f NRPPa_TRPInformationTypeItem_constraint;
per_type_decoder_f NRPPa_TRPInformationTypeItem_decode_aper;
per_type_encoder_f NRPPa_TRPInformationTypeItem_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPa_TRPInformationTypeItem_H_ */
#include <asn_internal.h>
