/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r18.1.0/38455-i10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#include "NRPPa_SlotOffsetRemainingHopsSemiPersistent.h"

#include "NRPPa_ProtocolExtensionContainer.h"
static int
memb_NRPPa_offset_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0L && value <= 81919L)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_memb_NRPPa_offset_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  17, -1,  0,  81919 }	/* (0..81919,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
asn_TYPE_member_t asn_MBR_NRPPa_SlotOffsetRemainingHopsSemiPersistent_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct NRPPa_SlotOffsetRemainingHopsSemiPersistent, sRSperiodicity),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NRPPa_SRSPeriodicity,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"sRSperiodicity"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct NRPPa_SlotOffsetRemainingHopsSemiPersistent, offset),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			&asn_PER_memb_NRPPa_offset_constr_3,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			memb_NRPPa_offset_constraint_1
		},
		0, 0, /* No default value */
		"offset"
		},
	{ ATF_POINTER, 1, offsetof(struct NRPPa_SlotOffsetRemainingHopsSemiPersistent, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NRPPa_ProtocolExtensionContainer_4443P110,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"iE-Extensions"
		},
};
static const int asn_MAP_NRPPa_SlotOffsetRemainingHopsSemiPersistent_oms_1[] = { 2 };
static const ber_tlv_tag_t asn_DEF_NRPPa_SlotOffsetRemainingHopsSemiPersistent_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_NRPPa_SlotOffsetRemainingHopsSemiPersistent_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* sRSperiodicity */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* offset */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* iE-Extensions */
};
asn_SEQUENCE_specifics_t asn_SPC_NRPPa_SlotOffsetRemainingHopsSemiPersistent_specs_1 = {
	sizeof(struct NRPPa_SlotOffsetRemainingHopsSemiPersistent),
	offsetof(struct NRPPa_SlotOffsetRemainingHopsSemiPersistent, _asn_ctx),
	asn_MAP_NRPPa_SlotOffsetRemainingHopsSemiPersistent_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_NRPPa_SlotOffsetRemainingHopsSemiPersistent_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_NRPPa_SlotOffsetRemainingHopsSemiPersistent = {
	"SlotOffsetRemainingHopsSemiPersistent",
	"SlotOffsetRemainingHopsSemiPersistent",
	&asn_OP_SEQUENCE,
	asn_DEF_NRPPa_SlotOffsetRemainingHopsSemiPersistent_tags_1,
	sizeof(asn_DEF_NRPPa_SlotOffsetRemainingHopsSemiPersistent_tags_1)
		/sizeof(asn_DEF_NRPPa_SlotOffsetRemainingHopsSemiPersistent_tags_1[0]), /* 1 */
	asn_DEF_NRPPa_SlotOffsetRemainingHopsSemiPersistent_tags_1,	/* Same as above */
	sizeof(asn_DEF_NRPPa_SlotOffsetRemainingHopsSemiPersistent_tags_1)
		/sizeof(asn_DEF_NRPPa_SlotOffsetRemainingHopsSemiPersistent_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_NRPPa_SlotOffsetRemainingHopsSemiPersistent_1,
	3,	/* Elements count */
	&asn_SPC_NRPPa_SlotOffsetRemainingHopsSemiPersistent_specs_1	/* Additional specs */
};

