/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r18.1.0/38455-i10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPa_PRSResource_QCLInfo_H_
#define	_NRPPa_PRSResource_QCLInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPa_PRSResource_QCLInfo_PR {
	NRPPa_PRSResource_QCLInfo_PR_NOTHING,	/* No components present */
	NRPPa_PRSResource_QCLInfo_PR_qCLSourceSSB,
	NRPPa_PRSResource_QCLInfo_PR_qCLSourcePRS,
	NRPPa_PRSResource_QCLInfo_PR_choice_Extension
} NRPPa_PRSResource_QCLInfo_PR;

/* Forward declarations */
struct NRPPa_PRSResource_QCLSourceSSB;
struct NRPPa_PRSResource_QCLSourcePRS;
struct NRPPa_ProtocolIE_Single_Container;

/* NRPPa_PRSResource-QCLInfo */
typedef struct NRPPa_PRSResource_QCLInfo {
	NRPPa_PRSResource_QCLInfo_PR present;
	union NRPPa_PRSResource_QCLInfo_u {
		struct NRPPa_PRSResource_QCLSourceSSB	*qCLSourceSSB;
		struct NRPPa_PRSResource_QCLSourcePRS	*qCLSourcePRS;
		struct NRPPa_ProtocolIE_Single_Container	*choice_Extension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPa_PRSResource_QCLInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NRPPa_PRSResource_QCLInfo;
extern asn_CHOICE_specifics_t asn_SPC_NRPPa_PRSResource_QCLInfo_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPa_PRSResource_QCLInfo_1[3];
extern asn_per_constraints_t asn_PER_type_NRPPa_PRSResource_QCLInfo_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPa_PRSResource_QCLInfo_H_ */
#include <asn_internal.h>
