/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r18.1.0/38455-i10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPa_OTDOACells_H_
#define	_NRPPa_OTDOACells_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include "NRPPa_OTDOACell-Information.h"
#include <constr_SEQUENCE.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct NRPPa_ProtocolExtensionContainer;

/* Forward definitions */
typedef struct NRPPa_OTDOACells__Member {
	NRPPa_OTDOACell_Information_t	 oTDOACellInfo;
	struct NRPPa_ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} OTDOACells__Member;

/* NRPPa_OTDOACells */
typedef struct NRPPa_OTDOACells {
	A_SEQUENCE_OF(OTDOACells__Member) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPa_OTDOACells_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NRPPa_OTDOACells;
extern asn_SET_OF_specifics_t asn_SPC_NRPPa_OTDOACells_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPa_OTDOACells_1[1];
extern asn_per_constraints_t asn_PER_type_NRPPa_OTDOACells_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPa_OTDOACells_H_ */
#include <asn_internal.h>
