/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r18.1.0/38455-i10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPa_SCS_SpecificCarrier_H_
#define	_NRPPa_SCS_SpecificCarrier_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPa_SCS_SpecificCarrier__subcarrierSpacing {
	NRPPa_SCS_SpecificCarrier__subcarrierSpacing_kHz15	= 0,
	NRPPa_SCS_SpecificCarrier__subcarrierSpacing_kHz30	= 1,
	NRPPa_SCS_SpecificCarrier__subcarrierSpacing_kHz60	= 2,
	NRPPa_SCS_SpecificCarrier__subcarrierSpacing_kHz120	= 3,
	/*
	 * Enumeration is extensible
	 */
	NRPPa_SCS_SpecificCarrier__subcarrierSpacing_kHz480	= 4,
	NRPPa_SCS_SpecificCarrier__subcarrierSpacing_kHz960	= 5
} e_NRPPa_SCS_SpecificCarrier__subcarrierSpacing;

/* Forward declarations */
struct NRPPa_ProtocolExtensionContainer;

/* NRPPa_SCS-SpecificCarrier */
typedef struct NRPPa_SCS_SpecificCarrier {
	long	 offsetToCarrier;
	long	 subcarrierSpacing;
	long	 carrierBandwidth;
	struct NRPPa_ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPa_SCS_SpecificCarrier_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_NRPPa_subcarrierSpacing_3;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_NRPPa_SCS_SpecificCarrier;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPa_SCS_SpecificCarrier_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPa_SCS_SpecificCarrier_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPa_SCS_SpecificCarrier_H_ */
#include <asn_internal.h>
