/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r18.1.0/38455-i10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPa_ReferenceSignal_H_
#define	_NRPPa_ReferenceSignal_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NRPPa_NZP-CSI-RS-ResourceID.h"
#include "NRPPa_SRSResourceID.h"
#include "NRPPa_SRSPosResourceID.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPa_ReferenceSignal_PR {
	NRPPa_ReferenceSignal_PR_NOTHING,	/* No components present */
	NRPPa_ReferenceSignal_PR_nZP_CSI_RS,
	NRPPa_ReferenceSignal_PR_sSB,
	NRPPa_ReferenceSignal_PR_sRS,
	NRPPa_ReferenceSignal_PR_positioningSRS,
	NRPPa_ReferenceSignal_PR_dL_PRS,
	NRPPa_ReferenceSignal_PR_choice_Extension
} NRPPa_ReferenceSignal_PR;

/* Forward declarations */
struct NRPPa_SSB;
struct NRPPa_DL_PRS;
struct NRPPa_ProtocolIE_Single_Container;

/* NRPPa_ReferenceSignal */
typedef struct NRPPa_ReferenceSignal {
	NRPPa_ReferenceSignal_PR present;
	union NRPPa_ReferenceSignal_u {
		NRPPa_NZP_CSI_RS_ResourceID_t	 nZP_CSI_RS;
		struct NRPPa_SSB	*sSB;
		NRPPa_SRSResourceID_t	 sRS;
		NRPPa_SRSPosResourceID_t	 positioningSRS;
		struct NRPPa_DL_PRS	*dL_PRS;
		struct NRPPa_ProtocolIE_Single_Container	*choice_Extension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPa_ReferenceSignal_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NRPPa_ReferenceSignal;
extern asn_CHOICE_specifics_t asn_SPC_NRPPa_ReferenceSignal_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPa_ReferenceSignal_1[6];
extern asn_per_constraints_t asn_PER_type_NRPPa_ReferenceSignal_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPa_ReferenceSignal_H_ */
#include <asn_internal.h>
