/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r18.1.0/38455-i10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPa_PeriodicityItem_H_
#define	_NRPPa_PeriodicityItem_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPa_PeriodicityItem {
	NRPPa_PeriodicityItem_ms0dot125	= 0,
	NRPPa_PeriodicityItem_ms0dot25	= 1,
	NRPPa_PeriodicityItem_ms0dot5	= 2,
	NRPPa_PeriodicityItem_ms0dot625	= 3,
	NRPPa_PeriodicityItem_ms1	= 4,
	NRPPa_PeriodicityItem_ms1dot25	= 5,
	NRPPa_PeriodicityItem_ms2	= 6,
	NRPPa_PeriodicityItem_ms2dot5	= 7,
	NRPPa_PeriodicityItem_ms4dot	= 8,
	NRPPa_PeriodicityItem_ms5	= 9,
	NRPPa_PeriodicityItem_ms8	= 10,
	NRPPa_PeriodicityItem_ms10	= 11,
	NRPPa_PeriodicityItem_ms16	= 12,
	NRPPa_PeriodicityItem_ms20	= 13,
	NRPPa_PeriodicityItem_ms32	= 14,
	NRPPa_PeriodicityItem_ms40	= 15,
	NRPPa_PeriodicityItem_ms64	= 16,
	NRPPa_PeriodicityItem_ms80m	= 17,
	NRPPa_PeriodicityItem_ms160	= 18,
	NRPPa_PeriodicityItem_ms320	= 19,
	NRPPa_PeriodicityItem_ms640m	= 20,
	NRPPa_PeriodicityItem_ms1280	= 21,
	NRPPa_PeriodicityItem_ms2560	= 22,
	NRPPa_PeriodicityItem_ms5120	= 23,
	NRPPa_PeriodicityItem_ms10240	= 24
	/*
	 * Enumeration is extensible
	 */
} e_NRPPa_PeriodicityItem;

/* NRPPa_PeriodicityItem */
typedef long	 NRPPa_PeriodicityItem_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_NRPPa_PeriodicityItem_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_NRPPa_PeriodicityItem;
extern const asn_INTEGER_specifics_t asn_SPC_NRPPa_PeriodicityItem_specs_1;
asn_struct_free_f NRPPa_PeriodicityItem_free;
asn_struct_print_f NRPPa_PeriodicityItem_print;
asn_constr_check_f NRPPa_PeriodicityItem_constraint;
per_type_decoder_f NRPPa_PeriodicityItem_decode_aper;
per_type_encoder_f NRPPa_PeriodicityItem_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPa_PeriodicityItem_H_ */
#include <asn_internal.h>
