/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r18.1.0/38455-i10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPa_CauseRadioNetwork_H_
#define	_NRPPa_CauseRadioNetwork_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPa_CauseRadioNetwork {
	NRPPa_CauseRadioNetwork_unspecified	= 0,
	NRPPa_CauseRadioNetwork_requested_item_not_supported	= 1,
	NRPPa_CauseRadioNetwork_requested_item_temporarily_not_available	= 2,
	/*
	 * Enumeration is extensible
	 */
	NRPPa_CauseRadioNetwork_serving_NG_RAN_node_changed	= 3,
	NRPPa_CauseRadioNetwork_requested_item_not_supported_on_time	= 4
} e_NRPPa_CauseRadioNetwork;

/* NRPPa_CauseRadioNetwork */
typedef long	 NRPPa_CauseRadioNetwork_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_NRPPa_CauseRadioNetwork_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_NRPPa_CauseRadioNetwork;
extern const asn_INTEGER_specifics_t asn_SPC_NRPPa_CauseRadioNetwork_specs_1;
asn_struct_free_f NRPPa_CauseRadioNetwork_free;
asn_struct_print_f NRPPa_CauseRadioNetwork_print;
asn_constr_check_f NRPPa_CauseRadioNetwork_constraint;
per_type_decoder_f NRPPa_CauseRadioNetwork_decode_aper;
per_type_encoder_f NRPPa_CauseRadioNetwork_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPa_CauseRadioNetwork_H_ */
#include <asn_internal.h>
