/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r18.1.0/38455-i10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#include "NRPPa_TRP-MeasurementUpdateItem.h"

#include "NRPPa_AoA-AssistanceInfo.h"
#include "NRPPa_ProtocolExtensionContainer.h"
asn_TYPE_member_t asn_MBR_NRPPa_TRP_MeasurementUpdateItem_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct NRPPa_TRP_MeasurementUpdateItem, tRP_ID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NRPPa_TRP_ID,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"tRP-ID"
		},
	{ ATF_POINTER, 2, offsetof(struct NRPPa_TRP_MeasurementUpdateItem, aoA_window_information),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NRPPa_AoA_AssistanceInfo,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"aoA-window-information"
		},
	{ ATF_POINTER, 1, offsetof(struct NRPPa_TRP_MeasurementUpdateItem, iE_extensions),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NRPPa_ProtocolExtensionContainer_4443P151,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"iE-extensions"
		},
};
static const int asn_MAP_NRPPa_TRP_MeasurementUpdateItem_oms_1[] = { 1, 2 };
static const ber_tlv_tag_t asn_DEF_NRPPa_TRP_MeasurementUpdateItem_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_NRPPa_TRP_MeasurementUpdateItem_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* tRP-ID */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* aoA-window-information */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* iE-extensions */
};
asn_SEQUENCE_specifics_t asn_SPC_NRPPa_TRP_MeasurementUpdateItem_specs_1 = {
	sizeof(struct NRPPa_TRP_MeasurementUpdateItem),
	offsetof(struct NRPPa_TRP_MeasurementUpdateItem, _asn_ctx),
	asn_MAP_NRPPa_TRP_MeasurementUpdateItem_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_NRPPa_TRP_MeasurementUpdateItem_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_NRPPa_TRP_MeasurementUpdateItem = {
	"TRP-MeasurementUpdateItem",
	"TRP-MeasurementUpdateItem",
	&asn_OP_SEQUENCE,
	asn_DEF_NRPPa_TRP_MeasurementUpdateItem_tags_1,
	sizeof(asn_DEF_NRPPa_TRP_MeasurementUpdateItem_tags_1)
		/sizeof(asn_DEF_NRPPa_TRP_MeasurementUpdateItem_tags_1[0]), /* 1 */
	asn_DEF_NRPPa_TRP_MeasurementUpdateItem_tags_1,	/* Same as above */
	sizeof(asn_DEF_NRPPa_TRP_MeasurementUpdateItem_tags_1)
		/sizeof(asn_DEF_NRPPa_TRP_MeasurementUpdateItem_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_NRPPa_TRP_MeasurementUpdateItem_1,
	3,	/* Elements count */
	&asn_SPC_NRPPa_TRP_MeasurementUpdateItem_specs_1	/* Additional specs */
};

