/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r18.1.0/38455-i10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#include "NRPPa_ExtendedAdditionalPathList-Item.h"

#include "NRPPa_TrpMeasurementQuality.h"
#include "NRPPa_MultipleULAoA.h"
#include "NRPPa_UL-SRS-RSRPP.h"
#include "NRPPa_ProtocolExtensionContainer.h"
asn_TYPE_member_t asn_MBR_NRPPa_ExtendedAdditionalPathList_Item_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct NRPPa_ExtendedAdditionalPathList_Item, relativeTimeOfPath),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_NRPPa_RelativePathDelay,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"relativeTimeOfPath"
		},
	{ ATF_POINTER, 4, offsetof(struct NRPPa_ExtendedAdditionalPathList_Item, pathQuality),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_NRPPa_TrpMeasurementQuality,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"pathQuality"
		},
	{ ATF_POINTER, 3, offsetof(struct NRPPa_ExtendedAdditionalPathList_Item, multipleULAoA),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NRPPa_MultipleULAoA,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"multipleULAoA"
		},
	{ ATF_POINTER, 2, offsetof(struct NRPPa_ExtendedAdditionalPathList_Item, pathPower),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NRPPa_UL_SRS_RSRPP,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"pathPower"
		},
	{ ATF_POINTER, 1, offsetof(struct NRPPa_ExtendedAdditionalPathList_Item, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NRPPa_ProtocolExtensionContainer_4443P7,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"iE-Extensions"
		},
};
static const int asn_MAP_NRPPa_ExtendedAdditionalPathList_Item_oms_1[] = { 1, 2, 3, 4 };
static const ber_tlv_tag_t asn_DEF_NRPPa_ExtendedAdditionalPathList_Item_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_NRPPa_ExtendedAdditionalPathList_Item_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* relativeTimeOfPath */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* pathQuality */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* multipleULAoA */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* pathPower */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* iE-Extensions */
};
asn_SEQUENCE_specifics_t asn_SPC_NRPPa_ExtendedAdditionalPathList_Item_specs_1 = {
	sizeof(struct NRPPa_ExtendedAdditionalPathList_Item),
	offsetof(struct NRPPa_ExtendedAdditionalPathList_Item, _asn_ctx),
	asn_MAP_NRPPa_ExtendedAdditionalPathList_Item_tag2el_1,
	5,	/* Count of tags in the map */
	asn_MAP_NRPPa_ExtendedAdditionalPathList_Item_oms_1,	/* Optional members */
	4, 0,	/* Root/Additions */
	5,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_NRPPa_ExtendedAdditionalPathList_Item = {
	"ExtendedAdditionalPathList-Item",
	"ExtendedAdditionalPathList-Item",
	&asn_OP_SEQUENCE,
	asn_DEF_NRPPa_ExtendedAdditionalPathList_Item_tags_1,
	sizeof(asn_DEF_NRPPa_ExtendedAdditionalPathList_Item_tags_1)
		/sizeof(asn_DEF_NRPPa_ExtendedAdditionalPathList_Item_tags_1[0]), /* 1 */
	asn_DEF_NRPPa_ExtendedAdditionalPathList_Item_tags_1,	/* Same as above */
	sizeof(asn_DEF_NRPPa_ExtendedAdditionalPathList_Item_tags_1)
		/sizeof(asn_DEF_NRPPa_ExtendedAdditionalPathList_Item_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_NRPPa_ExtendedAdditionalPathList_Item_1,
	5,	/* Elements count */
	&asn_SPC_NRPPa_ExtendedAdditionalPathList_Item_specs_1	/* Additional specs */
};

