/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r18.1.0/38455-i10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPa_PRS_Measurements_Info_List_Item_H_
#define	_NRPPa_PRS_Measurements_Info_List_Item_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPa_PRS_Measurements_Info_List_Item__measPRSPeriodicity {
	NRPPa_PRS_Measurements_Info_List_Item__measPRSPeriodicity_ms20	= 0,
	NRPPa_PRS_Measurements_Info_List_Item__measPRSPeriodicity_ms40	= 1,
	NRPPa_PRS_Measurements_Info_List_Item__measPRSPeriodicity_ms80	= 2,
	NRPPa_PRS_Measurements_Info_List_Item__measPRSPeriodicity_ms160	= 3
	/*
	 * Enumeration is extensible
	 */
} e_NRPPa_PRS_Measurements_Info_List_Item__measPRSPeriodicity;
typedef enum NRPPa_PRS_Measurements_Info_List_Item__measurementPRSLength {
	NRPPa_PRS_Measurements_Info_List_Item__measurementPRSLength_ms1dot5	= 0,
	NRPPa_PRS_Measurements_Info_List_Item__measurementPRSLength_ms3	= 1,
	NRPPa_PRS_Measurements_Info_List_Item__measurementPRSLength_ms3dot5	= 2,
	NRPPa_PRS_Measurements_Info_List_Item__measurementPRSLength_ms4	= 3,
	NRPPa_PRS_Measurements_Info_List_Item__measurementPRSLength_ms5dot5	= 4,
	NRPPa_PRS_Measurements_Info_List_Item__measurementPRSLength_ms6	= 5,
	NRPPa_PRS_Measurements_Info_List_Item__measurementPRSLength_ms10	= 6,
	NRPPa_PRS_Measurements_Info_List_Item__measurementPRSLength_ms20	= 7
} e_NRPPa_PRS_Measurements_Info_List_Item__measurementPRSLength;

/* Forward declarations */
struct NRPPa_ProtocolExtensionContainer;

/* NRPPa_PRS-Measurements-Info-List-Item */
typedef struct NRPPa_PRS_Measurements_Info_List_Item {
	long	 pointA;
	long	 measPRSPeriodicity;
	long	 measPRSOffset;
	long	 measurementPRSLength;
	struct NRPPa_ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPa_PRS_Measurements_Info_List_Item_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_NRPPa_measPRSPeriodicity_3;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_NRPPa_measurementPRSLength_10;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_NRPPa_PRS_Measurements_Info_List_Item;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPa_PRS_Measurements_Info_List_Item_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPa_PRS_Measurements_Info_List_Item_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPa_PRS_Measurements_Info_List_Item_H_ */
#include <asn_internal.h>
