/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r18.1.0/38455-i10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#include "NRPPa_PositioningBroadcastCells.h"

#include "NRPPa_NG-RAN-CGI.h"
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_NRPPa_PositioningBroadcastCells_constr_1 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 14,  14,  1,  16384 }	/* (SIZE(1..16384)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
asn_TYPE_member_t asn_MBR_NRPPa_PositioningBroadcastCells_1[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_NRPPa_NG_RAN_CGI,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_NRPPa_PositioningBroadcastCells_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_NRPPa_PositioningBroadcastCells_specs_1 = {
	sizeof(struct NRPPa_PositioningBroadcastCells),
	offsetof(struct NRPPa_PositioningBroadcastCells, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_NRPPa_PositioningBroadcastCells = {
	"PositioningBroadcastCells",
	"PositioningBroadcastCells",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_NRPPa_PositioningBroadcastCells_tags_1,
	sizeof(asn_DEF_NRPPa_PositioningBroadcastCells_tags_1)
		/sizeof(asn_DEF_NRPPa_PositioningBroadcastCells_tags_1[0]), /* 1 */
	asn_DEF_NRPPa_PositioningBroadcastCells_tags_1,	/* Same as above */
	sizeof(asn_DEF_NRPPa_PositioningBroadcastCells_tags_1)
		/sizeof(asn_DEF_NRPPa_PositioningBroadcastCells_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_NRPPa_PositioningBroadcastCells_constr_1,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_NRPPa_PositioningBroadcastCells_1,
	1,	/* Single element */
	&asn_SPC_NRPPa_PositioningBroadcastCells_specs_1	/* Additional specs */
};

