/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r18.1.0/38455-i10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPa_PosResourceSetType_H_
#define	_NRPPa_PosResourceSetType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPa_PosResourceSetType_PR {
	NRPPa_PosResourceSetType_PR_NOTHING,	/* No components present */
	NRPPa_PosResourceSetType_PR_periodic,
	NRPPa_PosResourceSetType_PR_semi_persistent,
	NRPPa_PosResourceSetType_PR_aperiodic,
	NRPPa_PosResourceSetType_PR_choice_extension
} NRPPa_PosResourceSetType_PR;

/* Forward declarations */
struct NRPPa_PosResourceSetTypePeriodic;
struct NRPPa_PosResourceSetTypeSemi_persistent;
struct NRPPa_PosResourceSetTypeAperiodic;
struct NRPPa_ProtocolIE_Single_Container;

/* NRPPa_PosResourceSetType */
typedef struct NRPPa_PosResourceSetType {
	NRPPa_PosResourceSetType_PR present;
	union NRPPa_PosResourceSetType_u {
		struct NRPPa_PosResourceSetTypePeriodic	*periodic;
		struct NRPPa_PosResourceSetTypeSemi_persistent	*semi_persistent;
		struct NRPPa_PosResourceSetTypeAperiodic	*aperiodic;
		struct NRPPa_ProtocolIE_Single_Container	*choice_extension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPa_PosResourceSetType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NRPPa_PosResourceSetType;
extern asn_CHOICE_specifics_t asn_SPC_NRPPa_PosResourceSetType_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPa_PosResourceSetType_1[4];
extern asn_per_constraints_t asn_PER_type_NRPPa_PosResourceSetType_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPa_PosResourceSetType_H_ */
#include <asn_internal.h>
