/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r18.1.0/38455-i10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPa_AssistanceInformationFailureList_H_
#define	_NRPPa_AssistanceInformationFailureList_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include "NRPPa_PosSIB-Type.h"
#include "NRPPa_Outcome.h"
#include <constr_SEQUENCE.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct NRPPa_ProtocolExtensionContainer;

/* Forward definitions */
typedef struct NRPPa_AssistanceInformationFailureList__Member {
	NRPPa_PosSIB_Type_t	 posSIB_Type;
	NRPPa_Outcome_t	 outcome;
	struct NRPPa_ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AssistanceInformationFailureList__Member;

/* NRPPa_AssistanceInformationFailureList */
typedef struct NRPPa_AssistanceInformationFailureList {
	A_SEQUENCE_OF(AssistanceInformationFailureList__Member) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPa_AssistanceInformationFailureList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NRPPa_AssistanceInformationFailureList;
extern asn_SET_OF_specifics_t asn_SPC_NRPPa_AssistanceInformationFailureList_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPa_AssistanceInformationFailureList_1[1];
extern asn_per_constraints_t asn_PER_type_NRPPa_AssistanceInformationFailureList_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPa_AssistanceInformationFailureList_H_ */
#include <asn_internal.h>
