/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r18.1.0/38455-i10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPa_TimeWindowInformation_Measurement_Item_H_
#define	_NRPPa_TimeWindowInformation_Measurement_Item_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NRPPa_TimeWindowDurationMeasurement.h"
#include <NativeEnumerated.h>
#include "NRPPa_TimeWindowPeriodicityMeasurement.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPa_TimeWindowInformation_Measurement_Item__timeWindowType {
	NRPPa_TimeWindowInformation_Measurement_Item__timeWindowType_single	= 0,
	NRPPa_TimeWindowInformation_Measurement_Item__timeWindowType_periodic	= 1
	/*
	 * Enumeration is extensible
	 */
} e_NRPPa_TimeWindowInformation_Measurement_Item__timeWindowType;

/* Forward declarations */
struct NRPPa_ProtocolExtensionContainer;

/* NRPPa_TimeWindowInformation-Measurement-Item */
typedef struct NRPPa_TimeWindowInformation_Measurement_Item {
	NRPPa_TimeWindowDurationMeasurement_t	 timeWindowDurationMeasurement;
	long	 timeWindowType;
	NRPPa_TimeWindowPeriodicityMeasurement_t	*timeWindowPeriodicityMeasurement;	/* OPTIONAL */
	struct NRPPa_ProtocolExtensionContainer	*iE_Extension;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPa_TimeWindowInformation_Measurement_Item_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_NRPPa_timeWindowType_3;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_NRPPa_TimeWindowInformation_Measurement_Item;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPa_TimeWindowInformation_Measurement_Item_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPa_TimeWindowInformation_Measurement_Item_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPa_TimeWindowInformation_Measurement_Item_H_ */
#include <asn_internal.h>
