/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r18.1.0/38455-i10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#include "NRPPa_BandwidthSRS.h"

#include "NRPPa_ProtocolIE-Single-Container.h"
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_type_NRPPa_fR1_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  3,  3,  0,  6 }	/* (0..6,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_type_NRPPa_fR2_constr_13 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  2,  2,  0,  3 }	/* (0..3,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_NRPPa_BandwidthSRS_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  2 }	/* (0..2) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
static const asn_INTEGER_enum_map_t asn_MAP_NRPPa_fR1_value2enum_2[] = {
	{ 0,	4,	"mHz5" },
	{ 1,	5,	"mHz10" },
	{ 2,	5,	"mHz20" },
	{ 3,	5,	"mHz40" },
	{ 4,	5,	"mHz50" },
	{ 5,	5,	"mHz80" },
	{ 6,	6,	"mHz100" },
	{ 7,	6,	"mHz160" },
	{ 8,	6,	"mHz200" }
	/* This list is extensible */
};
static const unsigned int asn_MAP_NRPPa_fR1_enum2value_2[] = {
	1,	/* mHz10(1) */
	6,	/* mHz100(6) */
	7,	/* mHz160(7) */
	2,	/* mHz20(2) */
	8,	/* mHz200(8) */
	3,	/* mHz40(3) */
	0,	/* mHz5(0) */
	4,	/* mHz50(4) */
	5	/* mHz80(5) */
	/* This list is extensible */
};
static const asn_INTEGER_specifics_t asn_SPC_NRPPa_fR1_specs_2 = {
	asn_MAP_NRPPa_fR1_value2enum_2,	/* "tag" => N; sorted by tag */
	asn_MAP_NRPPa_fR1_enum2value_2,	/* N => "tag"; sorted by N */
	9,	/* Number of elements in the maps */
	8,	/* Extensions before this member */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_NRPPa_fR1_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_NRPPa_fR1_2 = {
	"fR1",
	"fR1",
	&asn_OP_NativeEnumerated,
	asn_DEF_NRPPa_fR1_tags_2,
	sizeof(asn_DEF_NRPPa_fR1_tags_2)
		/sizeof(asn_DEF_NRPPa_fR1_tags_2[0]) - 1, /* 1 */
	asn_DEF_NRPPa_fR1_tags_2,	/* Same as above */
	sizeof(asn_DEF_NRPPa_fR1_tags_2)
		/sizeof(asn_DEF_NRPPa_fR1_tags_2[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_NRPPa_fR1_constr_2,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_NRPPa_fR1_specs_2	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_NRPPa_fR2_value2enum_13[] = {
	{ 0,	5,	"mHz50" },
	{ 1,	6,	"mHz100" },
	{ 2,	6,	"mHz200" },
	{ 3,	6,	"mHz400" },
	{ 4,	6,	"mHz600" },
	{ 5,	6,	"mhz800" },
	{ 6,	7,	"mHz1600" },
	{ 7,	7,	"mHz2000" }
	/* This list is extensible */
};
static const unsigned int asn_MAP_NRPPa_fR2_enum2value_13[] = {
	1,	/* mHz100(1) */
	6,	/* mHz1600(6) */
	2,	/* mHz200(2) */
	7,	/* mHz2000(7) */
	3,	/* mHz400(3) */
	0,	/* mHz50(0) */
	4,	/* mHz600(4) */
	5	/* mhz800(5) */
	/* This list is extensible */
};
static const asn_INTEGER_specifics_t asn_SPC_NRPPa_fR2_specs_13 = {
	asn_MAP_NRPPa_fR2_value2enum_13,	/* "tag" => N; sorted by tag */
	asn_MAP_NRPPa_fR2_enum2value_13,	/* N => "tag"; sorted by N */
	8,	/* Number of elements in the maps */
	5,	/* Extensions before this member */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_NRPPa_fR2_tags_13[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_NRPPa_fR2_13 = {
	"fR2",
	"fR2",
	&asn_OP_NativeEnumerated,
	asn_DEF_NRPPa_fR2_tags_13,
	sizeof(asn_DEF_NRPPa_fR2_tags_13)
		/sizeof(asn_DEF_NRPPa_fR2_tags_13[0]) - 1, /* 1 */
	asn_DEF_NRPPa_fR2_tags_13,	/* Same as above */
	sizeof(asn_DEF_NRPPa_fR2_tags_13)
		/sizeof(asn_DEF_NRPPa_fR2_tags_13[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_NRPPa_fR2_constr_13,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_NRPPa_fR2_specs_13	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_NRPPa_BandwidthSRS_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct NRPPa_BandwidthSRS, choice.fR1),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NRPPa_fR1_2,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"fR1"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct NRPPa_BandwidthSRS, choice.fR2),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NRPPa_fR2_13,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"fR2"
		},
	{ ATF_POINTER, 0, offsetof(struct NRPPa_BandwidthSRS, choice.choice_extension),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NRPPa_ProtocolIE_Single_Container_4422P5,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"choice-extension"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_NRPPa_BandwidthSRS_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* fR1 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* fR2 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* choice-extension */
};
asn_CHOICE_specifics_t asn_SPC_NRPPa_BandwidthSRS_specs_1 = {
	sizeof(struct NRPPa_BandwidthSRS),
	offsetof(struct NRPPa_BandwidthSRS, _asn_ctx),
	offsetof(struct NRPPa_BandwidthSRS, present),
	sizeof(((struct NRPPa_BandwidthSRS *)0)->present),
	asn_MAP_NRPPa_BandwidthSRS_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_NRPPa_BandwidthSRS = {
	"BandwidthSRS",
	"BandwidthSRS",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_NRPPa_BandwidthSRS_constr_1,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		CHOICE_constraint
	},
	asn_MBR_NRPPa_BandwidthSRS_1,
	3,	/* Elements count */
	&asn_SPC_NRPPa_BandwidthSRS_specs_1	/* Additional specs */
};

