/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r18.1.0/38455-i10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#include "NRPPa_DLPRSResourceSetARP.h"

#include "NRPPa_ProtocolExtensionContainer.h"
#include "NRPPa_DLPRSResourceARP.h"
static int
memb_NRPPa_listofDL_PRSResourceARP_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1UL && size <= 64UL)) {
		/* Perform validation of the inner elements */
		return SEQUENCE_OF_constraint(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_type_NRPPa_listofDL_PRSResourceARP_constr_4 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 6,  6,  1,  64 }	/* (SIZE(1..64)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_memb_NRPPa_listofDL_PRSResourceARP_constr_4 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 6,  6,  1,  64 }	/* (SIZE(1..64)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
static asn_TYPE_member_t asn_MBR_NRPPa_listofDL_PRSResourceARP_4[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_NRPPa_DLPRSResourceARP,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_NRPPa_listofDL_PRSResourceARP_tags_4[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_NRPPa_listofDL_PRSResourceARP_specs_4 = {
	sizeof(struct NRPPa_DLPRSResourceSetARP__listofDL_PRSResourceARP),
	offsetof(struct NRPPa_DLPRSResourceSetARP__listofDL_PRSResourceARP, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_NRPPa_listofDL_PRSResourceARP_4 = {
	"listofDL-PRSResourceARP",
	"listofDL-PRSResourceARP",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_NRPPa_listofDL_PRSResourceARP_tags_4,
	sizeof(asn_DEF_NRPPa_listofDL_PRSResourceARP_tags_4)
		/sizeof(asn_DEF_NRPPa_listofDL_PRSResourceARP_tags_4[0]) - 1, /* 1 */
	asn_DEF_NRPPa_listofDL_PRSResourceARP_tags_4,	/* Same as above */
	sizeof(asn_DEF_NRPPa_listofDL_PRSResourceARP_tags_4)
		/sizeof(asn_DEF_NRPPa_listofDL_PRSResourceARP_tags_4[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_NRPPa_listofDL_PRSResourceARP_constr_4,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_NRPPa_listofDL_PRSResourceARP_4,
	1,	/* Single element */
	&asn_SPC_NRPPa_listofDL_PRSResourceARP_specs_4	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_NRPPa_DLPRSResourceSetARP_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct NRPPa_DLPRSResourceSetARP, dl_PRSResourceSetID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NRPPa_PRS_Resource_Set_ID,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"dl-PRSResourceSetID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct NRPPa_DLPRSResourceSetARP, dL_PRSResourceSetARPLocation),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_NRPPa_DL_PRSResourceSetARPLocation,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"dL-PRSResourceSetARPLocation"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct NRPPa_DLPRSResourceSetARP, listofDL_PRSResourceARP),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		0,
		&asn_DEF_NRPPa_listofDL_PRSResourceARP_4,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			&asn_PER_memb_NRPPa_listofDL_PRSResourceARP_constr_4,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			memb_NRPPa_listofDL_PRSResourceARP_constraint_1
		},
		0, 0, /* No default value */
		"listofDL-PRSResourceARP"
		},
	{ ATF_POINTER, 1, offsetof(struct NRPPa_DLPRSResourceSetARP, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NRPPa_ProtocolExtensionContainer_4443P25,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"iE-Extensions"
		},
};
static const int asn_MAP_NRPPa_DLPRSResourceSetARP_oms_1[] = { 3 };
static const ber_tlv_tag_t asn_DEF_NRPPa_DLPRSResourceSetARP_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_NRPPa_DLPRSResourceSetARP_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* dl-PRSResourceSetID */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* dL-PRSResourceSetARPLocation */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* listofDL-PRSResourceARP */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* iE-Extensions */
};
asn_SEQUENCE_specifics_t asn_SPC_NRPPa_DLPRSResourceSetARP_specs_1 = {
	sizeof(struct NRPPa_DLPRSResourceSetARP),
	offsetof(struct NRPPa_DLPRSResourceSetARP, _asn_ctx),
	asn_MAP_NRPPa_DLPRSResourceSetARP_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_NRPPa_DLPRSResourceSetARP_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	4,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_NRPPa_DLPRSResourceSetARP = {
	"DLPRSResourceSetARP",
	"DLPRSResourceSetARP",
	&asn_OP_SEQUENCE,
	asn_DEF_NRPPa_DLPRSResourceSetARP_tags_1,
	sizeof(asn_DEF_NRPPa_DLPRSResourceSetARP_tags_1)
		/sizeof(asn_DEF_NRPPa_DLPRSResourceSetARP_tags_1[0]), /* 1 */
	asn_DEF_NRPPa_DLPRSResourceSetARP_tags_1,	/* Same as above */
	sizeof(asn_DEF_NRPPa_DLPRSResourceSetARP_tags_1)
		/sizeof(asn_DEF_NRPPa_DLPRSResourceSetARP_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_NRPPa_DLPRSResourceSetARP_1,
	4,	/* Elements count */
	&asn_SPC_NRPPa_DLPRSResourceSetARP_specs_1	/* Additional specs */
};

