/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r18.1.0/38455-i10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPa_TrpMeasuredResultsValue_H_
#define	_NRPPa_TrpMeasuredResultsValue_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NRPPa_UL-SRS-RSRP.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPa_TrpMeasuredResultsValue_PR {
	NRPPa_TrpMeasuredResultsValue_PR_NOTHING,	/* No components present */
	NRPPa_TrpMeasuredResultsValue_PR_uL_AngleOfArrival,
	NRPPa_TrpMeasuredResultsValue_PR_uL_SRS_RSRP,
	NRPPa_TrpMeasuredResultsValue_PR_uL_RTOA,
	NRPPa_TrpMeasuredResultsValue_PR_gNB_RxTxTimeDiff,
	NRPPa_TrpMeasuredResultsValue_PR_choice_extension
} NRPPa_TrpMeasuredResultsValue_PR;

/* Forward declarations */
struct NRPPa_UL_AoA;
struct NRPPa_UL_RTOAMeasurement;
struct NRPPa_GNB_RxTxTimeDiff;
struct NRPPa_ProtocolIE_Single_Container;

/* NRPPa_TrpMeasuredResultsValue */
typedef struct NRPPa_TrpMeasuredResultsValue {
	NRPPa_TrpMeasuredResultsValue_PR present;
	union NRPPa_TrpMeasuredResultsValue_u {
		struct NRPPa_UL_AoA	*uL_AngleOfArrival;
		NRPPa_UL_SRS_RSRP_t	 uL_SRS_RSRP;
		struct NRPPa_UL_RTOAMeasurement	*uL_RTOA;
		struct NRPPa_GNB_RxTxTimeDiff	*gNB_RxTxTimeDiff;
		struct NRPPa_ProtocolIE_Single_Container	*choice_extension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPa_TrpMeasuredResultsValue_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NRPPa_TrpMeasuredResultsValue;
extern asn_CHOICE_specifics_t asn_SPC_NRPPa_TrpMeasuredResultsValue_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPa_TrpMeasuredResultsValue_1[5];
extern asn_per_constraints_t asn_PER_type_NRPPa_TrpMeasuredResultsValue_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPa_TrpMeasuredResultsValue_H_ */
#include <asn_internal.h>
