/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r18.1.0/38455-i10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPa_Choice_TRP_Beam_Antenna_Info_Item_H_
#define	_NRPPa_Choice_TRP_Beam_Antenna_Info_Item_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NRPPa_TRP-ID.h"
#include <NULL.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPa_Choice_TRP_Beam_Antenna_Info_Item_PR {
	NRPPa_Choice_TRP_Beam_Antenna_Info_Item_PR_NOTHING,	/* No components present */
	NRPPa_Choice_TRP_Beam_Antenna_Info_Item_PR_reference,
	NRPPa_Choice_TRP_Beam_Antenna_Info_Item_PR_explicit,
	NRPPa_Choice_TRP_Beam_Antenna_Info_Item_PR_noChange,
	NRPPa_Choice_TRP_Beam_Antenna_Info_Item_PR_choice_extension
} NRPPa_Choice_TRP_Beam_Antenna_Info_Item_PR;

/* Forward declarations */
struct NRPPa_TRP_BeamAntennaExplicitInformation;
struct NRPPa_ProtocolIE_Single_Container;

/* NRPPa_Choice-TRP-Beam-Antenna-Info-Item */
typedef struct NRPPa_Choice_TRP_Beam_Antenna_Info_Item {
	NRPPa_Choice_TRP_Beam_Antenna_Info_Item_PR present;
	union NRPPa_Choice_TRP_Beam_Antenna_Info_Item_u {
		NRPPa_TRP_ID_t	 reference;
		struct NRPPa_TRP_BeamAntennaExplicitInformation	*Explicit;
		NULL_t	 noChange;
		struct NRPPa_ProtocolIE_Single_Container	*choice_extension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPa_Choice_TRP_Beam_Antenna_Info_Item_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NRPPa_Choice_TRP_Beam_Antenna_Info_Item;
extern asn_CHOICE_specifics_t asn_SPC_NRPPa_Choice_TRP_Beam_Antenna_Info_Item_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPa_Choice_TRP_Beam_Antenna_Info_Item_1[4];
extern asn_per_constraints_t asn_PER_type_NRPPa_Choice_TRP_Beam_Antenna_Info_Item_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPa_Choice_TRP_Beam_Antenna_Info_Item_H_ */
#include <asn_internal.h>
